// SPDX-License-Identifier: GPL-3.0-only

export const BACKTEST_PROGRESS_POLL_DELAY_MS = 500;
export const BACKTEST_PROGRESS_WRITE_INTERVAL_MS = 250;
export const BACKTEST_RESULT_CHUNK_SYMBOL_LIMIT = 200;
export const BACKTEST_RESULT_CHUNK_ROW_LIMIT = 5_000;
