// SPDX-License-Identifier: GPL-3.0-only
// This file is generated by tools/contracts/generate-openapi-contracts.mjs.
// Do not edit by hand; update contracts/openapi/*.yaml and regenerate.

import { z } from "zod";

import {
  desktopBacktestBatchListSchema,
  desktopBarsRangeSchema,
  desktopCustomIndicatorCompileRequestSchema,
  desktopCustomIndicatorCompileResultSchema,
  desktopCustomIndicatorExecuteRequestSchema,
  desktopCustomIndicatorExecuteResultSchema,
  desktopCustomIndicatorProfileDeleteRequestSchema,
  desktopCustomIndicatorProfileDeleteResultSchema,
  desktopCustomIndicatorProfileListSchema,
  desktopCustomIndicatorProfileSaveRequestSchema,
  desktopCustomIndicatorProfileSaveResultSchema,
  desktopCustomIndicatorProfilesReplaceRequestSchema,
  desktopCustomIndicatorProfilesReplaceResultSchema,
  desktopFreeReplayPoolDefaultEnvironmentRecordSchema,
  desktopFreeReplayPoolDefaultEnvironmentSchema,
  desktopFreeReplayPrepReadModelRequestSchema,
  desktopFreeReplayPrepReadModelSchema,
  desktopFreeReplayStartPointOverviewRangeSchema,
  desktopFreeReplayStartPointOverviewRequestSchema,
  desktopFreeReplayStartReadinessRequestSchema,
  desktopFreeReplayStartReadinessSchema,
  desktopInstrumentListSchema,
  desktopLegalDocumentResponseSchema,
  desktopLocalDataClearAllResultSchema,
  desktopLocalDataDeleteSourceResultSchema,
  desktopLocalDataImportControlRequestSchema,
  desktopLocalDataImportDraftValidationSchema,
  desktopLocalDataImportJobSchema,
  desktopLocalDataImportPreviewDiscardRequestSchema,
  desktopLocalDataImportPreviewDiscardResultSchema,
  desktopLocalDataImportPreviewJobSchema,
  desktopLocalDataRemoveSymbolsResultSchema,
  desktopLocalDataSourceDiagnosticProfileUpdateRequestSchema,
  desktopLocalDataSourceDiagnosticsSchema,
  desktopLocalDataSourceListSchema,
  desktopLocalDataSourceRemoveSymbolsRequestSchema,
  desktopLocalDataSourceSummarySchema,
  desktopLocalDataSourceSymbolDiagnosticsSchema,
  desktopLocalDataSyncPreviewByPathRequestSchema,
  desktopLocalDataSyncPreviewSchema,
  desktopLocalDataSyncQuickCheckSchema,
  desktopLocalImportMockSampleExportRequestSchema,
  desktopLocalImportMockSampleExportResultSchema,
  desktopMarketBarFrameSchema,
  desktopPortableExportPreviewRequestSchema,
  desktopPortableExportRequestSchema,
  desktopPortableImportInspectRequestSchema,
  desktopPortableImportRequestSchema,
  desktopPreparedFreeReplayStartRequestSchema,
  desktopPreparedFreeReplayStartResultSchema,
  desktopResetAllDataJobSchema,
  desktopSessionActionRequestSchema,
  desktopSessionBootstrapRequestSchema,
  desktopSessionBootstrapSchema,
  desktopSessionCreateRequestSchema,
  desktopSessionOrderQuoteRequestSchema,
  desktopSessionOrderQuoteSchema,
  desktopSessionSchema,
  desktopSessionSnapshotSchema,
  desktopSessionStepResultSchema,
  desktopSessionTradingSettingsUpdateRequestSchema,
  desktopSpecialTrainingBankDeleteResultSchema,
  desktopSpecialTrainingBankEditorReadModelRequestSchema,
  desktopSpecialTrainingBankEditorReadModelSchema,
  desktopSpecialTrainingBankListSchema,
  desktopSpecialTrainingBankSchema,
  desktopSpecialTrainingBankScopeSummarySchema,
  desktopSpecialTrainingChallengeActionRequestSchema,
  desktopSpecialTrainingChallengeActivityRequestSchema,
  desktopSpecialTrainingChallengeActivityResultSchema,
  desktopSpecialTrainingChallengeCommandResultSchema,
  desktopSpecialTrainingChallengeDiscardResultSchema,
  desktopSpecialTrainingChallengeProgressSchema,
  desktopSpecialTrainingChallengeRuntimeSchema,
  desktopSpecialTrainingChallengeSchema,
  desktopSpecialTrainingChallengeStartRequestSchema,
  desktopSpecialTrainingDecisionRequestSchema,
  desktopSpecialTrainingDurationEstimateSchema,
  desktopSpecialTrainingHistoryClearResultSchema,
  desktopSpecialTrainingHistoryQuestionDetailSchema,
  desktopSpecialTrainingHistorySessionDetailSchema,
  desktopSpecialTrainingHistorySessionListSchema,
  desktopSpecialTrainingOrderQuoteRequestSchema,
  desktopSpecialTrainingOrderQuoteSchema,
  desktopSpecialTrainingQuestionBankDraftPreviewRequestSchema,
  desktopSpecialTrainingQuestionBankPreviewRequestSchema,
  desktopSpecialTrainingQuestionBankResetRequestSchema,
  desktopSpecialTrainingQuestionBankSummarySchema,
  desktopSpecialTrainingQuestionSettleRequestSchema,
  desktopSpecialTrainingSettlementSchema,
  desktopSpecialTrainingStatsPayloadSchema,
  desktopSpecialTrainingStatsProjectDetailSchema,
  desktopSpecialTrainingStatsSummarySchema,
  desktopStartupLocalDataReinitializeRequestSchema,
  desktopStartupLocalDataReinitializeResultSchema,
  desktopSystemHealthSchema,
  desktopSystemStartupStatusSchema,
  desktopTrainingStatsSummarySchema,
} from "./api.js";

const desktopOpenApiDesktopAkshareAcquisitionInstrumentCatalogSchema = z.object({
  "instruments": z.array(z.lazy(() => desktopOpenApiDesktopAkshareAcquisitionInstrumentSchema)).min(1).max(10000),
  "cachedAt": z.string().max(64).datetime({ offset: true }),
}).strict();

const desktopOpenApiBacktestBatchCreateRequestSchema = z.object({
  "name": z.string().max(64).optional(),
  "config": z.lazy(() => desktopOpenApiBacktestConfigSchema),
}).strict();

const desktopOpenApiBacktestBatchRunRequestSchema = z.object({}).strict();

const desktopOpenApiBacktestBatchSchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "name": z.string().min(1).max(64),
  "status": z.lazy(() => desktopOpenApiBacktestBatchStatusSchema),
  "config": z.lazy(() => desktopOpenApiBacktestConfigSchema),
  "progress": z.record(z.string(), z.unknown()),
  "summary": z.record(z.string(), z.unknown()),
  "errorCode": z.string().nullable(),
  "errorMessage": z.string().nullable(),
  "createdAt": z.string().datetime({ offset: true }),
  "updatedAt": z.string().datetime({ offset: true }),
  "startedAt": z.string().datetime({ offset: true }).nullable(),
  "finishedAt": z.string().datetime({ offset: true }).nullable(),
}).strict();

const desktopOpenApiBacktestClearResultSchema = z.object({
  "deletedBatchIds": z.array(z.lazy(() => desktopOpenApiBoundedIdSchema)),
  "deletedBatchCount": z.number().int().min(0),
  "clearedAt": z.string().datetime({ offset: true }),
}).strict();

const desktopOpenApiBacktestDeleteResultSchema = z.object({
  "deletedBatchId": z.lazy(() => desktopOpenApiBoundedIdSchema),
}).strict();

const desktopOpenApiBacktestProgressSchema = z.object({
  "batch": z.lazy(() => desktopOpenApiBacktestBatchSchema),
  "progress": z.record(z.string(), z.unknown()),
}).strict();

const desktopOpenApiBacktestResultDetailSchema = z.object({
  "batch": z.lazy(() => desktopOpenApiBacktestBatchSchema),
  "result": z.lazy(() => desktopOpenApiBacktestResultSummarySchema),
  "fills": z.array(z.lazy(() => desktopOpenApiBacktestFillSchema)),
  "equityCurve": z.array(z.lazy(() => desktopOpenApiBacktestEquityPointSchema)),
}).strict();

const desktopOpenApiBacktestResultsSchema = z.object({
  "batch": z.lazy(() => desktopOpenApiBacktestBatchSchema),
  "results": z.array(z.lazy(() => desktopOpenApiBacktestResultListItemSchema)),
}).strict();

const desktopOpenApiDesktopCcxtAcquisitionMarketCatalogSchema = z.object({
  "exchangeId": z.enum(["binance", "okx"]),
  "markets": z.array(z.lazy(() => desktopOpenApiDesktopCcxtAcquisitionMarketSchema)).max(500),
  "cachedAt": z.string().max(64).datetime({ offset: true }),
}).strict();

const desktopOpenApiDesktopLocalDataFullReimportByPathRequestSchema = z.object({
  "previewToken": z.lazy(() => desktopOpenApiLongTokenSchema),
  "previewPlanId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "mapping": z.lazy(() => desktopOpenApiCsvMappingSchema).optional(),
  "userOverrides": z.lazy(() => desktopOpenApiDesktopLocalDataFullReimportUserOverridesSchema).optional(),
}).strict();

const desktopOpenApiDesktopLocalDataImportByPathRequestSchema = z.object({
  "previewToken": z.lazy(() => desktopOpenApiLongTokenSchema),
  "previewPlanId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "mapping": z.lazy(() => desktopOpenApiCsvMappingSchema).optional(),
  "userOverrides": z.lazy(() => desktopOpenApiDesktopLocalDataImportUserOverridesSchema).optional(),
}).strict();

const desktopOpenApiDesktopLocalDataImportDraftValidationRequestSchema = z.object({
  "previewToken": z.lazy(() => desktopOpenApiLongTokenSchema),
  "mapping": z.lazy(() => desktopOpenApiCsvMappingDraftSchema),
  "planDrafts": z.array(z.object({
    "previewPlanId": z.lazy(() => desktopOpenApiBoundedIdSchema),
    "tradingCalendar": z.lazy(() => desktopOpenApiTradingCalendarConfigSchema),
  }).strict()).max(500).optional(),
  "planning": z.object({
    "importEntryMode": z.enum(["GENERAL", "FULL_REIMPORT"]).optional(),
    "fullReimportTargetSourceId": z.string().max(128).optional(),
    "importTimeZone": z.string().min(1).max(128).optional(),
    "importTimeZoneMode": z.enum(["AUTO", "MANUAL"]).optional(),
    "timeZoneConfirmed": z.boolean().optional(),
    "timeZoneConfidence": z.enum(["HIGH", "MEDIUM", "LOW"]).optional(),
    "suggestedTimeZone": z.string().min(1).max(128).optional(),
    "suggestedTimeZoneReason": z.enum(["PRESET_DEFAULT", "RULE_INFERRED", "TIMESTAMP_INFERRED", "EXISTING_SOURCE", "SYSTEM_FALLBACK"]).optional(),
    "scopeStrategy": z.enum(["FLAT", "WITH_PARENT"]).optional(),
    "tradingCalendar": z.lazy(() => desktopOpenApiTradingCalendarConfigSchema).optional(),
    "tradingCalendarTouched": z.boolean().optional(),
    "repairWarningCount": z.number().int().min(0).optional(),
    "locale": z.string().max(32).optional(),
    "planOverrides": z.array(z.object({
      "previewPlanId": z.lazy(() => desktopOpenApiBoundedIdSchema),
      "targetSourceId": z.string().max(128).optional(),
      "sourceTouched": z.boolean().optional(),
      "poolName": z.string().max(20).optional(),
      "nameTouched": z.boolean().optional(),
    }).strict()).max(500).optional(),
  }).strict().optional(),
}).strict();

const desktopOpenApiDesktopLocalDataImportPreviewByPathRequestSchema = z.object({
  "folderPath": z.lazy(() => desktopOpenApiImportFolderPathSchema),
  "sourceFolderName": z.string().max(255).optional(),
  "sourceId": z.string().min(1).max(128).optional(),
  "locale": z.string().max(32).optional(),
}).strict();

const desktopOpenApiDesktopLocalDataIncrementalUpdateByPathRequestSchema = z.object({
  "previewToken": z.lazy(() => desktopOpenApiLongTokenSchema),
  "previewPlanId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "mapping": z.lazy(() => desktopOpenApiCsvMappingSchema).optional(),
  "userOverrides": z.lazy(() => desktopOpenApiDesktopLocalDataIncrementalUpdateUserOverridesSchema).optional(),
}).strict();

const desktopOpenApiDesktopLocalDataSourceTradingCalendarUpdateRequestSchema = z.object({
  "tradingCalendar": z.lazy(() => desktopOpenApiTradingCalendarConfigSchema),
}).strict();

const desktopOpenApiDesktopLocalDataSyncQuickCheckByMetadataRequestSchema = z.object({
  "sourceFolder": z.string().max(4096).regex(new RegExp("^(?:$|.*\\S.*)$")).optional(),
  "files": z.array(z.object({
    "relativePath": z.lazy(() => desktopOpenApiImportRelativePathSchema),
    "originalname": z.lazy(() => desktopOpenApiImportFileNameSchema).optional(),
    "size": z.number().int().min(0).max(21474836480).optional(),
    "mtimeMs": z.number().min(0).optional(),
    "fingerprint": z.string().max(65536).optional(),
  }).strict()).max(20000).optional(),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionCatalogSchema = z.object({
  "providers": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionProviderSchema)).min(3).max(3),
  "assetClasses": z.array(z.object({
    "id": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionAssetClassSchema),
    "marketIds": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionMarketIdSchema)).min(1).max(15),
  }).strict()).min(4).max(4),
  "markets": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionMarketSchema)).min(1).max(15),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionConnectorCatalogSchema = z.object({
  "connectors": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionConnectorSchema)).min(2).max(2),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionDiscardResultSchema = z.object({
  "discarded": z.boolean(),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionInstrumentCatalogSchema = z.object({
  "marketId": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionMarketIdSchema),
  "instruments": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionInstrumentSchema)).max(500),
  "nextCursor": z.string().min(1).max(128).nullable(),
  "cachedAt": z.string().max(64).datetime({ offset: true }).nullable(),
  "cacheState": z.enum(["FRESH", "STALE", "BUNDLED"]),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionJobCreateRequestSchema = z.union([z.lazy(() => desktopOpenApiDesktopAkshareAcquisitionJobCreateRequestSchema), z.lazy(() => desktopOpenApiDesktopCcxtAcquisitionJobCreateRequestSchema)]);

const desktopOpenApiDesktopMarketDataAcquisitionJobListSchema = z.object({
  "jobs": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionJobSummarySchema)).max(500),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionJobSchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "status": z.enum(["QUEUED", "RUNNING", "READY_TO_SAVE", "FAILED", "CANCELED"]),
  "connectorId": z.enum(["akshare", "ccxt"]),
  "request": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionJobCreateRequestSchema),
  "progress": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionJobProgressSchema),
  "staging": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionStagingSummarySchema).nullable(),
  "error": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionJobErrorSchema).nullable(),
  "createdAt": z.string().max(64).datetime({ offset: true }),
  "updatedAt": z.string().max(64).datetime({ offset: true }),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionMarketJobCreateRequestSchema = z.object({
  "marketId": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionMarketIdSchema),
  "sourcePlanId": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionSourcePlanIdSchema),
  "symbols": z.array(z.string().min(1).max(64)).min(1).max(20).refine((items) => new Set(items.map((item) => JSON.stringify(item))).size === items.length, { message: "uniqueItems" }),
  "timeframe": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionTimeframeSchema),
  "startAt": z.string().max(64).datetime({ offset: true }),
  "endAt": z.string().max(64).datetime({ offset: true }),
  "adjustment": z.enum(["none", "qfq", "hfq"]).nullable(),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionMarketJobSchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "status": z.enum(["QUEUED", "RUNNING", "READY_TO_SAVE", "FAILED", "CANCELED"]),
  "request": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionMarketJobCreateRequestSchema),
  "progress": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionJobProgressSchema),
  "sourceResults": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionSymbolSourceResultSchema)).max(20),
  "staging": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionStagingSummarySchema).nullable(),
  "error": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionJobErrorSchema).nullable(),
  "createdAt": z.string().max(64).datetime({ offset: true }),
  "updatedAt": z.string().max(64).datetime({ offset: true }),
}).strict();

const desktopOpenApiDesktopWorkspaceReadModelSchema = z.object({
  "workspaceId": z.lazy(() => desktopOpenApiDesktopWorkspaceIdSchema),
  "generatedAt": z.string().datetime({ offset: true }),
  "statusCode": z.string().min(1).max(64),
  "reasonCode": z.string().nullable(),
  "tone": z.lazy(() => desktopOpenApiDesktopWorkspaceReadModelToneSchema),
  "priority": z.number().int().min(0).max(100),
  "copy": z.lazy(() => desktopOpenApiDesktopWorkspaceCopyRefSchema).optional(),
  "facts": z.record(z.string(), z.unknown()),
  "actions": z.array(z.lazy(() => desktopOpenApiDesktopWorkspaceReadModelActionSchema)).max(64),
  "sections": z.array(z.lazy(() => desktopOpenApiDesktopWorkspaceReadModelSectionSchema)).max(64),
}).strict();

const desktopOpenApiDesktopAkshareAcquisitionInstrumentSchema = z.object({
  "symbol": z.string().min(6).max(12).regex(new RegExp("^(?:[0-9]{6}|INDEX-[0-9]{6})$")),
  "name": z.string().min(1).max(128),
  "exchangeId": z.enum(["SH", "SZ", "BJ"]),
  "kind": z.enum(["A_SHARE", "INDEX"]),
}).strict();

const desktopOpenApiBacktestConfigSchema = z.object({
  "name": z.string().max(64).optional(),
  "strategySource": z.string().min(1).max(65536),
  "parameterInputs": z.record(z.string(), z.string().max(128)).optional(),
  "instrumentIds": z.array(z.lazy(() => desktopOpenApiBoundedIdSchema)).max(20000).optional(),
  "samplePoolIds": z.array(z.lazy(() => desktopOpenApiBoundedIdSchema)).max(500).optional(),
  "startIndex": z.number().int().min(0).optional(),
  "endIndex": z.number().int().min(0).optional(),
  "startTime": z.string().datetime({ offset: true }).optional(),
  "endTime": z.string().datetime({ offset: true }).optional(),
  "initialCapital": z.number().gt(0),
  "priceMode": z.enum(["CUR_CLOSE", "NEXT_OPEN"]).optional(),
  "signalExecutionMode": z.enum(["CUR_CLOSE", "NEXT_OPEN"]).optional(),
  "orderSizing": z.lazy(() => desktopOpenApiBacktestOrderSizingSchema),
  "tradingSettings": z.lazy(() => desktopOpenApiBacktestTradingSettingsSchema),
  "signalRules": z.lazy(() => desktopOpenApiBacktestSignalRulesSchema).optional(),
}).strict();

const desktopOpenApiBoundedIdSchema = z.string().min(1).max(128);

const desktopOpenApiBacktestBatchStatusSchema = z.enum(["DRAFT", "QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED"]);

const desktopOpenApiBacktestResultSummarySchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "batchId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "instrumentId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "symbol": z.lazy(() => desktopOpenApiBoundedSymbolSchema),
  "timeframe": z.string().min(1).max(64),
  "barsCount": z.number().int().min(0),
  "finalEquity": z.number(),
  "totalPnl": z.number(),
  "profitRate": z.number(),
  "maxDrawdown": z.number(),
  "winRate": z.number(),
  "tradeCount": z.number().int().min(0),
  "conflictCount": z.number().int().min(0),
  "summary": z.record(z.string(), z.unknown()),
  "createdAt": z.string().datetime({ offset: true }),
  "updatedAt": z.string().datetime({ offset: true }),
}).strict();

const desktopOpenApiBacktestFillSchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "batchId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "resultId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "instrumentId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "symbol": z.lazy(() => desktopOpenApiBoundedSymbolSchema),
  "orderId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "fillIndex": z.number().int().min(0),
  "fillTime": z.string().datetime({ offset: true }),
  "side": z.enum(["BUY", "SELL"]),
  "price": z.number(),
  "qty": z.number(),
  "gross": z.number(),
  "fee": z.number(),
  "tax": z.number(),
  "slippage": z.number(),
  "createdAt": z.string().datetime({ offset: true }),
}).strict();

const desktopOpenApiBacktestEquityPointSchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "batchId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "resultId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "instrumentId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "symbol": z.lazy(() => desktopOpenApiBoundedSymbolSchema),
  "barIndex": z.number().int().min(0),
  "barTime": z.string().datetime({ offset: true }),
  "equity": z.number(),
  "drawdown": z.number(),
}).strict();

const desktopOpenApiBacktestResultListItemSchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "batchId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "instrumentId": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "symbol": z.lazy(() => desktopOpenApiBoundedSymbolSchema),
  "timeframe": z.string().min(1).max(64),
  "barsCount": z.number().int().min(0),
  "finalEquity": z.number(),
  "totalPnl": z.number(),
  "profitRate": z.number(),
  "maxDrawdown": z.number(),
  "winRate": z.number(),
  "tradeCount": z.number().int().min(0),
  "conflictCount": z.number().int().min(0),
  "createdAt": z.string().datetime({ offset: true }),
  "updatedAt": z.string().datetime({ offset: true }),
}).strict();

const desktopOpenApiDesktopCcxtAcquisitionMarketSchema = z.object({
  "symbol": z.string().min(3).max(64),
  "base": z.string().min(1).max(32),
  "quote": z.string().min(1).max(32),
  "active": z.literal(true),
}).strict();

const desktopOpenApiLongTokenSchema = z.string().min(1).max(65536);

const desktopOpenApiCsvMappingSchema = z.union([z.lazy(() => desktopOpenApiCsvMappingSingleTimestampSchema), z.lazy(() => desktopOpenApiCsvMappingSplitTimestampSchema)]);

const desktopOpenApiDesktopLocalDataFullReimportUserOverridesSchema = z.object({
  "sourceName": z.string().max(120).optional(),
  "sourceFolder": z.string().max(4096).regex(new RegExp("^(?:$|.*\\S.*)$")).optional(),
  "sourceFolderBookmarkId": z.lazy(() => desktopOpenApiSecurityBookmarkSchema).optional(),
  "timeZone": z.string().min(1).max(128).optional(),
  "timeZoneOrigin": z.enum(["PRESET_DEFAULT", "INFERRED_DEFAULT", "USER_SELECTED"]).optional(),
  "tradingCalendar": z.lazy(() => desktopOpenApiTradingCalendarConfigSchema).optional(),
  "allowExistingSourceTimeZoneChange": z.boolean().optional(),
}).strict();

const desktopOpenApiDesktopLocalDataImportUserOverridesSchema = z.object({
  "sourceName": z.string().max(120).optional(),
  "sourceFolder": z.string().max(4096).regex(new RegExp("^(?:$|.*\\S.*)$")).optional(),
  "sourceFolderBookmarkId": z.lazy(() => desktopOpenApiSecurityBookmarkSchema).optional(),
  "timeZone": z.string().min(1).max(128).optional(),
  "timeZoneOrigin": z.enum(["PRESET_DEFAULT", "INFERRED_DEFAULT", "USER_SELECTED"]).optional(),
  "tradingCalendar": z.lazy(() => desktopOpenApiTradingCalendarConfigSchema).optional(),
}).strict();

const desktopOpenApiCsvMappingDraftSchema = z.object({
  "timestampMode": z.enum(["SINGLE", "SPLIT"]).default("SINGLE"),
  "date": z.string().max(120).default(""),
  "time": z.string().max(120).default(""),
  "open": z.string().max(120).default(""),
  "high": z.string().max(120).default(""),
  "low": z.string().max(120).default(""),
  "close": z.string().max(120).default(""),
  "volume": z.string().max(120).default(""),
}).strict();

const desktopOpenApiTradingCalendarConfigSchema = z.object({
  "tradingDays": z.array(z.number().int().min(1).max(7)).min(1).max(7),
  "sessions": z.array(z.lazy(() => desktopOpenApiTradingSessionRangeSchema)).min(1).max(12),
}).strict();

const desktopOpenApiImportFolderPathSchema = z.string().min(1).max(4096).regex(new RegExp("\\S"));

const desktopOpenApiDesktopLocalDataIncrementalUpdateUserOverridesSchema = z.object({
  "sourceName": z.string().max(120).optional(),
  "sourceFolder": z.string().max(4096).regex(new RegExp("^(?:$|.*\\S.*)$")).optional(),
  "sourceFolderBookmarkId": z.lazy(() => desktopOpenApiSecurityBookmarkSchema).optional(),
  "sourceFolderUsageMode": z.enum(["BOUND_SOURCE", "ONE_OFF"]).optional(),
}).strict();

const desktopOpenApiImportRelativePathSchema = z.string().min(1).max(1024).regex(new RegExp("\\S"));

const desktopOpenApiImportFileNameSchema = z.string().max(255).regex(new RegExp("^(?:$|.*\\S.*)$"));

const desktopOpenApiDesktopMarketDataAcquisitionProviderSchema = z.object({
  "id": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionProviderIdSchema),
  "name": z.string().min(1).max(128),
  "version": z.string().min(1).max(64),
  "license": z.string().min(1).max(64),
  "projectUrl": z.string().min(1).max(2048),
  "docsUrl": z.string().min(1).max(2048),
  "termsUrl": z.string().min(1).max(2048),
  "termsRevision": z.string().min(1).max(128),
  "available": z.boolean(),
  "unavailabilityCode": z.string().min(1).max(128).nullable(),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionAssetClassSchema = z.enum(["STOCKS_AND_INDICES", "FOREX", "COMMODITIES_AND_RATES", "CRYPTO"]);

const desktopOpenApiDesktopMarketDataAcquisitionMarketIdSchema = z.enum(["CN_A_SHARE", "HK_STOCKS", "KR_STOCKS", "US_STOCKS", "JP_STOCKS", "VN_STOCKS", "GLOBAL_INDICES", "FOREX", "COMMODITY_FUTURES", "RATE_FUTURES", "CRYPTO_SPOT"]);

const desktopOpenApiDesktopMarketDataAcquisitionMarketSchema = z.object({
  "id": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionMarketIdSchema),
  "assetClassId": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionAssetClassSchema),
  "timeZone": z.string().min(1).max(128),
  "supportedTimeframes": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionTimeframeSchema)).min(1).max(4),
  "adjustmentOptions": z.array(z.enum(["none", "qfq", "hfq"])).max(3),
  "instrumentDiscovery": z.enum(["CATALOG", "PRESET"]),
  "sourcePlans": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionSourcePlanSchema)).min(1).max(3),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionConnectorSchema = z.object({
  "id": z.enum(["akshare", "ccxt"]),
  "version": z.string().min(1).max(64),
  "market": z.enum(["A_SHARE", "CRYPTO_SPOT"]),
  "available": z.boolean(),
  "unavailabilityCode": z.string().min(1).max(128).nullable(),
  "supportedTimeframes": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionTimeframeSchema)).min(1).max(4),
  "datasets": z.array(z.enum(["stock_zh_a_hist", "stock_zh_a_hist_min_em", "index_zh_a_hist"])).max(4),
  "exchanges": z.array(z.enum(["binance", "okx"])).max(2),
  "terms": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionConnectorTermsSchema),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionInstrumentSchema = z.object({
  "symbol": z.string().min(1).max(64),
  "name": z.string().min(1).max(128),
  "marketId": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionMarketIdSchema),
  "sourceSymbol": z.string().min(1).max(64),
  "exchangeId": z.string().min(1).max(64).nullable(),
  "sourcePlanIds": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionSourcePlanIdSchema)).min(1).max(3),
}).strict();

const desktopOpenApiDesktopAkshareAcquisitionJobCreateRequestSchema = z.union([z.lazy(() => desktopOpenApiDesktopAkshareDailyAcquisitionJobCreateRequestSchema), z.lazy(() => desktopOpenApiDesktopAkshareMinuteAcquisitionJobCreateRequestSchema), z.lazy(() => desktopOpenApiDesktopAkshareIndexDailyAcquisitionJobCreateRequestSchema)]);

const desktopOpenApiDesktopCcxtAcquisitionJobCreateRequestSchema = z.object({
  "connectorId": z.literal("ccxt"),
  "exchangeId": z.enum(["binance", "okx"]),
  "marketType": z.literal("spot"),
  "symbols": z.array(z.string().min(3).max(64).regex(new RegExp("^[A-Z0-9._-]+/[A-Z0-9._-]+$"))).min(1).max(20).refine((items) => new Set(items.map((item) => JSON.stringify(item))).size === items.length, { message: "uniqueItems" }),
  "timeframe": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionTimeframeSchema),
  "startAt": z.string().max(64).datetime({ offset: true }),
  "endAt": z.string().max(64).datetime({ offset: true }),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionJobSummarySchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "status": z.enum(["QUEUED", "RUNNING", "READY_TO_SAVE", "FAILED", "CANCELED"]),
  "marketId": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionMarketIdSchema),
  "sourcePlanId": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionSourcePlanIdSchema),
  "timeframe": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionTimeframeSchema),
  "symbolCount": z.number().int().min(1).max(20),
  "completedSymbols": z.number().int().min(0).max(20),
  "stage": z.enum(["QUEUED", "CONNECTING", "DOWNLOADING", "NORMALIZING", "VALIDATING", "RETRY_WAIT", "READY_TO_SAVE"]),
  "error": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionJobErrorSchema).nullable(),
  "createdAt": z.string().max(64).datetime({ offset: true }),
  "updatedAt": z.string().max(64).datetime({ offset: true }),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionJobProgressSchema = z.object({
  "stage": z.enum(["QUEUED", "CONNECTING", "DOWNLOADING", "NORMALIZING", "VALIDATING", "RETRY_WAIT", "READY_TO_SAVE"]),
  "completedSymbols": z.number().int().min(0).max(20),
  "totalSymbols": z.number().int().min(1).max(20),
  "retryAttempt": z.number().int().min(0).max(3),
  "retryAfterMs": z.number().int().min(0).max(10000),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionStagingSummarySchema = z.object({
  "fileCount": z.number().int().min(2).max(21),
  "totalBytes": z.number().int().min(1),
  "manifestSha256": z.string().regex(new RegExp("^[0-9a-f]{64}$")),
  "outputFolderName": z.string().min(1).max(128),
  "mergedDuplicateBars": z.number().int().min(0),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionJobErrorSchema = z.object({
  "code": z.string().min(1).max(128),
  "args": z.record(z.string(), z.unknown()),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionSourcePlanIdSchema = z.enum(["CN_A_SHARE_SMART", "FDR_HKEX", "FDR_KRX", "FDR_US_STOCKS", "FDR_TSE", "FDR_HOSE", "FDR_GLOBAL_INDICES", "FDR_FOREX", "FDR_COMMODITY_FUTURES", "FDR_RATE_FUTURES", "CCXT_BINANCE_SMART", "CCXT_OKX_SMART"]);

const desktopOpenApiDesktopMarketDataAcquisitionTimeframeSchema = z.enum(["1m", "5m", "1h", "1d"]);

const desktopOpenApiDesktopMarketDataAcquisitionSymbolSourceResultSchema = z.object({
  "symbol": z.string().min(1).max(64),
  "sourceSymbol": z.string().min(1).max(64),
  "finalSource": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionSourceAttemptSchema).nullable(),
  "attempts": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionSourceAttemptSchema)).min(1).max(3),
}).strict();

const desktopOpenApiDesktopWorkspaceIdSchema = z.enum(["command-center", "trainer", "history-review-console", "challenge-stats", "special-training", "data-management", "notes", "settings", "custom-indicator", "strategy-backtest"]);

const desktopOpenApiDesktopWorkspaceReadModelToneSchema = z.enum(["neutral", "ready", "loading", "warning", "danger", "locked"]);

const desktopOpenApiDesktopWorkspaceCopyRefSchema = z.object({
  "copyKey": z.string().min(1).max(128),
  "copyArgs": z.array(z.union([z.string(), z.number(), z.boolean()])).max(16).optional(),
}).strict();

const desktopOpenApiDesktopWorkspaceReadModelActionSchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "enabled": z.boolean(),
  "reasonCode": z.string().nullable(),
  "priority": z.number().int().min(0).max(100),
  "copy": z.lazy(() => desktopOpenApiDesktopWorkspaceCopyRefSchema).optional(),
  "facts": z.record(z.string(), z.unknown()).optional(),
}).strict();

const desktopOpenApiDesktopWorkspaceReadModelSectionSchema = z.object({
  "id": z.lazy(() => desktopOpenApiBoundedIdSchema),
  "statusCode": z.string().min(1).max(64),
  "reasonCode": z.string().nullable(),
  "tone": z.lazy(() => desktopOpenApiDesktopWorkspaceReadModelToneSchema),
  "priority": z.number().int().min(0).max(100),
  "copy": z.lazy(() => desktopOpenApiDesktopWorkspaceCopyRefSchema).optional(),
  "facts": z.record(z.string(), z.unknown()),
  "actions": z.array(z.lazy(() => desktopOpenApiDesktopWorkspaceReadModelActionSchema)).max(64),
}).strict();

const desktopOpenApiBacktestOrderSizingSchema = z.object({
  "mode": z.lazy(() => desktopOpenApiBacktestOrderSizingModeSchema),
  "value": z.number().min(0).optional(),
}).strict();

const desktopOpenApiBacktestTradingSettingsSchema = z.object({
  "assetClass": z.enum(["STOCK", "FUTURES", "FOREX", "CRYPTO"]),
  "marketPresetId": z.string().min(1).max(48),
  "minTradeStep": z.number().gt(0),
  "initialSecuritiesBalance": z.number().gt(0),
  "allowShortSelling": z.boolean(),
  "tradeSettlementMode": z.enum(["T0", "T1"]),
  "freeReplayEndSettlementMode": z.enum(["FORCE_CLOSE", "CURRENT_TOTAL_ASSET"]),
}).passthrough();

const desktopOpenApiBacktestSignalRulesSchema = z.object({
  "buy": z.lazy(() => desktopOpenApiBacktestDirectionSignalRuleSchema).optional(),
  "sell": z.lazy(() => desktopOpenApiBacktestDirectionSignalRuleSchema).optional(),
  "short": z.lazy(() => desktopOpenApiBacktestDirectionSignalRuleSchema).optional(),
  "cover": z.lazy(() => desktopOpenApiBacktestDirectionSignalRuleSchema).optional(),
}).strict();

const desktopOpenApiBoundedSymbolSchema = z.string().min(1).max(32);

const desktopOpenApiCsvMappingSingleTimestampSchema = z.object({
  "timestampMode": z.enum(["SINGLE"]).default("SINGLE"),
  "date": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "time": z.string().max(120).default(""),
  "open": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "high": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "low": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "close": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "volume": z.string().max(120).default(""),
}).strict();

const desktopOpenApiCsvMappingSplitTimestampSchema = z.object({
  "timestampMode": z.enum(["SPLIT"]),
  "date": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "time": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "open": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "high": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "low": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "close": z.lazy(() => desktopOpenApiCsvHeaderNameSchema),
  "volume": z.string().max(120).default(""),
}).strict();

const desktopOpenApiSecurityBookmarkSchema = z.string().max(16384);

const desktopOpenApiTradingSessionRangeSchema = z.object({
  "startMinute": z.number().int().min(0).max(1439),
  "endMinute": z.number().int().min(0).max(1440),
  "crossesMidnight": z.boolean(),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionProviderIdSchema = z.enum(["akshare", "ccxt", "financedatareader"]);

const desktopOpenApiDesktopMarketDataAcquisitionSourcePlanSchema = z.object({
  "id": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionSourcePlanIdSchema),
  "providerChain": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionProviderIdSchema)).min(1).max(3),
  "fallbackPolicy": z.enum(["NONE", "WHOLE_INSTRUMENT_DAILY_UNADJUSTED_ONLY", "WHOLE_INSTRUMENT_DAILY_ONLY"]),
  "available": z.boolean(),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionConnectorTermsSchema = z.object({
  "projects": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionProjectSchema)).min(1).max(2),
  "upstreams": z.array(z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionUpstreamTermsSchema)).min(1).max(2),
}).strict();

const desktopOpenApiDesktopAkshareDailyAcquisitionJobCreateRequestSchema = z.object({
  "connectorId": z.literal("akshare"),
  "dataset": z.literal("stock_zh_a_hist"),
  "symbols": z.array(z.string().min(1).max(32).regex(new RegExp("^[0-9]{6}$"))).min(1).max(20).refine((items) => new Set(items.map((item) => JSON.stringify(item))).size === items.length, { message: "uniqueItems" }),
  "timeframe": z.literal("1d"),
  "startAt": z.string().max(64).datetime({ offset: true }),
  "endAt": z.string().max(64).datetime({ offset: true }),
  "adjustment": z.enum(["none", "qfq", "hfq"]),
}).strict();

const desktopOpenApiDesktopAkshareMinuteAcquisitionJobCreateRequestSchema = z.object({
  "connectorId": z.literal("akshare"),
  "dataset": z.literal("stock_zh_a_hist_min_em"),
  "symbols": z.array(z.string().min(1).max(32).regex(new RegExp("^[0-9]{6}$"))).min(1).max(20).refine((items) => new Set(items.map((item) => JSON.stringify(item))).size === items.length, { message: "uniqueItems" }),
  "timeframe": z.enum(["1m", "5m", "1h"]),
  "startAt": z.string().max(64).datetime({ offset: true }),
  "endAt": z.string().max(64).datetime({ offset: true }),
  "adjustment": z.enum(["none", "qfq", "hfq"]),
}).strict();

const desktopOpenApiDesktopAkshareIndexDailyAcquisitionJobCreateRequestSchema = z.object({
  "connectorId": z.literal("akshare"),
  "dataset": z.literal("index_zh_a_hist"),
  "symbols": z.array(z.string().min(12).max(12).regex(new RegExp("^INDEX-[0-9]{6}$"))).min(1).max(20).refine((items) => new Set(items.map((item) => JSON.stringify(item))).size === items.length, { message: "uniqueItems" }),
  "timeframe": z.literal("1d"),
  "startAt": z.string().max(64).datetime({ offset: true }),
  "endAt": z.string().max(64).datetime({ offset: true }),
  "adjustment": z.literal("none"),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionSourceAttemptSchema = z.object({
  "providerId": z.lazy(() => desktopOpenApiDesktopMarketDataAcquisitionProviderIdSchema),
  "providerVersion": z.string().min(1).max(64),
  "upstreamId": z.string().min(1).max(128),
  "status": z.enum(["SUCCEEDED", "FAILED", "SKIPPED"]),
  "errorCode": z.string().min(1).max(128).nullable(),
}).strict();

const desktopOpenApiBacktestOrderSizingModeSchema = z.enum(["FIXED_QTY", "FIXED_AMOUNT", "EQUITY_PERCENT", "ALL_IN"]);

const desktopOpenApiBacktestDirectionSignalRuleSchema = z.object({
  "connector": z.enum(["AND", "OR"]),
  "conditions": z.array(z.lazy(() => desktopOpenApiBacktestSignalRuleConditionSchema)).min(1),
}).strict();

const desktopOpenApiCsvHeaderNameSchema = z.string().min(1).max(120).regex(new RegExp("\\S"));

const desktopOpenApiDesktopMarketDataAcquisitionProjectSchema = z.object({
  "id": z.enum(["akshare", "ccxt"]),
  "name": z.string().min(1).max(128),
  "url": z.string().min(1).max(2048),
  "infoUrl": z.string().min(1).max(2048),
  "version": z.string().min(1).max(64),
  "license": z.string().min(1).max(64),
}).strict();

const desktopOpenApiDesktopMarketDataAcquisitionUpstreamTermsSchema = z.object({
  "id": z.enum(["eastmoney", "binance", "okx"]),
  "upstreamName": z.string().min(1).max(128),
  "termsUrl": z.string().min(1).max(2048),
  "docsUrl": z.string().min(1).max(2048),
  "termsRevision": z.string().min(1).max(128),
}).strict();

const desktopOpenApiBacktestSignalRuleConditionSchema = z.object({
  "left": z.lazy(() => desktopOpenApiBacktestSignalRuleOperandSchema),
  "operator": z.lazy(() => desktopOpenApiBacktestSignalRuleOperatorSchema),
  "right": z.lazy(() => desktopOpenApiBacktestSignalRuleOperandSchema),
}).strict();

const desktopOpenApiBacktestSignalRuleOperandSchema = z.union([z.object({
  "kind": z.enum(["OUTPUT"]),
  "key": z.string().min(1).max(64).regex(new RegExp("^[A-Z_][A-Z0-9_]*$")),
}).strict(), z.object({
  "kind": z.enum(["PRICE"]),
  "field": z.enum(["CLOSE", "OPEN", "HIGH", "LOW", "VOLUME"]),
}).strict(), z.object({
  "kind": z.enum(["CONSTANT"]),
  "value": z.number(),
}).strict()]);

const desktopOpenApiBacktestSignalRuleOperatorSchema = z.enum(["CROSS_ABOVE", "CROSS_BELOW", "GREATER", "GREATER_EQUAL", "LESS", "LESS_EQUAL", "EQUAL"]);

export const DESKTOP_OPENAPI_COMPONENT_ZOD_SCHEMAS = {
  "DesktopAkshareAcquisitionInstrumentCatalog": desktopOpenApiDesktopAkshareAcquisitionInstrumentCatalogSchema,
  "BacktestBatchCreateRequest": desktopOpenApiBacktestBatchCreateRequestSchema,
  "BacktestBatchRunRequest": desktopOpenApiBacktestBatchRunRequestSchema,
  "BacktestBatch": desktopOpenApiBacktestBatchSchema,
  "BacktestClearResult": desktopOpenApiBacktestClearResultSchema,
  "BacktestDeleteResult": desktopOpenApiBacktestDeleteResultSchema,
  "BacktestProgress": desktopOpenApiBacktestProgressSchema,
  "BacktestResultDetail": desktopOpenApiBacktestResultDetailSchema,
  "BacktestResults": desktopOpenApiBacktestResultsSchema,
  "DesktopCcxtAcquisitionMarketCatalog": desktopOpenApiDesktopCcxtAcquisitionMarketCatalogSchema,
  "DesktopLocalDataFullReimportByPathRequest": desktopOpenApiDesktopLocalDataFullReimportByPathRequestSchema,
  "DesktopLocalDataImportByPathRequest": desktopOpenApiDesktopLocalDataImportByPathRequestSchema,
  "DesktopLocalDataImportDraftValidationRequest": desktopOpenApiDesktopLocalDataImportDraftValidationRequestSchema,
  "DesktopLocalDataImportPreviewByPathRequest": desktopOpenApiDesktopLocalDataImportPreviewByPathRequestSchema,
  "DesktopLocalDataIncrementalUpdateByPathRequest": desktopOpenApiDesktopLocalDataIncrementalUpdateByPathRequestSchema,
  "DesktopLocalDataSourceTradingCalendarUpdateRequest": desktopOpenApiDesktopLocalDataSourceTradingCalendarUpdateRequestSchema,
  "DesktopLocalDataSyncQuickCheckByMetadataRequest": desktopOpenApiDesktopLocalDataSyncQuickCheckByMetadataRequestSchema,
  "DesktopMarketDataAcquisitionCatalog": desktopOpenApiDesktopMarketDataAcquisitionCatalogSchema,
  "DesktopMarketDataAcquisitionConnectorCatalog": desktopOpenApiDesktopMarketDataAcquisitionConnectorCatalogSchema,
  "DesktopMarketDataAcquisitionDiscardResult": desktopOpenApiDesktopMarketDataAcquisitionDiscardResultSchema,
  "DesktopMarketDataAcquisitionInstrumentCatalog": desktopOpenApiDesktopMarketDataAcquisitionInstrumentCatalogSchema,
  "DesktopMarketDataAcquisitionJobCreateRequest": desktopOpenApiDesktopMarketDataAcquisitionJobCreateRequestSchema,
  "DesktopMarketDataAcquisitionJobList": desktopOpenApiDesktopMarketDataAcquisitionJobListSchema,
  "DesktopMarketDataAcquisitionJob": desktopOpenApiDesktopMarketDataAcquisitionJobSchema,
  "DesktopMarketDataAcquisitionMarketJobCreateRequest": desktopOpenApiDesktopMarketDataAcquisitionMarketJobCreateRequestSchema,
  "DesktopMarketDataAcquisitionMarketJob": desktopOpenApiDesktopMarketDataAcquisitionMarketJobSchema,
  "DesktopWorkspaceReadModel": desktopOpenApiDesktopWorkspaceReadModelSchema,
  "DesktopAkshareAcquisitionInstrument": desktopOpenApiDesktopAkshareAcquisitionInstrumentSchema,
  "BacktestConfig": desktopOpenApiBacktestConfigSchema,
  "BoundedId": desktopOpenApiBoundedIdSchema,
  "BacktestBatchStatus": desktopOpenApiBacktestBatchStatusSchema,
  "BacktestResultSummary": desktopOpenApiBacktestResultSummarySchema,
  "BacktestFill": desktopOpenApiBacktestFillSchema,
  "BacktestEquityPoint": desktopOpenApiBacktestEquityPointSchema,
  "BacktestResultListItem": desktopOpenApiBacktestResultListItemSchema,
  "DesktopCcxtAcquisitionMarket": desktopOpenApiDesktopCcxtAcquisitionMarketSchema,
  "LongToken": desktopOpenApiLongTokenSchema,
  "CsvMapping": desktopOpenApiCsvMappingSchema,
  "DesktopLocalDataFullReimportUserOverrides": desktopOpenApiDesktopLocalDataFullReimportUserOverridesSchema,
  "DesktopLocalDataImportUserOverrides": desktopOpenApiDesktopLocalDataImportUserOverridesSchema,
  "CsvMappingDraft": desktopOpenApiCsvMappingDraftSchema,
  "TradingCalendarConfig": desktopOpenApiTradingCalendarConfigSchema,
  "ImportFolderPath": desktopOpenApiImportFolderPathSchema,
  "DesktopLocalDataIncrementalUpdateUserOverrides": desktopOpenApiDesktopLocalDataIncrementalUpdateUserOverridesSchema,
  "ImportRelativePath": desktopOpenApiImportRelativePathSchema,
  "ImportFileName": desktopOpenApiImportFileNameSchema,
  "DesktopMarketDataAcquisitionProvider": desktopOpenApiDesktopMarketDataAcquisitionProviderSchema,
  "DesktopMarketDataAcquisitionAssetClass": desktopOpenApiDesktopMarketDataAcquisitionAssetClassSchema,
  "DesktopMarketDataAcquisitionMarketId": desktopOpenApiDesktopMarketDataAcquisitionMarketIdSchema,
  "DesktopMarketDataAcquisitionMarket": desktopOpenApiDesktopMarketDataAcquisitionMarketSchema,
  "DesktopMarketDataAcquisitionConnector": desktopOpenApiDesktopMarketDataAcquisitionConnectorSchema,
  "DesktopMarketDataAcquisitionInstrument": desktopOpenApiDesktopMarketDataAcquisitionInstrumentSchema,
  "DesktopAkshareAcquisitionJobCreateRequest": desktopOpenApiDesktopAkshareAcquisitionJobCreateRequestSchema,
  "DesktopCcxtAcquisitionJobCreateRequest": desktopOpenApiDesktopCcxtAcquisitionJobCreateRequestSchema,
  "DesktopMarketDataAcquisitionJobSummary": desktopOpenApiDesktopMarketDataAcquisitionJobSummarySchema,
  "DesktopMarketDataAcquisitionJobProgress": desktopOpenApiDesktopMarketDataAcquisitionJobProgressSchema,
  "DesktopMarketDataAcquisitionStagingSummary": desktopOpenApiDesktopMarketDataAcquisitionStagingSummarySchema,
  "DesktopMarketDataAcquisitionJobError": desktopOpenApiDesktopMarketDataAcquisitionJobErrorSchema,
  "DesktopMarketDataAcquisitionSourcePlanId": desktopOpenApiDesktopMarketDataAcquisitionSourcePlanIdSchema,
  "DesktopMarketDataAcquisitionTimeframe": desktopOpenApiDesktopMarketDataAcquisitionTimeframeSchema,
  "DesktopMarketDataAcquisitionSymbolSourceResult": desktopOpenApiDesktopMarketDataAcquisitionSymbolSourceResultSchema,
  "DesktopWorkspaceId": desktopOpenApiDesktopWorkspaceIdSchema,
  "DesktopWorkspaceReadModelTone": desktopOpenApiDesktopWorkspaceReadModelToneSchema,
  "DesktopWorkspaceCopyRef": desktopOpenApiDesktopWorkspaceCopyRefSchema,
  "DesktopWorkspaceReadModelAction": desktopOpenApiDesktopWorkspaceReadModelActionSchema,
  "DesktopWorkspaceReadModelSection": desktopOpenApiDesktopWorkspaceReadModelSectionSchema,
  "BacktestOrderSizing": desktopOpenApiBacktestOrderSizingSchema,
  "BacktestTradingSettings": desktopOpenApiBacktestTradingSettingsSchema,
  "BacktestSignalRules": desktopOpenApiBacktestSignalRulesSchema,
  "BoundedSymbol": desktopOpenApiBoundedSymbolSchema,
  "CsvMappingSingleTimestamp": desktopOpenApiCsvMappingSingleTimestampSchema,
  "CsvMappingSplitTimestamp": desktopOpenApiCsvMappingSplitTimestampSchema,
  "SecurityBookmark": desktopOpenApiSecurityBookmarkSchema,
  "TradingSessionRange": desktopOpenApiTradingSessionRangeSchema,
  "DesktopMarketDataAcquisitionProviderId": desktopOpenApiDesktopMarketDataAcquisitionProviderIdSchema,
  "DesktopMarketDataAcquisitionSourcePlan": desktopOpenApiDesktopMarketDataAcquisitionSourcePlanSchema,
  "DesktopMarketDataAcquisitionConnectorTerms": desktopOpenApiDesktopMarketDataAcquisitionConnectorTermsSchema,
  "DesktopAkshareDailyAcquisitionJobCreateRequest": desktopOpenApiDesktopAkshareDailyAcquisitionJobCreateRequestSchema,
  "DesktopAkshareMinuteAcquisitionJobCreateRequest": desktopOpenApiDesktopAkshareMinuteAcquisitionJobCreateRequestSchema,
  "DesktopAkshareIndexDailyAcquisitionJobCreateRequest": desktopOpenApiDesktopAkshareIndexDailyAcquisitionJobCreateRequestSchema,
  "DesktopMarketDataAcquisitionSourceAttempt": desktopOpenApiDesktopMarketDataAcquisitionSourceAttemptSchema,
  "BacktestOrderSizingMode": desktopOpenApiBacktestOrderSizingModeSchema,
  "BacktestDirectionSignalRule": desktopOpenApiBacktestDirectionSignalRuleSchema,
  "CsvHeaderName": desktopOpenApiCsvHeaderNameSchema,
  "DesktopMarketDataAcquisitionProject": desktopOpenApiDesktopMarketDataAcquisitionProjectSchema,
  "DesktopMarketDataAcquisitionUpstreamTerms": desktopOpenApiDesktopMarketDataAcquisitionUpstreamTermsSchema,
  "BacktestSignalRuleCondition": desktopOpenApiBacktestSignalRuleConditionSchema,
  "BacktestSignalRuleOperand": desktopOpenApiBacktestSignalRuleOperandSchema,
  "BacktestSignalRuleOperator": desktopOpenApiBacktestSignalRuleOperatorSchema,
} as const;

export const DESKTOP_OPENAPI_RUNTIME_SCHEMA_BINDINGS = {
  "desktopAkshareAcquisitionInstrumentCatalogSchema": { source: "component", component: "DesktopAkshareAcquisitionInstrumentCatalog", schema: desktopOpenApiDesktopAkshareAcquisitionInstrumentCatalogSchema },
  "desktopBacktestBatchCreateRequestSchema": { source: "component", component: "BacktestBatchCreateRequest", schema: desktopOpenApiBacktestBatchCreateRequestSchema },
  "desktopBacktestBatchListSchema": { source: "external", component: "DesktopBacktestBatchList", schema: desktopBacktestBatchListSchema },
  "desktopBacktestBatchRunRequestSchema": { source: "component", component: "BacktestBatchRunRequest", schema: desktopOpenApiBacktestBatchRunRequestSchema },
  "desktopBacktestBatchSchema": { source: "component", component: "BacktestBatch", schema: desktopOpenApiBacktestBatchSchema },
  "desktopBacktestClearResultSchema": { source: "component", component: "BacktestClearResult", schema: desktopOpenApiBacktestClearResultSchema },
  "desktopBacktestDeleteResultSchema": { source: "component", component: "BacktestDeleteResult", schema: desktopOpenApiBacktestDeleteResultSchema },
  "desktopBacktestProgressSchema": { source: "component", component: "BacktestProgress", schema: desktopOpenApiBacktestProgressSchema },
  "desktopBacktestResultDetailSchema": { source: "component", component: "BacktestResultDetail", schema: desktopOpenApiBacktestResultDetailSchema },
  "desktopBacktestResultsSchema": { source: "component", component: "BacktestResults", schema: desktopOpenApiBacktestResultsSchema },
  "desktopBarsRangeSchema": { source: "external", component: "DesktopBarsRange", schema: desktopBarsRangeSchema },
  "desktopCcxtAcquisitionMarketCatalogSchema": { source: "component", component: "DesktopCcxtAcquisitionMarketCatalog", schema: desktopOpenApiDesktopCcxtAcquisitionMarketCatalogSchema },
  "desktopCustomIndicatorCompileRequestSchema": { source: "external", component: "DesktopCustomIndicatorCompileRequest", schema: desktopCustomIndicatorCompileRequestSchema },
  "desktopCustomIndicatorCompileResultSchema": { source: "external", component: "DesktopCustomIndicatorCompileResult", schema: desktopCustomIndicatorCompileResultSchema },
  "desktopCustomIndicatorExecuteRequestSchema": { source: "external", component: "DesktopCustomIndicatorExecuteRequest", schema: desktopCustomIndicatorExecuteRequestSchema },
  "desktopCustomIndicatorExecuteResultSchema": { source: "external", component: "DesktopCustomIndicatorExecuteResult", schema: desktopCustomIndicatorExecuteResultSchema },
  "desktopCustomIndicatorProfileDeleteRequestSchema": { source: "external", component: "DesktopCustomIndicatorProfileDeleteRequest", schema: desktopCustomIndicatorProfileDeleteRequestSchema },
  "desktopCustomIndicatorProfileDeleteResultSchema": { source: "external", component: "DesktopCustomIndicatorProfileDeleteResult", schema: desktopCustomIndicatorProfileDeleteResultSchema },
  "desktopCustomIndicatorProfileListSchema": { source: "external", component: "DesktopCustomIndicatorProfileList", schema: desktopCustomIndicatorProfileListSchema },
  "desktopCustomIndicatorProfileSaveRequestSchema": { source: "external", component: "DesktopCustomIndicatorProfileSaveRequest", schema: desktopCustomIndicatorProfileSaveRequestSchema },
  "desktopCustomIndicatorProfileSaveResultSchema": { source: "external", component: "DesktopCustomIndicatorProfileSaveResult", schema: desktopCustomIndicatorProfileSaveResultSchema },
  "desktopCustomIndicatorProfilesReplaceRequestSchema": { source: "external", component: "DesktopCustomIndicatorProfilesReplaceRequest", schema: desktopCustomIndicatorProfilesReplaceRequestSchema },
  "desktopCustomIndicatorProfilesReplaceResultSchema": { source: "external", component: "DesktopCustomIndicatorProfilesReplaceResult", schema: desktopCustomIndicatorProfilesReplaceResultSchema },
  "desktopFreeReplayPoolDefaultEnvironmentRecordSchema": { source: "external", component: "DesktopFreeReplayPoolDefaultEnvironmentRecord", schema: desktopFreeReplayPoolDefaultEnvironmentRecordSchema },
  "desktopFreeReplayPoolDefaultEnvironmentSchema": { source: "external", component: "DesktopFreeReplayPoolDefaultEnvironment", schema: desktopFreeReplayPoolDefaultEnvironmentSchema },
  "desktopFreeReplayPrepReadModelRequestSchema": { source: "external", component: "DesktopFreeReplayPrepReadModelRequest", schema: desktopFreeReplayPrepReadModelRequestSchema },
  "desktopFreeReplayPrepReadModelSchema": { source: "external", component: "DesktopFreeReplayPrepReadModel", schema: desktopFreeReplayPrepReadModelSchema },
  "desktopFreeReplayStartPointOverviewRangeSchema": { source: "external", component: "DesktopFreeReplayStartPointOverviewRange", schema: desktopFreeReplayStartPointOverviewRangeSchema },
  "desktopFreeReplayStartPointOverviewRequestSchema": { source: "external", component: "DesktopFreeReplayStartPointOverviewRequest", schema: desktopFreeReplayStartPointOverviewRequestSchema },
  "desktopFreeReplayStartReadinessRequestSchema": { source: "external", component: "DesktopFreeReplayStartReadinessRequest", schema: desktopFreeReplayStartReadinessRequestSchema },
  "desktopFreeReplayStartReadinessSchema": { source: "external", component: "DesktopFreeReplayStartReadiness", schema: desktopFreeReplayStartReadinessSchema },
  "desktopInstrumentListSchema": { source: "external", component: "DesktopInstrumentList", schema: desktopInstrumentListSchema },
  "desktopLegalDocumentResponseSchema": { source: "external", component: "DesktopLegalDocumentResponse", schema: desktopLegalDocumentResponseSchema },
  "desktopLocalDataClearAllResultSchema": { source: "external", component: "DesktopLocalDataClearAllResult", schema: desktopLocalDataClearAllResultSchema },
  "desktopLocalDataDeleteSourceResultSchema": { source: "external", component: "DesktopLocalDataDeleteSourceResult", schema: desktopLocalDataDeleteSourceResultSchema },
  "desktopLocalDataFullReimportByPathRequestSchema": { source: "component", component: "DesktopLocalDataFullReimportByPathRequest", schema: desktopOpenApiDesktopLocalDataFullReimportByPathRequestSchema },
  "desktopLocalDataImportByPathRequestSchema": { source: "component", component: "DesktopLocalDataImportByPathRequest", schema: desktopOpenApiDesktopLocalDataImportByPathRequestSchema },
  "desktopLocalDataImportControlRequestSchema": { source: "external", component: "DesktopLocalDataImportControlRequest", schema: desktopLocalDataImportControlRequestSchema },
  "desktopLocalDataImportDraftValidationRequestSchema": { source: "component", component: "DesktopLocalDataImportDraftValidationRequest", schema: desktopOpenApiDesktopLocalDataImportDraftValidationRequestSchema },
  "desktopLocalDataImportDraftValidationSchema": { source: "external", component: "DesktopLocalDataImportDraftValidation", schema: desktopLocalDataImportDraftValidationSchema },
  "desktopLocalDataImportJobSchema": { source: "external", component: "DesktopLocalDataImportJob", schema: desktopLocalDataImportJobSchema },
  "desktopLocalDataImportPreviewByPathRequestSchema": { source: "component", component: "DesktopLocalDataImportPreviewByPathRequest", schema: desktopOpenApiDesktopLocalDataImportPreviewByPathRequestSchema },
  "desktopLocalDataImportPreviewDiscardRequestSchema": { source: "external", component: "DesktopLocalDataImportPreviewDiscardRequest", schema: desktopLocalDataImportPreviewDiscardRequestSchema },
  "desktopLocalDataImportPreviewDiscardResultSchema": { source: "external", component: "DesktopLocalDataImportPreviewDiscardResult", schema: desktopLocalDataImportPreviewDiscardResultSchema },
  "desktopLocalDataImportPreviewJobSchema": { source: "external", component: "DesktopLocalDataImportPreviewJob", schema: desktopLocalDataImportPreviewJobSchema },
  "desktopLocalDataIncrementalUpdateByPathRequestSchema": { source: "component", component: "DesktopLocalDataIncrementalUpdateByPathRequest", schema: desktopOpenApiDesktopLocalDataIncrementalUpdateByPathRequestSchema },
  "desktopLocalDataRemoveSymbolsResultSchema": { source: "external", component: "DesktopLocalDataRemoveSymbolsResult", schema: desktopLocalDataRemoveSymbolsResultSchema },
  "desktopLocalDataSourceDiagnosticProfileUpdateRequestSchema": { source: "external", component: "DesktopLocalDataSourceDiagnosticProfileUpdateRequest", schema: desktopLocalDataSourceDiagnosticProfileUpdateRequestSchema },
  "desktopLocalDataSourceDiagnosticsSchema": { source: "external", component: "DesktopLocalDataSourceDiagnostics", schema: desktopLocalDataSourceDiagnosticsSchema },
  "desktopLocalDataSourceListSchema": { source: "external", component: "DesktopLocalDataSourceList", schema: desktopLocalDataSourceListSchema },
  "desktopLocalDataSourceRemoveSymbolsRequestSchema": { source: "external", component: "DesktopLocalDataSourceRemoveSymbolsRequest", schema: desktopLocalDataSourceRemoveSymbolsRequestSchema },
  "desktopLocalDataSourceSummarySchema": { source: "external", component: "DesktopLocalDataSourceSummary", schema: desktopLocalDataSourceSummarySchema },
  "desktopLocalDataSourceSymbolDiagnosticsSchema": { source: "external", component: "DesktopLocalDataSourceSymbolDiagnostics", schema: desktopLocalDataSourceSymbolDiagnosticsSchema },
  "desktopLocalDataSourceTradingCalendarUpdateRequestSchema": { source: "component", component: "DesktopLocalDataSourceTradingCalendarUpdateRequest", schema: desktopOpenApiDesktopLocalDataSourceTradingCalendarUpdateRequestSchema },
  "desktopLocalDataSyncPreviewByPathRequestSchema": { source: "external", component: "DesktopLocalDataSyncPreviewByPathRequest", schema: desktopLocalDataSyncPreviewByPathRequestSchema },
  "desktopLocalDataSyncPreviewSchema": { source: "external", component: "DesktopLocalDataSyncPreview", schema: desktopLocalDataSyncPreviewSchema },
  "desktopLocalDataSyncQuickCheckByMetadataRequestSchema": { source: "component", component: "DesktopLocalDataSyncQuickCheckByMetadataRequest", schema: desktopOpenApiDesktopLocalDataSyncQuickCheckByMetadataRequestSchema },
  "desktopLocalDataSyncQuickCheckSchema": { source: "external", component: "DesktopLocalDataSyncQuickCheck", schema: desktopLocalDataSyncQuickCheckSchema },
  "desktopLocalImportMockSampleExportRequestSchema": { source: "external", component: "DesktopLocalImportMockSampleExportRequest", schema: desktopLocalImportMockSampleExportRequestSchema },
  "desktopLocalImportMockSampleExportResultSchema": { source: "external", component: "DesktopLocalImportMockSampleExportResult", schema: desktopLocalImportMockSampleExportResultSchema },
  "desktopMarketBarFrameSchema": { source: "external", component: "DesktopMarketBarFrame", schema: desktopMarketBarFrameSchema },
  "desktopMarketDataAcquisitionCatalogSchema": { source: "component", component: "DesktopMarketDataAcquisitionCatalog", schema: desktopOpenApiDesktopMarketDataAcquisitionCatalogSchema },
  "desktopMarketDataAcquisitionConnectorCatalogSchema": { source: "component", component: "DesktopMarketDataAcquisitionConnectorCatalog", schema: desktopOpenApiDesktopMarketDataAcquisitionConnectorCatalogSchema },
  "desktopMarketDataAcquisitionDiscardResultSchema": { source: "component", component: "DesktopMarketDataAcquisitionDiscardResult", schema: desktopOpenApiDesktopMarketDataAcquisitionDiscardResultSchema },
  "desktopMarketDataAcquisitionInstrumentCatalogSchema": { source: "component", component: "DesktopMarketDataAcquisitionInstrumentCatalog", schema: desktopOpenApiDesktopMarketDataAcquisitionInstrumentCatalogSchema },
  "desktopMarketDataAcquisitionJobCreateRequestSchema": { source: "component", component: "DesktopMarketDataAcquisitionJobCreateRequest", schema: desktopOpenApiDesktopMarketDataAcquisitionJobCreateRequestSchema },
  "desktopMarketDataAcquisitionJobListSchema": { source: "component", component: "DesktopMarketDataAcquisitionJobList", schema: desktopOpenApiDesktopMarketDataAcquisitionJobListSchema },
  "desktopMarketDataAcquisitionJobSchema": { source: "component", component: "DesktopMarketDataAcquisitionJob", schema: desktopOpenApiDesktopMarketDataAcquisitionJobSchema },
  "desktopMarketDataAcquisitionMarketJobCreateRequestSchema": { source: "component", component: "DesktopMarketDataAcquisitionMarketJobCreateRequest", schema: desktopOpenApiDesktopMarketDataAcquisitionMarketJobCreateRequestSchema },
  "desktopMarketDataAcquisitionMarketJobSchema": { source: "component", component: "DesktopMarketDataAcquisitionMarketJob", schema: desktopOpenApiDesktopMarketDataAcquisitionMarketJobSchema },
  "desktopPortableExportPreviewRequestSchema": { source: "external", component: "DesktopPortableExportPreviewRequest", schema: desktopPortableExportPreviewRequestSchema },
  "desktopPortableExportRequestSchema": { source: "external", component: "DesktopPortableExportRequest", schema: desktopPortableExportRequestSchema },
  "desktopPortableImportInspectRequestSchema": { source: "external", component: "DesktopPortableImportInspectRequest", schema: desktopPortableImportInspectRequestSchema },
  "desktopPortableImportRequestSchema": { source: "external", component: "DesktopPortableImportRequest", schema: desktopPortableImportRequestSchema },
  "desktopPreparedFreeReplayStartRequestSchema": { source: "external", component: "DesktopPreparedFreeReplayStartRequest", schema: desktopPreparedFreeReplayStartRequestSchema },
  "desktopPreparedFreeReplayStartResultSchema": { source: "external", component: "DesktopPreparedFreeReplayStartResult", schema: desktopPreparedFreeReplayStartResultSchema },
  "desktopResetAllDataJobSchema": { source: "external", component: "DesktopResetAllDataJob", schema: desktopResetAllDataJobSchema },
  "desktopSessionActionRequestSchema": { source: "external", component: "DesktopSessionActionRequest", schema: desktopSessionActionRequestSchema },
  "desktopSessionBootstrapRequestSchema": { source: "external", component: "DesktopSessionBootstrapRequest", schema: desktopSessionBootstrapRequestSchema },
  "desktopSessionBootstrapSchema": { source: "external", component: "DesktopSessionBootstrap", schema: desktopSessionBootstrapSchema },
  "desktopSessionCreateRequestSchema": { source: "external", component: "DesktopSessionCreateRequest", schema: desktopSessionCreateRequestSchema },
  "desktopSessionOrderQuoteRequestSchema": { source: "external", component: "DesktopSessionOrderQuoteRequest", schema: desktopSessionOrderQuoteRequestSchema },
  "desktopSessionOrderQuoteSchema": { source: "external", component: "DesktopSessionOrderQuote", schema: desktopSessionOrderQuoteSchema },
  "desktopSessionSchema": { source: "external", component: "DesktopSession", schema: desktopSessionSchema },
  "desktopSessionSnapshotSchema": { source: "external", component: "DesktopSessionSnapshot", schema: desktopSessionSnapshotSchema },
  "desktopSessionStepResultSchema": { source: "external", component: "DesktopSessionStepResult", schema: desktopSessionStepResultSchema },
  "desktopSessionTradingSettingsUpdateRequestSchema": { source: "external", component: "DesktopSessionTradingSettingsUpdateRequest", schema: desktopSessionTradingSettingsUpdateRequestSchema },
  "desktopSpecialTrainingBankDeleteResultSchema": { source: "external", component: "DesktopSpecialTrainingBankDeleteResult", schema: desktopSpecialTrainingBankDeleteResultSchema },
  "desktopSpecialTrainingBankEditorReadModelRequestSchema": { source: "external", component: "DesktopSpecialTrainingBankEditorReadModelRequest", schema: desktopSpecialTrainingBankEditorReadModelRequestSchema },
  "desktopSpecialTrainingBankEditorReadModelSchema": { source: "external", component: "DesktopSpecialTrainingBankEditorReadModel", schema: desktopSpecialTrainingBankEditorReadModelSchema },
  "desktopSpecialTrainingBankListSchema": { source: "external", component: "DesktopSpecialTrainingBankList", schema: desktopSpecialTrainingBankListSchema },
  "desktopSpecialTrainingBankSchema": { source: "external", component: "DesktopSpecialTrainingBank", schema: desktopSpecialTrainingBankSchema },
  "desktopSpecialTrainingBankScopeSummarySchema": { source: "external", component: "DesktopSpecialTrainingBankScopeSummary", schema: desktopSpecialTrainingBankScopeSummarySchema },
  "desktopSpecialTrainingChallengeActionRequestSchema": { source: "external", component: "DesktopSpecialTrainingChallengeActionRequest", schema: desktopSpecialTrainingChallengeActionRequestSchema },
  "desktopSpecialTrainingChallengeActivityRequestSchema": { source: "external", component: "DesktopSpecialTrainingChallengeActivityRequest", schema: desktopSpecialTrainingChallengeActivityRequestSchema },
  "desktopSpecialTrainingChallengeActivityResultSchema": { source: "external", component: "DesktopSpecialTrainingChallengeActivityResult", schema: desktopSpecialTrainingChallengeActivityResultSchema },
  "desktopSpecialTrainingChallengeCommandResultSchema": { source: "external", component: "DesktopSpecialTrainingChallengeCommandResult", schema: desktopSpecialTrainingChallengeCommandResultSchema },
  "desktopSpecialTrainingChallengeDiscardResultSchema": { source: "external", component: "DesktopSpecialTrainingChallengeDiscardResult", schema: desktopSpecialTrainingChallengeDiscardResultSchema },
  "desktopSpecialTrainingChallengeProgressSchema": { source: "external", component: "DesktopSpecialTrainingChallengeProgress", schema: desktopSpecialTrainingChallengeProgressSchema },
  "desktopSpecialTrainingChallengeRuntimeSchema": { source: "external", component: "DesktopSpecialTrainingChallengeRuntime", schema: desktopSpecialTrainingChallengeRuntimeSchema },
  "desktopSpecialTrainingChallengeSchema": { source: "external", component: "DesktopSpecialTrainingChallenge", schema: desktopSpecialTrainingChallengeSchema },
  "desktopSpecialTrainingChallengeStartRequestSchema": { source: "external", component: "DesktopSpecialTrainingChallengeStartRequest", schema: desktopSpecialTrainingChallengeStartRequestSchema },
  "desktopSpecialTrainingDecisionRequestSchema": { source: "external", component: "DesktopSpecialTrainingDecisionRequest", schema: desktopSpecialTrainingDecisionRequestSchema },
  "desktopSpecialTrainingDurationEstimateSchema": { source: "external", component: "DesktopSpecialTrainingDurationEstimate", schema: desktopSpecialTrainingDurationEstimateSchema },
  "desktopSpecialTrainingHistoryClearResultSchema": { source: "external", component: "DesktopSpecialTrainingHistoryClearResult", schema: desktopSpecialTrainingHistoryClearResultSchema },
  "desktopSpecialTrainingHistoryQuestionDetailSchema": { source: "external", component: "DesktopSpecialTrainingHistoryQuestionDetail", schema: desktopSpecialTrainingHistoryQuestionDetailSchema },
  "desktopSpecialTrainingHistorySessionDetailSchema": { source: "external", component: "DesktopSpecialTrainingHistorySessionDetail", schema: desktopSpecialTrainingHistorySessionDetailSchema },
  "desktopSpecialTrainingHistorySessionListSchema": { source: "external", component: "DesktopSpecialTrainingHistorySessionList", schema: desktopSpecialTrainingHistorySessionListSchema },
  "desktopSpecialTrainingOrderQuoteRequestSchema": { source: "external", component: "DesktopSpecialTrainingOrderQuoteRequest", schema: desktopSpecialTrainingOrderQuoteRequestSchema },
  "desktopSpecialTrainingOrderQuoteSchema": { source: "external", component: "DesktopSpecialTrainingOrderQuote", schema: desktopSpecialTrainingOrderQuoteSchema },
  "desktopSpecialTrainingQuestionBankDraftPreviewRequestSchema": { source: "external", component: "DesktopSpecialTrainingQuestionBankDraftPreviewRequest", schema: desktopSpecialTrainingQuestionBankDraftPreviewRequestSchema },
  "desktopSpecialTrainingQuestionBankPreviewRequestSchema": { source: "external", component: "DesktopSpecialTrainingQuestionBankPreviewRequest", schema: desktopSpecialTrainingQuestionBankPreviewRequestSchema },
  "desktopSpecialTrainingQuestionBankResetRequestSchema": { source: "external", component: "DesktopSpecialTrainingQuestionBankResetRequest", schema: desktopSpecialTrainingQuestionBankResetRequestSchema },
  "desktopSpecialTrainingQuestionBankSummarySchema": { source: "external", component: "DesktopSpecialTrainingQuestionBankSummary", schema: desktopSpecialTrainingQuestionBankSummarySchema },
  "desktopSpecialTrainingQuestionSettleRequestSchema": { source: "external", component: "DesktopSpecialTrainingQuestionSettleRequest", schema: desktopSpecialTrainingQuestionSettleRequestSchema },
  "desktopSpecialTrainingSettlementSchema": { source: "external", component: "DesktopSpecialTrainingSettlement", schema: desktopSpecialTrainingSettlementSchema },
  "desktopSpecialTrainingStatsPayloadSchema": { source: "external", component: "DesktopSpecialTrainingStatsPayload", schema: desktopSpecialTrainingStatsPayloadSchema },
  "desktopSpecialTrainingStatsProjectDetailSchema": { source: "external", component: "DesktopSpecialTrainingStatsProjectDetail", schema: desktopSpecialTrainingStatsProjectDetailSchema },
  "desktopSpecialTrainingStatsSummarySchema": { source: "external", component: "DesktopSpecialTrainingStatsSummary", schema: desktopSpecialTrainingStatsSummarySchema },
  "desktopStartupLocalDataReinitializeRequestSchema": { source: "external", component: "DesktopStartupLocalDataReinitializeRequest", schema: desktopStartupLocalDataReinitializeRequestSchema },
  "desktopStartupLocalDataReinitializeResultSchema": { source: "external", component: "DesktopStartupLocalDataReinitializeResult", schema: desktopStartupLocalDataReinitializeResultSchema },
  "desktopSystemHealthSchema": { source: "external", component: "DesktopSystemHealth", schema: desktopSystemHealthSchema },
  "desktopSystemStartupStatusSchema": { source: "external", component: "DesktopSystemStartupStatus", schema: desktopSystemStartupStatusSchema },
  "desktopTrainingStatsSummarySchema": { source: "external", component: "DesktopTrainingStatsSummary", schema: desktopTrainingStatsSummarySchema },
  "desktopWorkspaceReadModelSchema": { source: "component", component: "DesktopWorkspaceReadModel", schema: desktopOpenApiDesktopWorkspaceReadModelSchema },
} as const;
