// SPDX-License-Identifier: GPL-3.0-only

import type { ApiRequestOptions } from "@/api/requesterTypes";
import type {
  TradingCalendarConfig,
  TradingCalendarSuggestion,
} from "@zinuto/shared/tradingCalendar";

export type CsvTimestampMode = "SINGLE" | "SPLIT";

export type CsvFieldMapping = {
  timestampMode: CsvTimestampMode;
  date: string;
  time: string;
  open: string;
  high: string;
  low: string;
  close: string;
  volume: string;
};

export type ApiTradingAssetClass = "STOCK" | "FUTURES" | "FOREX" | "CRYPTO";
export type ApiDiagnosticProfileOrigin = "SYSTEM" | "INFERRED" | "USER";
export type ApiDiagnosticStatus = "READY" | "BUILDING" | "FAILED";
export type ApiDiagnosticCategory =
  | "TIME_INTEGRITY"
  | "EXTREME_ANOMALY";
export type ApiDiagnosticSeverity = "INFO" | "WARNING" | "CRITICAL";
export type ApiDiagnosticCode =
  | "INVALID_OHLC"
  | "DUPLICATE_TIMESTAMP"
  | "TIME_ORDER_BREAK"
  | "DATA_GAP"
  | "OUT_OF_SESSION_BAR"
  | "TIMEFRAME_MISALIGNED_BAR"
  | "EXTREME_PRICE_SPIKE";

export type ApiTradingSessionRange = TradingCalendarConfig["sessions"][number];
export type ApiTradingCalendarConfig = TradingCalendarConfig;
export type ApiTradingCalendarSuggestion = TradingCalendarSuggestion;

export type ApiLocalDataSourceDiagnosticProfile = {
  assetClass: ApiTradingAssetClass;
  marketPresetId: string;
  profileOrigin: ApiDiagnosticProfileOrigin;
};

export type ApiLocalDataSourceDiagnosticIssue = {
  id: string;
  instrumentId: string;
  symbol: string;
  category: ApiDiagnosticCategory;
  code: ApiDiagnosticCode;
  severity: ApiDiagnosticSeverity;
  dateLabel: string;
  focusBarIndex: number;
  focusStartTs: string | null;
  focusEndTs: string | null;
  missingBars: number;
  ratio: number;
  volumeRatio: number;
  closeChangeRatio: number;
  amplitudeRatio: number;
  zScore: number;
  multiple: number;
  count: number;
};

export type ApiLocalDataSourceDiagnosticSummary = {
  totalIssues: number;
  criticalIssues: number;
  warningIssues: number;
  infoIssues: number;
  byCategory: Record<ApiDiagnosticCategory, number>;
};

export type ImportRuleConfidence = "HIGH" | "MEDIUM" | "LOW";
export type ImportRulePriceFamily = "RAW" | "ADJUSTED" | "GENERIC";
export type ImportRuleFieldKey =
  | "date"
  | "time"
  | "open"
  | "high"
  | "low"
  | "close"
  | "volume";

export type ApiLocalDataImportDraftValidationReasonCode =
  | "READY"
  | "CSV_MAPPING_REQUIRED"
  | "CSV_MAPPING_HEADER_MISSING"
  | "CSV_MAPPING_DUPLICATED"
  | "LOCAL_DATA_IMPORT_NO_CONFIRMABLE_PLAN"
  | "LOCAL_DATA_IMPORT_PREVIEW_EXPIRED"
  | "LOCAL_DATA_TRADING_CALENDAR_INVALID"
  | "LOCAL_DATA_IMPORT_TARGET_SOURCE_INVALID"
  | "LOCAL_DATA_IMPORT_REPAIR_WARNINGS"
  | "LOCAL_DATA_IMPORT_TIME_ZONE_CONFIRMATION_REQUIRED";

export type ApiLocalDataImportBlockingIssueKind =
  | "none"
  | "field-mapping"
  | "targeting"
  | "trading-calendar"
  | "repair-warnings"
  | "time-zone";

export type ApiLocalDataImportPlanning = {
  targetSourceOptions: Array<{
    sourceId: string;
    sourceName: string;
    baseTimeframe: "1m" | "5m" | "1h" | "1d";
    importScopeStrategy: "FLAT" | "WITH_PARENT" | null;
    importScopeTopLevelSubfolder: string;
    timeZone: string;
    timeZoneOrigin: "PRESET_DEFAULT" | "INFERRED_DEFAULT" | "USER_SELECTED";
    tradingCalendar: ApiTradingCalendarConfig;
  }>;
  recommendedTimeZone: string;
  recommendedTimeZoneReason:
    | "PRESET_DEFAULT"
    | "RULE_INFERRED"
    | "TIMESTAMP_INFERRED"
    | "EXISTING_SOURCE"
    | "SYSTEM_FALLBACK";
  recommendedTradingCalendar: ApiTradingCalendarConfig;
  scopeStrategy: "FLAT" | "WITH_PARENT";
  availableScopeStrategies: Array<"FLAT" | "WITH_PARENT">;
  planRows: Array<{
    id: string;
    previewPlanId: string;
    strategy: "FLAT" | "WITH_PARENT";
    topLevelSubfolder: string;
    poolName: string;
    autoGeneratedPoolName: string;
    sourceId: string;
    targetSourceId: string;
    targetSourceOptions: Array<{
      sourceId: string;
      sourceName: string;
    }>;
    hasExistingTargetOptions: boolean;
    symbolCount: number;
    fileCount: number;
    baseTimeframe: "1m" | "5m" | "1h" | "1d";
    effectiveTimeZone: string;
    effectiveTimeZoneOrigin: "PRESET_DEFAULT" | "INFERRED_DEFAULT" | "USER_SELECTED";
    effectiveTimeZoneSource:
      | "NEW_SOURCE_PENDING_IMPORT"
      | "EXISTING_SOURCE"
      | "FULL_REIMPORT";
    targetSourceTimeZone: string | null;
    targetSourceTimeZoneOrigin:
      | "PRESET_DEFAULT"
      | "INFERRED_DEFAULT"
      | "USER_SELECTED"
      | null;
    tradingCalendar: ApiTradingCalendarConfig;
    targetSourceTradingCalendar: ApiTradingCalendarConfig | null;
    willUpdateExistingSourceTimeZone: boolean;
    willUpdateExistingSourceTradingCalendar: boolean;
  }>;
};

export type ApiLocalDataImportDraftValidation = {
  mapping: {
    valid: boolean;
    reasonCode: ApiLocalDataImportDraftValidationReasonCode;
    issueCount: number;
    issues: Array<{
      field: ImportRuleFieldKey;
      reasonCode: ApiLocalDataImportDraftValidationReasonCode;
      header: string;
    }>;
  };
  tradingCalendar: {
    valid: boolean;
    reasonCode: ApiLocalDataImportDraftValidationReasonCode;
    issueCount: number;
    issues: Array<{
      previewPlanId: string;
      baseTimeframe: "1m" | "5m" | "1h" | "1d" | null;
      reasonCode: ApiLocalDataImportDraftValidationReasonCode;
    }>;
  };
  targeting: {
    valid: boolean;
    reasonCode: ApiLocalDataImportDraftValidationReasonCode;
    issueCount: number;
    issues: Array<{
      previewPlanId: string;
      targetSourceId: string;
      reasonCode: ApiLocalDataImportDraftValidationReasonCode;
    }>;
  };
  repair: {
    valid: boolean;
    reasonCode: ApiLocalDataImportDraftValidationReasonCode;
    warningCount: number;
  };
  timeZone: {
    valid: boolean;
    reasonCode: ApiLocalDataImportDraftValidationReasonCode;
    confirmationRequired: boolean;
  };
  confirm: {
    enabled: boolean;
    reasonCode: ApiLocalDataImportDraftValidationReasonCode;
  };
  blockingIssue: {
    kind: ApiLocalDataImportBlockingIssueKind;
    reasonCode: ApiLocalDataImportDraftValidationReasonCode;
  };
  planning: ApiLocalDataImportPlanning;
  validatedAt: string;
};

export type ApiLocalDataSourceSummary = {
  id: string;
  samplePoolId: string;
  name: string;
  sourceFolder: string;
  sourceFolderBookmarkId: string;
  importScopeStrategy: "FLAT" | "WITH_PARENT" | null;
  importScopeTopLevelSubfolder: string;
  timeZone: string;
  timeZoneOrigin:
    | "PRESET_DEFAULT"
    | "INFERRED_DEFAULT"
    | "USER_SELECTED";
  baseTimeframe: "1m" | "5m" | "1h" | "1d";
  tradingCalendar: ApiTradingCalendarConfig;
  diagnosticProfile: ApiLocalDataSourceDiagnosticProfile;
  fieldMapping: CsvFieldMapping;
  symbols: string[];
  instruments: Array<{
    samplePoolId: string;
    instrumentId: string;
    symbol: string;
    displayLabel: string;
    baseTimeframe: "1m" | "5m" | "1h" | "1d";
    sourceTimeframe: "1m" | "5m" | "1h" | "1d";
    scopeKind: "SYSTEM" | "LOCAL";
    sourceId: string | null;
    sourceName: string | null;
    barCount: number;
    timeStartTs: string | null;
    timeEndTs: string | null;
  }>;
  status: "IMPORTING" | "READY" | "FAILED";
  symbolCount: number;
  barCount: number;
  symbolStats: Array<{
    instrumentId: string;
    symbol: string;
    displayLabel: string;
    barCount: number;
    timeStartTs: string | null;
    timeEndTs: string | null;
  }>;
  timeStartTs: string | null;
  timeEndTs: string | null;
  totalFiles: number;
  importedFiles: number;
  failedFiles: number;
  requiresSourceFolderRebind: boolean;
  sourceLocked: boolean;
  unlockedSymbols: string[];
  lockedSymbols: string[];
  lockedSymbolCount: number;
  lockReason: string | null;
  storageBytes: number;
  createdAt: string;
  updatedAt: string;
  lastJob: {
    id: string;
    status: "QUEUED" | "RUNNING" | "SUCCESS" | "PARTIAL_SUCCESS" | "FAILED" | "CANCELED";
    stage: "QUEUED" | "SCANNING" | "IMPORTING" | "FINALIZING" | "DONE";
    progressPercent: number;
    compactProgressPercent: number;
    compactBeforeBytes: number;
    compactAfterBytes: number;
    compactReclaimedBytes: number;
    doneFiles: number;
    totalFiles: number;
    errorFiles: number;
    startedAt: string | null;
    finishedAt: string | null;
  } | null;
};

export type ApiLocalDataImportSymbolLimit = {
  limitApplied: boolean;
  maxSymbols: number | null;
  selectedSymbols: string[];
  skippedSymbols: string[];
  skippedSymbolCount: number;
  reason: null;
};

export type ApiLocalDataImportJob = {
  id: string;
  sourceId: string;
  sourceName: string;
  timeZone: string;
  baseTimeframe: "1m" | "5m" | "1h" | "1d";
  jobMode: "FULL_IMPORT" | "INCREMENTAL_UPDATE";
  status: "QUEUED" | "RUNNING" | "SUCCESS" | "PARTIAL_SUCCESS" | "FAILED" | "CANCELED";
  stage: "QUEUED" | "SCANNING" | "IMPORTING" | "FINALIZING" | "DONE";
  progressPercent: number;
  compactProgressPercent: number;
  compactBeforeBytes: number;
  compactAfterBytes: number;
  compactReclaimedBytes: number;
  totalFiles: number;
  doneFiles: number;
  totalRows: number;
  importedRows: number;
  skippedRows: number;
  errorFiles: number;
  currentFileName: string | null;
  errorMessage: string | null;
  errorCode: string | null;
  cause: {
    code: string;
    stage: string;
  } | null;
  details: Record<string, string | number | boolean | null> | null;
  failureSummary: {
    totalFailedFiles: number;
    primaryCode: string | null;
    items: Array<{
      code: string;
      stage: string;
      fileName: string | null;
      count: number;
    }>;
  } | null;
  createdAt: string;
  startedAt: string | null;
  finishedAt: string | null;
  isPaused: boolean;
  cancelRequested: boolean;
  outcomeSummary: {
    noChanges: boolean;
    addedSymbols: string[];
    updatedSymbols: string[];
    unchangedFiles: number;
    prependedRows: number;
    appendedRows: number;
    overlapRowsIgnored: number;
    internalRangeRowsIgnored: number;
    conflictRowsIgnored: number;
    qualityWarnings: {
      filesWithSkippedRows: number;
      invalidRequiredRowsSkipped: number;
      invalidOhlcRowsSkipped: number;
      duplicateConflictRowsSkipped: number;
      duplicateIdenticalRowsDeduped: number;
    };
  } | null;
  outcomeInsight: {
    prependedRows: number;
    appendedRows: number;
    importedRows: number;
    overlapRowsIgnored: number;
    internalRangeRowsIgnored: number;
    conflictRowsIgnored: number;
    ignoredRows: number;
    hasIgnoredRows: boolean;
    filesWithSkippedRows: number;
    qualityRowsSkipped: number;
    invalidRequiredRowsSkipped: number;
    invalidOhlcRowsSkipped: number;
    duplicateConflictRowsSkipped: number;
    duplicateIdenticalRowsDeduped: number;
    hasQualityWarnings: boolean;
    isIgnoredOnly: boolean;
  } | null;
  phaseFacts: {
    cardPhase: "IMPORTING" | "FINALIZING" | "FAILED" | "DONE";
    active: boolean;
    terminal: boolean;
    done: boolean;
    failed: boolean;
    fileProgressPercent: number;
    importProgressPercent: number;
    compactProgressDisplayPercent: number;
    compactAfterDisplayBytes: number;
    compactReclaimedDisplayBytes: number;
    shouldShowCompactProgress: boolean;
    progressTone: "syncing" | "danger" | "ready";
    pollDelayMs: number;
  };
  symbolLimit: ApiLocalDataImportSymbolLimit;
  failedFiles: Array<{
    id: string;
    fileName: string;
    symbol: string;
    rowsTotal: number;
    rowsImported: number;
    rowsSkipped: number;
    errorMessage: string;
    errorCode: string;
    cause: {
      code: string;
      stage: string;
    };
    details: Record<string, string | number | boolean | null>;
    diagnostics: Array<{
      code: string;
      severity: "INFO" | "WARNING" | "ERROR";
      stage: string;
      fileName: string | null;
      relativePath: string | null;
      format: string | null;
      field: string | null;
      rowNumber: number | null;
      rawValue: string | null;
      expected: string | null;
      actual: string | number | boolean | null;
      samples: Array<Record<string, string | number | boolean | null>>;
    }>;
    updatedAt: string;
  }>;
};

export type ApiLocalDataSourceSymbolDiagnostics = {
  symbol: string;
  baseTimeframe: "1m" | "5m" | "1h" | "1d";
  diagnosticRulesVersion: string;
  status: ApiDiagnosticStatus;
  generatedAt: string | null;
  profile: ApiLocalDataSourceDiagnosticProfile;
  health: {
    score: number;
    severity: ApiDiagnosticSeverity;
    affectedSymbols: number;
  };
  totalBars: number;
  summary: ApiLocalDataSourceDiagnosticSummary;
  items: ApiLocalDataSourceDiagnosticIssue[];
};

export type ApiLocalDataSourceDiagnostics = {
  sourceId: string;
  baseTimeframe: "1m" | "5m" | "1h" | "1d";
  diagnosticRulesVersion: string;
  status: ApiDiagnosticStatus;
  generatedAt: string | null;
  profile: ApiLocalDataSourceDiagnosticProfile;
  health: {
    score: number;
    severity: ApiDiagnosticSeverity;
    affectedSymbols: number;
  };
  totalSymbols: number;
  scannedSymbols: number;
  affectedSymbols: number;
  totalIssues: number;
  summary: ApiLocalDataSourceDiagnosticSummary;
  symbols: Array<{
    instrumentId: string;
    symbol: string;
    totalBars: number;
    issueCount: number;
    criticalIssues: number;
    warningIssues: number;
    infoIssues: number;
    healthScore: number;
    volatilityPercent: number;
    highPrice: number;
    lowPrice: number;
    timeStartTs: string | null;
    timeEndTs: string | null;
  }>;
  items: ApiLocalDataSourceDiagnosticIssue[];
  nextCursor: string | null;
};

export type ApiLocalDataSourceDiagnosticsRequestOptions = ApiRequestOptions & {
  limit?: number;
  cursor?: string | null;
  category?: ApiDiagnosticCategory | null;
  severity?: ApiDiagnosticSeverity | null;
};

export type ApiLocalDataImportFolderPreview = {
  previewToken: string;
  folderName: string;
  folderPath: string;
  marketDataAcquisitionMetadata: {
    schemaVersion: 1;
    connectorId: 'akshare' | 'ccxt';
    adjustment: 'none' | 'qfq' | 'hfq' | null;
    sourceSymbols: string[];
    importSymbols: string[];
  } | null;
  suggestedFreeReplayEnvironment: {
    assetClass: "STOCK" | "FUTURES" | "FOREX" | "CRYPTO";
    marketPresetId: string;
  } | null;
  suggestedTimeZone: string;
  suggestedTimeZoneReason:
    | "PRESET_DEFAULT"
    | "RULE_INFERRED"
    | "TIMESTAMP_INFERRED"
    | "EXISTING_SOURCE"
    | "SYSTEM_FALLBACK";
  timeZoneSuggestion: {
    timeZone: string;
    reason:
      | "PRESET_DEFAULT"
      | "RULE_INFERRED"
      | "TIMESTAMP_INFERRED"
      | "EXISTING_SOURCE"
      | "SYSTEM_FALLBACK";
    confidence: ImportRuleConfidence;
    reasons: Array<{
      code: string;
      timeZone: string;
      score: number;
    }>;
    samples: Array<{
      raw: string;
      parsedAt: string;
    }>;
  };
  tradingCalendarSuggestion: ApiTradingCalendarSuggestion;
  draftValidation: ApiLocalDataImportDraftValidation;
  headers: string[];
  defaultMapping: CsvFieldMapping;
  mappingProfile: {
    canonicalSchemaKey: string;
    priceFamily: ImportRulePriceFamily;
    confidence: ImportRuleConfidence;
    score: number;
    conflicts: string[];
  };
  fieldDiagnostics: Array<{
    field: ImportRuleFieldKey;
    status: "MATCHED" | "MISSING" | "CONFLICT";
    selectedHeader: string;
    confidence: ImportRuleConfidence;
    reason: string;
    candidates: Array<{
      header: string;
      score: number;
      reason: string;
      family: ImportRulePriceFamily;
    }>;
  }>;
  repairSummary: {
    applied: string[];
    warnings: string[];
    sample: {
      checkedRows: number;
      parseableTimestampRows: number;
      validOhlcRows: number;
      duplicateTimestampRows: number;
      conflictingDuplicateTimestampRows: number;
    };
  };
  schemaDiagnostics: {
    canonicalSchemaKey: string;
    validSchemaCount: number;
    inconsistentFiles: Array<{
      relativePath: string;
      reason: string;
      canonicalSchemaKey: string;
      conflicts: string[];
    }>;
  };
  detectedTimeframe: "1m" | "5m" | "1h" | "1d";
  detectedTimeframes: Array<"1m" | "5m" | "1h" | "1d">;
  validSymbolCount: number;
  totalFiles: number;
  validFiles: number;
  invalidFiles: number;
  invalidFileSamples: Array<{
    relativePath: string;
    reason: string;
  }>;
  planSummaries: Array<{
    id: string;
    strategy: "FLAT" | "WITH_PARENT";
    baseTimeframe: "1m" | "5m" | "1h" | "1d";
    topLevelSubfolder: string;
    symbolCount: number;
    fileCount: number;
  }>;
  confirmableImportPlans: Array<{
    id: string;
    previewPlanId: string;
    strategy: "FLAT" | "WITH_PARENT";
    baseTimeframe: "1m" | "5m" | "1h" | "1d";
    topLevelSubfolder: string;
    defaultPoolName: string;
    symbolCount: number;
    fileCount: number;
  }>;
  sampledFileNames: string[];
  skippedNestedCount: number;
};

export type ApiLocalDataImportPreviewJobStage =
  | "QUEUED"
  | "SCANNING_FILES"
  | "READING_HEADERS"
  | "DETECTING_TIMEFRAMES"
  | "BUILDING_PLAN"
  | "CHECKING_QUALITY"
  | "DONE";

export type ApiLocalDataImportPreviewJob = {
  id: string;
  status: "QUEUED" | "RUNNING" | "SUCCESS" | "FAILED";
  stage: ApiLocalDataImportPreviewJobStage;
  progressPercent: number;
  processedFiles: number;
  totalFiles: number;
  result: ApiLocalDataImportFolderPreview | null;
  errorMessage: string | null;
  errorCode: string | null;
  errorArgs: Record<string, unknown> | null;
  createdAt: string;
  startedAt: string | null;
  finishedAt: string | null;
};

export const BASE_TIMEFRAME_SORT_ORDER: ReadonlyArray<
  "1m" | "5m" | "1h" | "1d"
> = ["1m", "5m", "1h", "1d"];

export type ApiLocalDataSyncPreview = {
  sourceId: string;
  sourceName: string;
  sourceFolder: string;
  sourceFolderUsageMode: "BOUND_SOURCE" | "ONE_OFF";
  baseTimeframe: "1m" | "5m" | "1h" | "1d";
  timeZone: string;
  timeZoneOrigin:
    | "PRESET_DEFAULT"
    | "PRESET_DEFAULT"
    | "INFERRED_DEFAULT"
    | "USER_SELECTED";
  importScopeStrategy: "FLAT" | "WITH_PARENT" | null;
  importScopeTopLevelSubfolder: string;
  matchedPreviewPlanId: string | null;
  scopeCandidates: Array<{
    previewPlanId: string;
    strategy: "FLAT" | "WITH_PARENT";
    topLevelSubfolder: string;
    symbolCount: number;
    fileCount: number;
  }>;
  requiresScopeConfirmation: boolean;
  changeSummary: {
    changedFiles: number;
    unchangedFiles: number;
    addedSymbols: string[];
    updatedSymbols: string[];
    missingSymbolsRetained: string[];
    symbolLimit: ApiLocalDataImportSymbolLimit;
  };
};

export type ApiLocalDataSyncQuickCheck = {
  sourceId: string;
  sourceName: string;
  sourceFolder: string;
  baseTimeframe: "1m" | "5m" | "1h" | "1d";
  status: "NO_CHANGES" | "POTENTIAL_CHANGES" | "UNABLE_TO_CHECK";
  reasonCode: string;
  checkedAt: string;
  estimatedChangedFiles: number;
  estimatedChangedSymbols: number;
  detectedFiles: number;
  trackedFiles: number;
  changedSymbols: string[];
  changedRelativePaths: string[];
  fingerprintRequiredRelativePaths: string[];
  missingSymbolsRetained: string[];
  snapshotSymbols: string[];
  invalidFiles: number;
  symbolLimit: ApiLocalDataImportSymbolLimit;
};
