// SPDX-License-Identifier: GPL-3.0-only

// Generated by tools/market-data/generate-runtime-version-manifest.mjs.
// Do not edit by hand; the audited connector registry is authoritative.
export const MARKET_DATA_CONNECTOR_VERSIONS = {
  "akshare": "1.18.91",
  "ccxt": "4.5.73",
  "financedatareader": "0.9.202"
} as const;
export const AKSHARE_VERSION = MARKET_DATA_CONNECTOR_VERSIONS.akshare;
export const CCXT_VERSION = MARKET_DATA_CONNECTOR_VERSIONS.ccxt;
export const FINANCE_DATA_READER_VERSION = MARKET_DATA_CONNECTOR_VERSIONS.financedatareader;
