// SPDX-License-Identifier: GPL-3.0-only

import type { PendingCsvFolderImport } from "@/domains/data-import/dataSourceTypes";
import type { ApiLocalDataImportPlanning } from "@/api";
import { useEffect, useMemo, type Dispatch, type SetStateAction } from 'react';
import {
  type PendingCsvImportTargetSourceOption,
  type PendingCsvPlanOverride,
} from '@/app-shell/appCsvImportContracts';
import type { CsvImportPlanConfigRow } from '@/app-shell/AppCsvMappingModal';
import type { BaseTimeframe } from '@/domains/chart/chartPeriods';
import { normalizeTimeZone, resolveSystemTimeZone } from '@zinuto/shared/timezone';

type UsePendingCsvImportPlanningArgs = {
  pendingCsvFolderImport: PendingCsvFolderImport | null;
  pendingCsvImportTimeZone: string;
  pendingCsvImportTimeZoneMode: 'AUTO' | 'MANUAL';
  setPendingCsvImportTimeZone: Dispatch<SetStateAction<string>>;
  setPendingCsvImportTimeZoneMode: Dispatch<SetStateAction<'AUTO' | 'MANUAL'>>;
  setPendingCsvPlanOverrides: Dispatch<SetStateAction<Record<string, PendingCsvPlanOverride>>>;
};

export const usePendingCsvImportPlanning = ({
  pendingCsvFolderImport,
  pendingCsvImportTimeZone,
  pendingCsvImportTimeZoneMode,
  setPendingCsvImportTimeZone,
  setPendingCsvImportTimeZoneMode,
  setPendingCsvPlanOverrides
}: UsePendingCsvImportPlanningArgs): {
  pendingCsvImportTargetSourceOptions: PendingCsvImportTargetSourceOption[];
  pendingCsvRecommendedTimeZone: string;
  pendingCsvRecommendedTimeZoneReason:
    | 'PRESET_DEFAULT'
    | 'RULE_INFERRED'
    | 'TIMESTAMP_INFERRED'
    | 'EXISTING_SOURCE'
    | 'SYSTEM_FALLBACK';
  pendingCsvPlanConfigRows: CsvImportPlanConfigRow[];
} => {
  const planning: ApiLocalDataImportPlanning | null =
    pendingCsvFolderImport?.importPlanning ??
    pendingCsvFolderImport?.draftValidation?.planning ??
    null;
  const pendingCsvRecommendedTimeZone = normalizeTimeZone(
    planning?.recommendedTimeZone || resolveSystemTimeZone(),
  );
  const pendingCsvRecommendedTimeZoneReason =
    planning?.recommendedTimeZoneReason ?? 'SYSTEM_FALLBACK';

  useEffect(() => {
    if (!pendingCsvFolderImport) {
      const systemTimeZone = resolveSystemTimeZone();
      if (pendingCsvImportTimeZone !== systemTimeZone || pendingCsvImportTimeZoneMode !== 'AUTO') {
        setPendingCsvImportTimeZone(systemTimeZone);
        setPendingCsvImportTimeZoneMode('AUTO');
      }
      setPendingCsvPlanOverrides((current) => (Object.keys(current).length ? {} : current));
      return;
    }
    if (
      pendingCsvImportTimeZoneMode === 'AUTO' &&
      pendingCsvImportTimeZone !== pendingCsvRecommendedTimeZone
    ) {
      setPendingCsvImportTimeZone(pendingCsvRecommendedTimeZone);
    }
  }, [
    pendingCsvFolderImport,
    pendingCsvImportTimeZone,
    pendingCsvImportTimeZoneMode,
    pendingCsvRecommendedTimeZone,
    setPendingCsvImportTimeZone,
    setPendingCsvImportTimeZoneMode,
    setPendingCsvPlanOverrides
  ]);

  const pendingCsvImportTargetSourceOptions = useMemo<PendingCsvImportTargetSourceOption[]>(
    () =>
      (planning?.targetSourceOptions ?? []).map((option) => ({
        sourceId: option.sourceId,
        sourceName: option.sourceName,
        baseTimeframe: option.baseTimeframe as BaseTimeframe,
        importScopeStrategy: option.importScopeStrategy,
        importScopeTopLevelSubfolder: option.importScopeTopLevelSubfolder,
        timeZone: option.timeZone,
        timeZoneOrigin: option.timeZoneOrigin,
        tradingCalendar: option.tradingCalendar,
      })),
    [planning?.targetSourceOptions],
  );

  const pendingCsvPlanConfigRows = useMemo<CsvImportPlanConfigRow[]>(
    () =>
      (planning?.planRows ?? []).map((row) => ({
        id: row.id,
        previewPlanId: row.previewPlanId,
        strategy: row.strategy,
        topLevelSubfolder: row.topLevelSubfolder,
        poolName: row.poolName,
        autoGeneratedPoolName: row.autoGeneratedPoolName,
        sourceId: row.sourceId,
        targetSourceId: row.targetSourceId,
        targetSourceOptions: row.targetSourceOptions,
        hasExistingTargetOptions: row.hasExistingTargetOptions,
        symbolCount: row.symbolCount,
        fileCount: row.fileCount,
        baseTimeframe: row.baseTimeframe as BaseTimeframe,
        effectiveTimeZone: row.effectiveTimeZone,
        effectiveTimeZoneOrigin: row.effectiveTimeZoneOrigin,
        effectiveTimeZoneSource: row.effectiveTimeZoneSource,
        targetSourceTimeZone: row.targetSourceTimeZone,
        targetSourceTimeZoneOrigin: row.targetSourceTimeZoneOrigin,
        tradingCalendar: row.tradingCalendar,
        targetSourceTradingCalendar: row.targetSourceTradingCalendar,
        willUpdateExistingSourceTimeZone: row.willUpdateExistingSourceTimeZone,
        willUpdateExistingSourceTradingCalendar: row.willUpdateExistingSourceTradingCalendar,
      })),
    [planning?.planRows],
  );

  return {
    pendingCsvImportTargetSourceOptions,
    pendingCsvRecommendedTimeZone,
    pendingCsvRecommendedTimeZoneReason,
    pendingCsvPlanConfigRows
  };
};
