// SPDX-License-Identifier: GPL-3.0-only
/* eslint-disable */
// This file is generated by ./tools/docs/generate-shared-i18n-runtime.mjs.

import { I18N_CATALOG_EN } from "./i18n.generated.en.js";
import { I18N_CATALOG_ZH_CN } from "./i18n.generated.zh-CN.js";
import { I18N_CATALOG_JA } from "./i18n.generated.ja.js";
import { I18N_CATALOG_KO } from "./i18n.generated.ko.js";
import { I18N_CATALOG_ES } from "./i18n.generated.es.js";

export {
  I18N_CATALOG_NAMESPACES,
  I18N_MESSAGE_IDS,
  I18N_SOURCE_LOCALES,
} from "./i18n.metadata.generated.js";

export const I18N_CATALOGS = {
  "en": I18N_CATALOG_EN,
  "zh-CN": I18N_CATALOG_ZH_CN,
  "ja": I18N_CATALOG_JA,
  "ko": I18N_CATALOG_KO,
  "es": I18N_CATALOG_ES
} as Record<string, Record<string, Record<string, string>>>;
