// SPDX-License-Identifier: GPL-3.0-only
/* eslint-disable */
// This file is generated by ./tools/docs/generate-shared-i18n-runtime.mjs.

export const I18N_CATALOG_LOADERS = {
  "en": async () => (await import("./i18n.generated.en.js")).I18N_CATALOG_EN,
  "zh-CN": async () => (await import("./i18n.generated.zh-CN.js")).I18N_CATALOG_ZH_CN,
  "ja": async () => (await import("./i18n.generated.ja.js")).I18N_CATALOG_JA,
  "ko": async () => (await import("./i18n.generated.ko.js")).I18N_CATALOG_KO,
  "es": async () => (await import("./i18n.generated.es.js")).I18N_CATALOG_ES
} as const;
