// SPDX-License-Identifier: GPL-3.0-only

import type { FreeReplayEndSettlementMode } from '@zinuto/shared/trading';

export const DEFAULT_USER_ID = 'default-user';
export const DEFAULT_SECURITIES_ACCOUNT_ID = 'default-securities';

export const DEFAULT_INITIAL_SECURITIES_BALANCE = 50000;
export const DEFAULT_INITIAL_BANK_BALANCE = 100000;
export const DEFAULT_TRADING_ASSET_CLASS: 'STOCK' | 'FUTURES' | 'FOREX' | 'CRYPTO' = 'STOCK';
export const DEFAULT_TRADING_MARKET_PRESET_ID = 'A_SHARE';
export const DEFAULT_MIN_TRADE_STEP = 100;

export const DEFAULT_COMMISSION_RATE = 0.03;
export const DEFAULT_MAKER_FEE_RATE = 0;
export const DEFAULT_TAKER_FEE_RATE = 0;
export const DEFAULT_FUNDING_RATE = 0;
export const DEFAULT_CONTRACT_MULTIPLIER = 1;
export const DEFAULT_TRANSFER_FEE_RATE = 0.001;
export const DEFAULT_REGULATORY_FEE_RATE = 0;
export const DEFAULT_PLATFORM_FEE_RATE = 0;
export const DEFAULT_TRANSACTION_LEVY_RATE = 0;
export const DEFAULT_SLIPPAGE_RATE = 0.01;
export const DEFAULT_STAMP_DUTY_RATE = 0.05;
export const DEFAULT_COMMISSION_MINIMUM_FEE = 5;
export const DEFAULT_PLATFORM_FEE_MINIMUM_FEE = 0;
export const DEFAULT_TRANSACTION_LEVY_MINIMUM_FEE = 0;
export const DEFAULT_LONG_FINANCING_ANNUAL_RATE = 0;
export const DEFAULT_LONG_INITIAL_MARGIN_RATIO = 100;
export const DEFAULT_LONG_MAINTENANCE_MARGIN_RATIO = 100;
export const DEFAULT_SHORT_BORROW_ANNUAL_RATE = 6;
export const DEFAULT_SHORT_INITIAL_MARGIN_RATIO = 150;
export const DEFAULT_SHORT_MAINTENANCE_MARGIN_RATIO = 130;

export const DEFAULT_STAMP_DUTY_MODE: 'BUY' | 'SELL' | 'DOUBLE' = 'SELL';
export const DEFAULT_STAMP_DUTY_SINGLE_SIDE: 'BUY' | 'SELL' = 'SELL';
export const DEFAULT_POSITION_COST_MODE: 'DILUTED' | 'AVERAGE_OPEN' = 'DILUTED';
export const DEFAULT_TRADE_SETTLEMENT_MODE: 'T0' | 'T1' = 'T1';
export const DEFAULT_FREE_REPLAY_END_SETTLEMENT_MODE: FreeReplayEndSettlementMode = 'FORCE_CLOSE';
export const DEFAULT_TRADE_AMOUNT_INCLUDES_FEES = false;
export const DEFAULT_ALLOW_LONG_MARGIN_TRADING = false;
export const DEFAULT_ALLOW_SHORT_SELLING = false;
