// SPDX-License-Identifier: GPL-3.0-only

import type { BaseTimeframe } from "@zinuto/shared/timeframe";
import type { DataSourceSyncPrefsById } from "@/domains/data-import/dataSourceTypes";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  createNextSystemSettingsTabNavigationRequest,
  type SystemSettingsTabId,
  type SystemSettingsTabNavigationRequest,
} from "@/workspaces/settings/settings/SystemSettingsTabs";
import { useAppUiBootstrapState } from "@/app-shell/useAppUiBootstrapState";
import { useAppDialogState } from "@/app-shell/useAppDialogState";
import { useAppTradingFormState } from "@/app-shell/useAppTradingFormState";
import { useTrainerChartRuntimeState } from "@/app-shell/useTrainerChartRuntimeState";
import { useAppWorkspaceUiState } from "@/app-shell/useAppWorkspaceUiState";
import { useAppSamplePoolState } from "@/app-shell/useAppSamplePoolState";
import { useTrainerSessionDataState } from "@/app-shell/useTrainerSessionDataState";
import { useDrawingToolbarState } from "@/app-shell/useDrawingToolbarState";
import { useTrainerIndicatorDisplayState } from "@/app-shell/useTrainerIndicatorDisplayState";
import { useTrainerAutoplayState } from "@/app-shell/useTrainerAutoplayState";
import { type TrainerHydrationState } from "@/domains/trainer/trainerHydration";
import { type UiSettings } from "@/frontend-kernel/appTypes";
import { DEFAULT_TRAINER_PERIOD_OPTIONS_BY_BASE } from "@/domains/chart/chartPeriods";
import { normalizeDataSourceSyncPrefsById } from "@/app-shell/dataSourceSyncMonitor";
import { buildReplayBarTimestampMs } from "@/domains/chart/replayAggregation";
import { resolveTrainerPeriodAdvanceMeta } from "@/domains/trainer/trainerPeriodAdvance";
import {
  type DataConfigPoolOrderByBase,
  normalizeDataConfigPoolOrderByBase,
  normalizeSystemPoolNameOverrides,
} from "@/app-shell/appRootDataConfigUtils";
import { normalizeCustomSamplePoolNameOverrides } from "@/app-shell/appSamplePools";
import {
  normalizeSystemPoolTradingBindingById,
  type SystemPoolTradingBindingById,
} from "@/app-shell/appRootPoolTradingBinding";
import { type AppTextKey } from "@/frontend-kernel/i18n/messageRuntime";
import { formatMessageByLanguage } from "@/frontend-kernel/i18n/messageRuntime";
import { BUILT_IN_SAMPLE_POOL_IDS } from "@/domains/trainer/samplePools";
import {
  normalizeTradingMarketPresetLabelOverridesById,
  normalizeHiddenBuiltInTradingMarketPresetIds,
  type TradingMarketPresetLabelOverridesById,
} from "@/domains/trainer/tradingMarketPresets";
import { FREE_REPLAY_BASE_TIMEFRAMES } from "@/domains/trainer/freeReplaySetup";
import { DEFAULT_TRADING_SETTINGS } from "@/domains/trainer/defaultTradingSettings";
import type {
  FreeReplayAdvancePeriod,
  SessionTerminationReasonCode,
} from "@/domains/training/types";
import { useRuntimeSecondaryPopupPreload } from "@/app-shell/runtime/useRuntimeSecondaryPopupPreload";
import { formatMessage, type MessageId } from "@zinuto/shared/i18n";
import { useRuntimeChartSettingsMenu } from "@/app-shell/runtime/useRuntimeChartSettingsMenu";
type RuntimeHookScope = AppRootRuntimeProps & Record<string, unknown>;

export type AppRootRuntimeProps = {
  initialUiSettings: UiSettings;
  initialDataPoolRemovedSymbolsBySourceId: Record<string, string[]>;
  canPersistUiSettings: boolean;
};

export const useRuntimeStartupState = (scope: RuntimeHookScope) => {
  const { initialDataPoolRemovedSymbolsBySourceId, initialUiSettings } = scope;
  useRuntimeSecondaryPopupPreload();
  const {
    chartDomRef,
    trainerChartDomAttachVersion,
    specialTrainingChartDomAttachVersion,
    chartRef,
    chartDataRef,
    liveBarSubscriberRef,
    barsRef,
    barsTsMsRef,
    trainerAggregationCacheRef,
    trainerAggregationTailCacheRef,
    barsOffsetRef,
    barsTotalRef,
    snapshotRef,
    isLoadingMoreBarsRef,
    isPrefetchingBarsRef,
    playingLockRef,
    symbolLoadAbortControllerRef,
    symbolLoadRequestVersionRef,
    snapshotAbortControllerRef,
    snapshotRequestVersionRef,
    ensureBarsForwardAbortControllerRef,
    ensureBarsBackwardAbortControllerRef,
    appBootstrapAbortControllerRef,
    activeDrawToolRef,
    drawingOverlayIdRef,
    selectedDrawingIdRef,
    rearmTimerRef,
    drawArmEpochRef,
    armDrawOverlayRef,
    sessionIdRef,
    signalTopRef,
    signalBottomRef,
    showTrainerSubIndicatorsRef,
    showTrainerVolumePaneRef,
    signalTopParamsRef,
    signalBottomParamsRef,
    lastScrollSessionRef,
    chartDataRenderSignatureRef,
    chartMarkerHeavyRenderSignatureRef,
    chartMarkerPositionRenderSignatureRef,
    specialTrainingOverlaySignatureRef,
    lastMainIndicatorMountKeyRef,
    lastSignalIndicatorMountKeyRef,
    visibleAggregatedBarsRef,
    drawingStoreRef,
    currentDisplayPeriodRef,
    pendingDrawingRebuildPeriodRef,
    aggregationPrewarmTaskRef,
    bindTrainerChartDomRef,
    bindSpecialTrainingChartDomRef,
    resolveChartDomForPage,
  } = useTrainerChartRuntimeState();
  const historyRefreshInProgressRef = useRef(false);
  const [trainerHydrationState, setTrainerHydrationState] =
    useState<TrainerHydrationState>("IDLE");
  const {
    persistedUi,
    setError,
    setHint,
    language,
    setLanguage,
    languageSource,
    setLanguageSource,
    themeMode,
    setThemeMode,
    priceColorMode,
    setPriceColorMode,
    tradeColorTheme,
    setTradeColorTheme,
    chartRenderMode,
    setChartRenderMode,
    fontSizePreset,
    setFontSizePreset,
    sessionNameFormat,
    setSessionNameFormat,
    trainerDisplayPeriod,
    setTrainerDisplayPeriod,
    showGlobalDecimals,
    setShowGlobalDecimals,
    showDesktopHelpLauncher,
    setShowDesktopHelpLauncher,
    showDrawingsAcrossPeriods,
    developerModeEnabled,
    setDeveloperModeEnabled,
    desktopCloseButtonAction,
    setDesktopCloseButtonAction,
    systemThemeMode,
    setSystemThemeMode,
  } = useAppUiBootstrapState({
    initialHint: formatMessage(
      initialUiSettings.language ?? "en",
      "appText.ready" as MessageId,
    ),
    initialUiSettings,
  });
  const trainerPeriodOptionsByBase = DEFAULT_TRAINER_PERIOD_OPTIONS_BY_BASE;
  const tt = useCallback(
    (key: AppTextKey) => formatMessageByLanguage(language, key),
    [language],
  );
  const ttf = useCallback(
    (key: AppTextKey, values: Array<unknown> = []) =>
      formatMessageByLanguage(language, key, values),
    [language],
  );
  useEffect(() => {
    setHint(tt("appText.ready"));
  }, [language, setHint]);
  const {
    instruments,
    setInstruments,
    selectedSymbol,
    setSelectedSymbol,
    selectedInstrumentId,
    setSelectedInstrumentId,
    bars,
    setBars,
    barsTimeZone,
    setBarsTimeZone,
    barsOffset,
    setBarsOffset,
    barsTotal,
    setBarsTotal,
    sessionId,
    setSessionId,
    snapshot,
    setSnapshot,
    currentTrainingBaseTimeframe,
    setCurrentTrainingBaseTimeframe,
  } = useTrainerSessionDataState();
  const [
    currentTrainingMinimumBaseTimeframe,
    setCurrentTrainingMinimumBaseTimeframe,
  ] = useState<FreeReplayAdvancePeriod>("1d");
  const barsTsMs = useMemo(() => buildReplayBarTimestampMs(bars), [bars]);
  const effectiveTrainingBaseTimeframe = useMemo<BaseTimeframe>(() => {
    const sourceIndex = FREE_REPLAY_BASE_TIMEFRAMES.indexOf(
      currentTrainingBaseTimeframe,
    );
    const minimumIndex = FREE_REPLAY_BASE_TIMEFRAMES.indexOf(
      currentTrainingMinimumBaseTimeframe as BaseTimeframe,
    );
    if (sourceIndex < 0 || minimumIndex < 0) {
      return currentTrainingBaseTimeframe;
    }
    return sourceIndex >= minimumIndex
      ? currentTrainingBaseTimeframe
      : (currentTrainingMinimumBaseTimeframe as BaseTimeframe);
  }, [currentTrainingBaseTimeframe, currentTrainingMinimumBaseTimeframe]);
  const periodAdvanceMetaState = useMemo(() => {
    if (!snapshot) {
      return resolveTrainerPeriodAdvanceMeta({
        tsMsByIndex: [],
        cursorIndex: 0,
        barsOffset,
        barsTotal,
        allowStep: false,
        displayPeriod: trainerDisplayPeriod,
        baseTimeframe: effectiveTrainingBaseTimeframe,
        timeZone: barsTimeZone ?? undefined,
      });
    }
    return resolveTrainerPeriodAdvanceMeta({
      tsMsByIndex: barsTsMs,
      cursorIndex: snapshot.session.cursor_index,
      barsOffset,
      barsTotal,
      allowStep: Boolean(snapshot.actionState?.allowStep),
      displayPeriod: trainerDisplayPeriod,
      baseTimeframe: effectiveTrainingBaseTimeframe,
      timeZone: barsTimeZone ?? undefined,
    });
  }, [
    barsOffset,
    barsTimeZone,
    barsTotal,
    barsTsMs,
    effectiveTrainingBaseTimeframe,
    snapshot,
    snapshot?.actionState?.allowStep,
    trainerDisplayPeriod,
  ]);

  const {
    mainNativeIndicator,
    setMainNativeIndicator,
    mainNativeIndicatorParams,
    setMainNativeIndicatorParams,
    signalTopIndicator,
    setSignalTopIndicator,
    signalTopIndicatorParams,
    setSignalTopIndicatorParams,
    signalBottomIndicator,
    setSignalBottomIndicator,
    signalBottomIndicatorParams,
    setSignalBottomIndicatorParams,
    showTrainerSubIndicators,
    setShowTrainerSubIndicators,
    tradeMarkerDensityRatio,
    setTradeMarkerDensityRatio,
    selectedDataIndex,
    setSelectedDataIndex,
    chartReady,
    setChartReady,
  } = useTrainerIndicatorDisplayState({ persistedUi });
  const {
    showChartSettingsModal,
    setShowChartSettingsModal,
    showTradingSettingsModal,
    setShowTradingSettingsModal,
    actionDialog,
    setActionDialog,
    noticeDialog,
    setNoticeDialog,
    noticeCountdownMs,
    setNoticeCountdownMs,
    orderEndPrompt,
    setOrderEndPrompt,
    pendingRestoreDrawings,
    setPendingRestoreDrawings,
    isPreparingAction,
    setIsPreparingAction,
    showShortcutModal,
    setShowShortcutModal,
  } = useAppDialogState();
  const [
    systemSettingsTabNavigationRequest,
    setSystemSettingsTabNavigationRequest,
  ] = useState<SystemSettingsTabNavigationRequest | null>(null);
  const requestedSystemSettingsTab =
    systemSettingsTabNavigationRequest?.tab ?? null;
  const requestedSystemSettingsTabRequestId =
    systemSettingsTabNavigationRequest?.requestId ?? 0;
  const setRequestedSystemSettingsTab = useCallback(
    (requestedTab: SystemSettingsTabId | null) => {
      setSystemSettingsTabNavigationRequest((current) =>
        requestedTab === null
          ? null
          : createNextSystemSettingsTabNavigationRequest(current, requestedTab),
      );
    },
    [],
  );
  const [portableRebindTargetSourceIds, setPortableRebindTargetSourceIds] =
    useState<string[]>([]);
  const {
    chartSettingsModalFocusTarget,
    closeIndicatorQuickMenu,
    indicatorQuickMenuState,
    openChartSettingsModal,
    openIndicatorQuickMenu,
    setChartSettingsModalFocusTarget,
    setIndicatorQuickMenuState,
  } = useRuntimeChartSettingsMenu({
    showChartSettingsModal,
    setShowChartSettingsModal,
  });
  const openResetAllDialogRef = useRef<
    (options?: {
      terminationReasonCode?: SessionTerminationReasonCode | null;
    }) => Promise<void>
  >(async () => undefined);
  const handledTrainingTerminationSignatureRef = useRef("");
  const {
    includeSystemDefaultPool,
    setIncludeSystemDefaultPool,
    customSamplePools,
    setCustomSamplePools,
    customSamplePoolsRef,
    activeSamplePoolId,
    setActiveSamplePoolId,
    currentTrainingPoolMeta,
    setCurrentTrainingPoolMeta,
  } = useAppSamplePoolState({
    persistedUi,
  });
  const [
    dataPoolRemovedSymbolsBySourceId,
    setDataPoolRemovedSymbolsBySourceId,
  ] = useState<Record<string, string[]>>(
    () => initialDataPoolRemovedSymbolsBySourceId,
  );
  const [systemPoolNameOverrides, setSystemPoolNameOverrides] = useState<
    Record<string, string>
  >(() =>
    normalizeSystemPoolNameOverrides(
      persistedUi.systemPoolNameOverrides,
      BUILT_IN_SAMPLE_POOL_IDS,
    ),
  );
  const [customPoolNameOverrides, setCustomPoolNameOverrides] = useState<
    Record<string, string>
  >(() =>
    normalizeCustomSamplePoolNameOverrides(persistedUi.customPoolNameOverrides),
  );
  const [dataConfigPoolOrderByBase, setDataConfigPoolOrderByBase] =
    useState<DataConfigPoolOrderByBase>(() =>
      normalizeDataConfigPoolOrderByBase(persistedUi.dataConfigPoolOrderByBase),
    );
  const [dataSourceSyncPrefsById, setDataSourceSyncPrefsById] =
    useState<DataSourceSyncPrefsById>(() =>
      normalizeDataSourceSyncPrefsById(persistedUi.dataSourceSyncPrefsById),
    );
  const {
    drawColors,
    drawLineWidth,
    setDrawLineWidth,
    drawLineType,
    setDrawLineType,
    drawColor,
    setDrawColor,
    drawMagnet,
    setDrawMagnet,
    activeDrawTool,
    setActiveDrawTool,
    selectedDrawingId,
    setSelectedDrawingId,
    allDrawingsVisible,
    setAllDrawingsVisible,
    drawingCount,
    setDrawingCount,
  } = useDrawingToolbarState({
    persistedUi,
    themeMode: themeMode === "system" ? systemThemeMode : themeMode,
  });
  const {
    autoplayBarsPerSec,
    setAutoplayBarsPerSec,
    isAutoplay,
    setIsAutoplay,
  } = useTrainerAutoplayState({ persistedUi });
  const {
    buyTradeInputMode,
    setBuyTradeInputMode,
    buyLotInput,
    setBuyLotInput,
    buyAmountInput,
    setBuyAmountInput,
    buyRatioPresetInputs,
    sellRatioPresetInputs,
    buyRatioInput,
    setBuyRatioInput,
    buyPriceMode,
    setBuyPriceMode,
    sellTradeInputMode,
    setSellTradeInputMode,
    sellLotInput,
    setSellLotInput,
    sellAmountInput,
    setSellAmountInput,
    sellRatioInput,
    setSellRatioInput,
    sellPriceMode,
    setSellPriceMode,
    lotSizeByPool,
    setLotSizeByPool,
    initialSecuritiesInput,
    setInitialSecuritiesInput,
    tradingAssetClass,
    setTradingAssetClass,
    minTradeStepInput,
    setMinTradeStepInput,
    commissionRateInput,
    setCommissionRateInput,
    makerFeeRateInput,
    setMakerFeeRateInput,
    takerFeeRateInput,
    setTakerFeeRateInput,
    fundingRateInput,
    setFundingRateInput,
    contractMultiplierInput,
    setContractMultiplierInput,
    transferFeeRateInput,
    setTransferFeeRateInput,
    regulatoryFeeRateInput,
    setRegulatoryFeeRateInput,
    platformFeeRateInput,
    setPlatformFeeRateInput,
    transactionLevyRateInput,
    setTransactionLevyRateInput,
    slippageRateInput,
    setSlippageRateInput,
    stampDutyRateInput,
    setStampDutyRateInput,
    commissionMinimumFeeInput,
    setCommissionMinimumFeeInput,
    platformFeeMinimumFeeInput,
    setPlatformFeeMinimumFeeInput,
    transactionLevyMinimumFeeInput,
    setTransactionLevyMinimumFeeInput,
    longFinancingAnnualRateInput,
    setLongFinancingAnnualRateInput,
    longInitialMarginRatioInput,
    setLongInitialMarginRatioInput,
    longMaintenanceMarginRatioInput,
    setLongMaintenanceMarginRatioInput,
    shortBorrowAnnualRateInput,
    setShortBorrowAnnualRateInput,
    shortInitialMarginRatioInput,
    setShortInitialMarginRatioInput,
    shortMaintenanceMarginRatioInput,
    setShortMaintenanceMarginRatioInput,
    stampDutyMode,
    setStampDutyMode,
    positionCostMode,
    setPositionCostMode,
    tradeSettlementMode,
    setTradeSettlementMode,
    freeReplayEndSettlementMode,
    setFreeReplayEndSettlementMode,
    tradeAmountIncludesFees,
    setTradeAmountIncludesFees,
    allowLongMarginTrading,
    setAllowLongMarginTrading,
    allowShortSelling,
    setAllowShortSelling,
    tradingMarketPresetKey,
    setTradingMarketPresetKey,
    tradingMarketPresetValuesByKey,
    setTradingMarketPresetValuesByKey,
    tradingMarketPresetCustomTemplates,
    setTradingMarketPresetCustomTemplates,
    tradingSettings,
    setTradingSettings,
    isSavingTradingSettings,
    setIsSavingTradingSettings,
  } = useAppTradingFormState({
    persistedUi,
    customSamplePools,
    defaultTradingSettings: DEFAULT_TRADING_SETTINGS,
  });
  const [
    hiddenBuiltInTradingMarketPresetIds,
    setHiddenBuiltInTradingMarketPresetIds,
  ] = useState(() =>
    normalizeHiddenBuiltInTradingMarketPresetIds(
      persistedUi.hiddenBuiltInTradingMarketPresetIds,
    ),
  );
  const [
    tradingMarketPresetLabelOverridesById,
    setTradingMarketPresetLabelOverridesById,
  ] = useState<TradingMarketPresetLabelOverridesById>(() =>
    normalizeTradingMarketPresetLabelOverridesById(
      persistedUi.tradingMarketPresetLabelOverridesById,
    ),
  );
  const [systemPoolTradingBindingById, setSystemPoolTradingBindingById] =
    useState<SystemPoolTradingBindingById>(() =>
      normalizeSystemPoolTradingBindingById({
        value: persistedUi.freeReplayPoolDefaultEnvironmentById,
        supportedPoolIds: BUILT_IN_SAMPLE_POOL_IDS,
        fallbackAssetClass: tradingAssetClass,
        fallbackMarketPresetId: tradingMarketPresetKey,
        tradingMarketPresetCustomTemplates,
      }),
    );
  const {
    activePage,
    setActivePage,
    systemStorageUsage,
    setSystemStorageUsage,
    isSystemStorageUsageLoading,
    setIsSystemStorageUsageLoading,
    isGlobalResetProgressVisible,
    setIsGlobalResetProgressVisible,
    globalResetProgressLabel,
    setGlobalResetProgressLabel,
    globalResetProgressPercent,
    setGlobalResetProgressPercent,
    globalResetProgressTargetPercent,
    setGlobalResetProgressTargetPercent,
    setGlobalResetModules,
    selectedReplayNoteId,
    setSelectedReplayNoteId,
    activeTrainingRecordNoteId,
    setActiveTrainingRecordNoteId,
    chartNoteHover,
    setChartNoteHover,
    editingProjectId,
    setEditingProjectId,
    editingProjectName,
    setEditingProjectName,
    editingSamplePoolId,
    setEditingSamplePoolId,
    editingSamplePoolName,
    setEditingSamplePoolName,
    historyListCompact,
    setHistoryListCompact,
    viewportScale,
    setViewportScale,
    viewportLayoutMode,
    setViewportLayoutMode,
    pendingCsvFolderImport,
    setPendingCsvFolderImport,
    pendingCsvFieldMapping,
    setPendingCsvFieldMapping,
    isCsvImporting,
    setIsCsvImporting,
    deletingSamplePoolId,
    setDeletingSamplePoolId,
    deletingSamplePoolProgressPercent,
    setDeletingSamplePoolProgressPercent,
    deletingSamplePoolProgressTargetPercent,
    setDeletingSamplePoolProgressTargetPercent,
    isClearingLocalDataSources,
    setIsClearingLocalDataSources,
    clearingLocalDataSourcesProgressPercent,
    setClearingLocalDataSourcesProgressPercent,
    clearingLocalDataSourcesProgressTargetPercent,
    setClearingLocalDataSourcesProgressTargetPercent,
    replayUnavailableMessage,
    setReplayUnavailableMessage,
    isBusy,
    setIsBusy,
    onboardingTourStatus,
    setOnboardingTourStatus,
    onboardingTourStep,
    setOnboardingTourStep,
  } = useAppWorkspaceUiState({
    persistedUi,
  });
  const [displayedWorkspacePage, setDisplayedWorkspacePage] =
    useState(activePage);
  useEffect(() => {
    if (
      activePage !== "SETTINGS" &&
      systemSettingsTabNavigationRequest !== null
    ) {
      setSystemSettingsTabNavigationRequest(null);
    }
  }, [activePage, systemSettingsTabNavigationRequest]);
  return {
    actionDialog,
    activeDrawTool,
    activeDrawToolRef,
    activePage,
    activeSamplePoolId,
    activeTrainingRecordNoteId,
    aggregationPrewarmTaskRef,
    allDrawingsVisible,
    allowLongMarginTrading,
    allowShortSelling,
    appBootstrapAbortControllerRef,
    armDrawOverlayRef,
    autoplayBarsPerSec,
    bars,
    barsOffset,
    barsOffsetRef,
    barsRef,
    barsTimeZone,
    barsTotal,
    barsTotalRef,
    barsTsMs,
    barsTsMsRef,
    bindTrainerChartDomRef,
    bindSpecialTrainingChartDomRef,
    bindChartDomRef: bindTrainerChartDomRef,
    buyAmountInput,
    buyLotInput,
    buyPriceMode,
    buyRatioInput,
    buyRatioPresetInputs,
    buyTradeInputMode,
    chartDataRef,
    chartDataRenderSignatureRef,
    trainerChartDomAttachVersion,
    specialTrainingChartDomAttachVersion,
    chartDomRef,
    chartMarkerHeavyRenderSignatureRef,
    chartMarkerPositionRenderSignatureRef,
    chartNoteHover,
    chartReady,
    chartRef,
    chartRenderMode,
    chartSettingsModalFocusTarget,
    clearingLocalDataSourcesProgressPercent,
    clearingLocalDataSourcesProgressTargetPercent,
    closeIndicatorQuickMenu,
    commissionMinimumFeeInput,
    commissionRateInput,
    contractMultiplierInput,
    currentDisplayPeriodRef,
    displayedWorkspacePage,
    currentTrainingBaseTimeframe,
    currentTrainingMinimumBaseTimeframe,
    currentTrainingPoolMeta,
    customPoolNameOverrides,
    customSamplePools,
    customSamplePoolsRef,
    dataConfigPoolOrderByBase,
    dataPoolRemovedSymbolsBySourceId,
    dataSourceSyncPrefsById,
    deletingSamplePoolId,
    deletingSamplePoolProgressPercent,
    deletingSamplePoolProgressTargetPercent,
    drawArmEpochRef,
    drawColor,
    drawColors,
    drawLineType,
    drawLineWidth,
    drawMagnet,
    drawingCount,
    drawingOverlayIdRef,
    drawingStoreRef,
    editingProjectId,
    editingProjectName,
    editingSamplePoolId,
    editingSamplePoolName,
    effectiveTrainingBaseTimeframe,
    ensureBarsBackwardAbortControllerRef,
    ensureBarsForwardAbortControllerRef,
    fontSizePreset,
    freeReplayEndSettlementMode,
    fundingRateInput,
    globalResetProgressLabel,
    globalResetProgressPercent,
    globalResetProgressTargetPercent,
    handledTrainingTerminationSignatureRef,
    hiddenBuiltInTradingMarketPresetIds,
    historyListCompact,
    historyRefreshInProgressRef,
    includeSystemDefaultPool,
    indicatorQuickMenuState,
    initialSecuritiesInput,
    instruments,
    isAutoplay,
    isBusy,
    isClearingLocalDataSources,
    isCsvImporting,
    isGlobalResetProgressVisible,
    isLoadingMoreBarsRef,
    isPrefetchingBarsRef,
    isPreparingAction,
    isSavingTradingSettings,
    isSystemStorageUsageLoading,
    language,
    languageSource,
    lastMainIndicatorMountKeyRef,
    lastScrollSessionRef,
    lastSignalIndicatorMountKeyRef,
    liveBarSubscriberRef,
    longFinancingAnnualRateInput,
    longInitialMarginRatioInput,
    longMaintenanceMarginRatioInput,
    lotSizeByPool,
    mainNativeIndicator,
    mainNativeIndicatorParams,
    makerFeeRateInput,
    minTradeStepInput,
    noticeCountdownMs,
    noticeDialog,
    openChartSettingsModal,
    openIndicatorQuickMenu,
    openResetAllDialogRef,
    orderEndPrompt,
    onboardingTourStatus,
    onboardingTourStep,
    pendingCsvFieldMapping,
    pendingCsvFolderImport,
    pendingDrawingRebuildPeriodRef,
    pendingRestoreDrawings,
    periodAdvanceMetaState,
    persistedUi,
    platformFeeMinimumFeeInput,
    platformFeeRateInput,
    playingLockRef,
    portableRebindTargetSourceIds,
    positionCostMode,
    priceColorMode,
    rearmTimerRef,
    regulatoryFeeRateInput,
    replayUnavailableMessage,
    requestedSystemSettingsTab,
    requestedSystemSettingsTabRequestId,
    resolveChartDomForPage,
    selectedDataIndex,
    selectedDrawingId,
    selectedDrawingIdRef,
    selectedInstrumentId,
    selectedReplayNoteId,
    selectedSymbol,
    sellAmountInput,
    sellLotInput,
    sellPriceMode,
    sellRatioInput,
    sellRatioPresetInputs,
    sellTradeInputMode,
    sessionId,
    sessionIdRef,
    sessionNameFormat,
    setActionDialog,
    setActiveDrawTool,
    setActivePage,
    setDisplayedWorkspacePage,
    setActiveSamplePoolId,
    setActiveTrainingRecordNoteId,
    setAllDrawingsVisible,
    setAllowLongMarginTrading,
    setAllowShortSelling,
    setAutoplayBarsPerSec,
    setBars,
    setBarsOffset,
    setBarsTimeZone,
    setBarsTotal,
    setBuyAmountInput,
    setBuyLotInput,
    setBuyPriceMode,
    setBuyRatioInput,
    setBuyTradeInputMode,
    setChartNoteHover,
    setChartReady,
    setChartRenderMode,
    setChartSettingsModalFocusTarget,
    setClearingLocalDataSourcesProgressPercent,
    setClearingLocalDataSourcesProgressTargetPercent,
    setCommissionMinimumFeeInput,
    setCommissionRateInput,
    setContractMultiplierInput,
    setCurrentTrainingBaseTimeframe,
    setCurrentTrainingMinimumBaseTimeframe,
    setCurrentTrainingPoolMeta,
    setCustomPoolNameOverrides,
    setCustomSamplePools,
    setDataConfigPoolOrderByBase,
    setDataPoolRemovedSymbolsBySourceId,
    setDataSourceSyncPrefsById,
    setDeletingSamplePoolId,
    setDeletingSamplePoolProgressPercent,
    setDeletingSamplePoolProgressTargetPercent,
    setDrawColor,
    setDrawLineType,
    setDrawLineWidth,
    setDrawMagnet,
    setDrawingCount,
    setEditingProjectId,
    setEditingProjectName,
    setEditingSamplePoolId,
    setEditingSamplePoolName,
    setError,
    setFontSizePreset,
    setFreeReplayEndSettlementMode,
    setFundingRateInput,
    setGlobalResetModules,
    setGlobalResetProgressLabel,
    setGlobalResetProgressPercent,
    setGlobalResetProgressTargetPercent,
    setHiddenBuiltInTradingMarketPresetIds,
    setHint,
    setHistoryListCompact,
    setIncludeSystemDefaultPool,
    setIndicatorQuickMenuState,
    setInitialSecuritiesInput,
    setInstruments,
    setIsAutoplay,
    setIsBusy,
    setIsClearingLocalDataSources,
    setIsCsvImporting,
    setIsGlobalResetProgressVisible,
    setIsPreparingAction,
    setIsSavingTradingSettings,
    setIsSystemStorageUsageLoading,
    setLanguage,
    setLanguageSource,
    setLongFinancingAnnualRateInput,
    setLongInitialMarginRatioInput,
    setLongMaintenanceMarginRatioInput,
    setLotSizeByPool,
    setMainNativeIndicator,
    setMainNativeIndicatorParams,
    setMakerFeeRateInput,
    setMinTradeStepInput,
    setNoticeCountdownMs,
    setNoticeDialog,
    setOrderEndPrompt,
    setOnboardingTourStatus,
    setOnboardingTourStep,
    setPendingCsvFieldMapping,
    setPendingCsvFolderImport,
    setPendingRestoreDrawings,
    setPlatformFeeMinimumFeeInput,
    setPlatformFeeRateInput,
    setPortableRebindTargetSourceIds,
    setPositionCostMode,
    setPriceColorMode,
    setRegulatoryFeeRateInput,
    setReplayUnavailableMessage,
    setRequestedSystemSettingsTab,
    setSelectedDataIndex,
    setSelectedDrawingId,
    setSelectedInstrumentId,
    setSelectedReplayNoteId,
    setSelectedSymbol,
    setSellAmountInput,
    setSellLotInput,
    setSellPriceMode,
    setSellRatioInput,
    setSellTradeInputMode,
    setSessionId,
    setSessionNameFormat,
    setShortBorrowAnnualRateInput,
    setShortInitialMarginRatioInput,
    setShortMaintenanceMarginRatioInput,
    setDeveloperModeEnabled,
    setShowChartSettingsModal,
    setShowGlobalDecimals,
    setShowShortcutModal,
    setShowTradingSettingsModal,
    setShowTrainerSubIndicators,
    setSignalBottomIndicator,
    setSignalBottomIndicatorParams,
    setSignalTopIndicator,
    setSignalTopIndicatorParams,
    setSlippageRateInput,
    setSnapshot,
    setStampDutyMode,
    setStampDutyRateInput,
    setSystemPoolNameOverrides,
    setSystemPoolTradingBindingById,
    setSystemStorageUsage,
    setSystemThemeMode,
    setTakerFeeRateInput,
    setThemeMode,
    setTradeAmountIncludesFees,
    setTradeColorTheme,
    setTradeMarkerDensityRatio,
    setTradeSettlementMode,
    setTradingAssetClass,
    setTradingMarketPresetCustomTemplates,
    setTradingMarketPresetKey,
    setTradingMarketPresetLabelOverridesById,
    setTradingMarketPresetValuesByKey,
    setTradingSettings,
    setTrainerDisplayPeriod,
    setTrainerHydrationState,
    setTransactionLevyMinimumFeeInput,
    setTransactionLevyRateInput,
    setTransferFeeRateInput,
    setViewportLayoutMode,
    setViewportScale,
    shortBorrowAnnualRateInput,
    shortInitialMarginRatioInput,
    shortMaintenanceMarginRatioInput,
    desktopCloseButtonAction,
    setDesktopCloseButtonAction,
    developerModeEnabled,
    showChartSettingsModal,
    showDrawingsAcrossPeriods,
    showDesktopHelpLauncher,
    setShowDesktopHelpLauncher,
    showGlobalDecimals,
    showShortcutModal,
    showTradingSettingsModal,
    showTrainerSubIndicators,
    showTrainerSubIndicatorsRef,
    showTrainerVolumePaneRef,
    signalBottomIndicator,
    signalBottomIndicatorParams,
    signalBottomParamsRef,
    signalBottomRef,
    signalTopIndicator,
    signalTopIndicatorParams,
    signalTopParamsRef,
    signalTopRef,
    slippageRateInput,
    snapshot,
    snapshotAbortControllerRef,
    snapshotRef,
    snapshotRequestVersionRef,
    specialTrainingOverlaySignatureRef,
    stampDutyMode,
    stampDutyRateInput,
    symbolLoadAbortControllerRef,
    symbolLoadRequestVersionRef,
    systemPoolNameOverrides,
    systemPoolTradingBindingById,
    systemStorageUsage,
    systemThemeMode,
    takerFeeRateInput,
    themeMode,
    tradeAmountIncludesFees,
    tradeColorTheme,
    tradeMarkerDensityRatio,
    tradeSettlementMode,
    tradingAssetClass,
    tradingMarketPresetCustomTemplates,
    tradingMarketPresetKey,
    tradingMarketPresetLabelOverridesById,
    tradingMarketPresetValuesByKey,
    tradingSettings,
    trainerAggregationCacheRef,
    trainerAggregationTailCacheRef,
    trainerDisplayPeriod,
    trainerHydrationState,
    trainerPeriodOptionsByBase,
    transactionLevyMinimumFeeInput,
    transactionLevyRateInput,
    transferFeeRateInput,
    tt,
    ttf,
    viewportLayoutMode,
    viewportScale,
    visibleAggregatedBarsRef,
  };
};
