// SPDX-License-Identifier: GPL-3.0-only

import { useCallback, useMemo } from "react";
import {
  formatMoney,
  formatRatio,
  formatSignedMoney,
} from "@/ui/formatting/format";
import { useReplayTrainerSettingsModalProps } from "@/app-shell/useReplayTrainerSettingsModalProps";
import { useAppWorkspacePageBundleArgs } from "@/app-shell/useAppWorkspacePageBundleArgs";
import { useAppTradingMarketPresetActions } from "@/app-shell/useAppTradingMarketPresetActions";
import {
  formatStorageBytes,
  getBaseTimeframeLabels,
} from "@/frontend-kernel/uiOptions";
import {
  normalizeInput,
  normalizeIntegerInput,
} from "@/frontend-kernel/valueFormat";
import { getLanguageOptions } from "@/ui/config/uiLabels";
import { SAMPLE_POOL_ALL_ID } from "@/domains/trainer/samplePools";
import { type TradingMarketPresetId } from "@/domains/trainer/tradingMarketPresets";
import { applySessionTradingSettingsToReplayPanelProps } from "@/domains/trainer/sessionTradingSettingsPanel";
import { useRuntimeTrainerWorkspaceBundle } from "@/app-shell/runtime/trainer-runtime/useRuntimeTrainerWorkspaceBundle";
import { buildRuntimeReplaySettingsPanelArgs } from "@/app-shell/runtime/trainer-runtime/runtimeReplaySettingsPanelArgs";
import {
  buildRuntimeDataConfigWorkspaceBundleArgs,
  buildRuntimeHistoryWorkspaceBundleArgs,
  buildRuntimeNotesWorkspaceBundleArgs,
  buildRuntimeSystemSettingsWorkspaceBundleArgs,
  buildRuntimeWorkspacePageBundleArgs,
} from "@/app-shell/runtime/workspace-shell/runtimeWorkspacePageBundleBuilders";
import type { RuntimeWorkspaceBundleScope } from "@/app-shell/runtime/runtimeWorkspaceBundleTypes";
import { useRuntimeGlobalResetConfirmation } from "@/app-shell/runtime/useRuntimeGlobalResetConfirmation";

export type { AppRootRuntimeProps } from "@/app-shell/runtime/runtimeWorkspaceBundleTypes";

export const useRuntimeWorkspaceBundles = (
  scope: RuntimeWorkspaceBundleScope,
) => {
  const freeReplaySelectedInstrumentId = String(
    (scope as { freeReplaySelectedInstrumentId?: unknown })
      .freeReplaySelectedInstrumentId ?? "",
  );
  const {
    activeFontSizeLabel,
    activeLanguageLabel,
    activePage,
    activeSessionTradingSettings,
    activeThemeLabel,
    activeTradingMarketPresetLabel,
    activeTradingMarketPresetValues,
    allowLongMarginTrading,
    allowShortSelling,
    applyPrepAnchorSelection,
    applyTradingMarketPresetValues,
    bars,
    barsTimeZone,
    buyAmountInput,
    buyBlockReason,
    buyEstimate,
    buyLotInput,
    buyOrderDisabled,
    buyPriceMode,
    buyRatioInput,
    buyRatioPresetOptions,
    buyTradeInputMode,
    calendarSpanText,
    canSaveTradingMarketPresetToCurrent,
    canUndoTrainerAction,
    cancelRenameSamplePool,
    cancelRenameTrainingProject,
    changeClass,
    chartRenderMode,
    clearAllTrainingProjects,
    clearSelectedFolder,
    clearingLocalDataSourcesProgressPercent,
    combinedEnabledPoolSymbols,
    commissionMinimumFeeInput,
    commissionRateInput,
    commitReplayNoteTitle,
    compactScriptLanguage,
    confirmLocalDataSourceSyncPreview,
    contractMultiplierInput,
    controlCsvImportCardJob,
    createHistoryReviewReplayNote,
    createSystemMarkers,
    createTradingCustomTemplateFromCurrent,
    csvImportCardControlAction,
    csvImportCardViews,
    cumulativePnlRate,
    currentPosition,
    currentTradingFee,
    customSamplePools,
    dataPoolRemovedSymbolsBySourceId,
    dataSourceSyncMonitorStateById,
    dataSourceSyncPrefsById,
    defaultReplayNoteTitle,
    deleteTrainingProject,
    deleteTrainingProjects,
    deletingSamplePoolId,
    deletingSamplePoolProgressPercent,
    dismissLocalDataSourceSyncPreview,
    editingProjectId,
    editingProjectName,
    editingSamplePoolId,
    editingSamplePoolName,
    effectiveThemeMode,
    effectiveTrainingBaseTimeframe,
    enabledPoolGroupCount,
    fetchDetailSymbolBarsRange,
    fetchDetailSymbolDiagnostics,
    floatingRate,
    fontSizePreset,
    fontSizePresetOptions,
    formatReplayNoteTime,
    formatTradeLogQuantityText,
    formatWorkspaceTradeQuantityText,
    freeReplayAssetOptions,
    freeReplayAvailableSymbolCount,
    freeReplayBlindBoxOptions,
    freeReplayBlindBoxValue,
    freeReplayEndSettlementMode,
    freeReplayEnvironmentAssetOptions,
    freeReplayEnvironmentPresetOptions,
    freeReplayEnvironmentRuleCards,
    freeReplayHasAvailableSymbols,
    freeReplayModeOptions,
    freeReplayPersistEnvironmentToPool,
    freeReplayPrepAnchorTs,
    freeReplayPrepConfig,
    freeReplayPrepEnvironmentAssetClass,
    freeReplayPrepEnvironmentPresetId,
    freeReplaySamplePoolOptions,
    freeReplaySelectedEnvironmentPresetLabel,
    freeReplaySelectedPoolId,
    freeReplaySelectedSymbol,
    freeReplayStartButtonIconName,
    freeReplayStartDisabled,
    freeReplayStartReadiness,
    freeReplaySymbolOptions,
    freeReplayTimeframeOptions,
    fundingRateInput,
    globalResetAffectedPoolCount,
    globalResetAffectedSymbolCount,
    globalResetProgressLabel,
    globalResetProgressPercent,
    globalResetStorageRows,
    globalResetStorageTotalText,
    isGlobalResetStorageSummaryReady,
    handleAllowLongMarginTradingChange,
    handleAllowShortSellingChange,
    handleCreateTradingMarketPresetFromCurrent,
    handleFreeReplayPrepBaseTimeframeChange,
    handleFreeReplayPrepBlindBoxChange,
    handleFreeReplayPrepEnvironmentAssetClassChange,
    handleFreeReplayPrepEnvironmentPresetChange,
    handleFreeReplayPrepModeChange,
    handleFreeReplayPrepPersistEnvironmentToPoolChange,
    handleFreeReplayPrepSamplePoolChange,
    handleFreeReplayPrepSymbolChange,
    handleResumeLatestTrainerSession,
    handleSystemDevSimulationDataChanged,
    handleTradingAssetClassChange,
    handleTradingMarketPresetKeyChange,
    hasLiveResumableTrainerSession,
    hasNextBar,
    headerSymbolCount,
    historyKeyword,
    historyListCompact,
    historyPoolFilterOptions,
    historyProfitFilter,
    historyProjectsNextCursor,
    historyReplayChartBindings,
    historySamplePoolFilterSelectValue,
    historyVisibleProjects,
    initialSecuritiesInput,
    initialSecuritiesLockedReason,
    isBusy,
    isClearingLocalDataSources,
    isCsvImporting,
    isFreeReplayPrepMode,
    isGlobalResetProgressVisible,
    isHistoryProjectsLoading,
    isHistoryProjectsLoadingMore,
    isInitialSecuritiesEditable,
    isNativeImportDragActive,
    isPreparingAction,
    isPreparingCsvImportPreview,
    isReplayNotesLoading,
    isReplayNotesLoadingMore,
    isReplaySettingsSaveDisabled,
    isSavingTradingSettings,
    isSystemStorageUsageLoading,
    isTradingMarketPresetDirty,
    klineProgressData,
    language,
    lastUndoableTrainerAction,
    latestResumableTrainerSession,
    leverageExposureSummary,
    listVisibleBuiltInTradingMarketPresetIdsByAssetClass,
    loadMoreReplayNotes,
    loadMoreTrainingProjects,
    longFinancingAnnualRateInput,
    longInitialMarginRatioInput,
    longMaintenanceMarginRatioInput,
    makerFeeRateInput,
    marketPresetChips,
    minTradeStepInput,
    moveCustomPoolWithinTimeframe,
    nextOpenUnavailable,
    notesPageController,
    openCsvFolderPathAndPrepareImport,
    openCsvFolderPickerAndPrepareImport,
    openDataWorkspaceForPortableRebind,
    openDeviceTransferSettings,
    openResetAllDialog,
    pendingLocalDataSourceSyncPreview,
    preparingLocalDataSourceSyncPreview,
    placeOrder,
    platformFeeMinimumFeeInput,
    platformFeeRateInput,
    pnlClass,
    poolSettingsRows,
    portableRebindTargetSourceIds,
    positionCostMode,
    positionMarketValue,
    prepAnchorNavigatorWindowPayload,
    preparingCsvImportPreviewPercent,
    preparingCsvImportPreviewProgress,
    priceColorMode,
    refreshSystemStorageUsage,
    regulatoryFeeRateInput,
    removeSamplePool,
    removeSymbolsFromSamplePool,
    renderTrainingNoteSnapshot,
    replayNotesNextCursor,
    replaySettingsAllowLongOptions,
    replaySettingsAllowShortOptions,
    replaySettingsAssetClassOptions,
    replaySettingsDensityOptions,
    replaySettingsFreeReplayEndSettlementModeOptions,
    replaySettingsPositionCostOptions,
    replaySettingsSettlementModeOptions,
    replaySettingsStampDutyOptions,
    replaySettingsTradeAmountOptions,
    replaySpanText,
    requestedSystemSettingsTab,
    requestedSystemSettingsTabRequestId,
    resetAllStoredData,
    resetAllTradingAssetParameters,
    resetTrainerToPrepView,
    resolveFallbackTradingMarketPresetId,
    resolveTradingMarketPresetLabel,
    resolveTradingMarketPresetValues,
    resolveTradingMarketPresetValuesForAssetClass,
    reverseChangeClass,
    runDataSourceSyncQuickCheckSweep,
    saveRenameTrainingProject,
    saveSamplePoolRename,
    saveTradingSettings,
    securitiesAccount,
    securitiesDelta,
    securitiesTotal,
    selectLocalDataSourceSyncPreviewPlan,
    selectedHistoryCompactStats,
    selectedHistoryProject,
    selectedHistoryProjectId,
    selectedHistoryProjectReplayNoteCount,
    sellBlockReason,
    sellEstimate,
    sellOrderDisabled,
    sessionId,
    setBuyAmountInput,
    setBuyLotInput,
    setBuyPriceMode,
    setBuyRatioInput,
    setBuyTradeInputMode,
    setChartRenderMode,
    setCommissionMinimumFeeInput,
    setCommissionRateInput,
    setContractMultiplierInput,
    setDataPoolRemovedSymbolsBySourceId,
    setDataSourceSyncPrefsById,
    setEditingProjectName,
    setEditingSamplePoolName,
    setError,
    setFontSizePreset,
    setFreeReplayEndSettlementMode,
    setFundingRateInput,
    setHiddenBuiltInTradingMarketPresetIds,
    setHistoryKeyword,
    setHistoryListCompact,
    setHistoryProfitFilter,
    setHistorySamplePoolFilter,
    setInitialSecuritiesInput,
    setLanguage,
    setLongFinancingAnnualRateInput,
    setLongInitialMarginRatioInput,
    setLongMaintenanceMarginRatioInput,
    setMakerFeeRateInput,
    setMinTradeStepInput,
    setPlatformFeeMinimumFeeInput,
    setPlatformFeeRateInput,
    setPositionCostMode,
    setPriceColorMode,
    setRegulatoryFeeRateInput,
    setSelectedHistoryProjectId,
    setSelectedReplayNoteId,
    setShortBorrowAnnualRateInput,
    setShortInitialMarginRatioInput,
    setShortMaintenanceMarginRatioInput,
    setShowChartSettingsModal,
    setShowGlobalDecimals,
    setSlippageRateInput,
    setStampDutyMode,
    setStampDutyRateInput,
    setSystemPoolTradingBindingById,
    setTakerFeeRateInput,
    setThemeMode,
    setTradeAmountIncludesFees,
    setTradeColorTheme,
    setTradeMarkerDensityRatio,
    setTradeSettlementMode,
    setTradingMarketPresetCustomTemplates,
    setTradingMarketPresetKey,
    setTradingMarketPresetLabelOverridesById,
    setTradingMarketPresetValuesByKey,
    setTrainerDisplayPeriod,
    setTransactionLevyMinimumFeeInput,
    setTransactionLevyRateInput,
    setTransferFeeRateInput,
    setUserLanguagePreference,
    shortBorrowAnnualRateInput,
    shortInitialMarginRatioInput,
    shortMaintenanceMarginRatioInput,
    showChartSettingsModal,
    showGlobalDecimals,
    slippageRateInput,
    snapshot,
    stampDutyMode,
    stampDutyRateInput,
    startPreparedFreeReplay,
    startRenameSamplePool,
    startRenameTrainingProject,
    startTrainingWithSymbol,
    stepNext,
    storageUsageRows,
    storageUsageTotalText,
    syncCustomSamplePoolsFromDataSources,
    syncSamplePoolWithSourceFolder,
    systemSettingsDevSimulationInput,
    systemStorageUsage,
    takerFeeRateInput,
    themeMode,
    totalPoolGroupCount,
    tradeAmountIncludesFees,
    tradeCapacity,
    tradeColorTheme,
    tradeLogRows,
    tradeLogSideStats,
    tradeMarkerDensityLevel,
    tradeSettlementMode,
    tradingAssetClass,
    tradingMarketPresetCustomTemplates,
    tradingMarketPresetKey,
    tradingSettingsDraftParseResult,
    tradingSettingsText,
    trainerChartWorkspaceLayout,
    trainerDisplayPeriod,
    trainerHydrationState,
    trainerKlineSourceProgressLine,
    trainerPeriodOptionsByBase,
    trainerTradingAssetUi,
    trainingDateRange,
    trainingDays,
    trainingProjects,
    transactionLevyMinimumFeeInput,
    transactionLevyRateInput,
    transferFeeRateInput,
    tt,
    ttf,
    ui,
    undo,
    undoAvailableTrainerSteps,
    undoMaxTrainerSteps,
    updateReplayNoteColorTokens,
    updateReplayNoteContent,
    updateReplayNoteTitle,
    withBuySellCount,
    withCountUnit,
    withLabelValue,
  } = scope;
  const handleSaveTradingSettings = useCallback(() => {
    void saveTradingSettings();
  }, [saveTradingSettings]);
  const handleResumeLatestTrainerSessionStable = useCallback(async () => {
    await handleResumeLatestTrainerSession();
  }, [handleResumeLatestTrainerSession]);
  const handleStepNext = useCallback(async () => {
    await stepNext();
  }, [stepNext]);
  const handleClearLocalPools = useCallback(() => {
    void clearSelectedFolder();
  }, [clearSelectedFolder]);
  const handleHistoryRetentionApplied = useCallback(async () => {
    await handleSystemDevSimulationDataChanged({ reason: "cleanup" });
  }, [handleSystemDevSimulationDataChanged]);
  const languageOptions = useMemo(
    () => getLanguageOptions(language),
    [language],
  );
  const {
    handleSaveTradingMarketPresetToCurrent,
    handleSaveTradingMarketPresetAsNew,
    handleRenameTradingMarketPresetById,
    handleDeleteTradingMarketPresetById,
  } = useAppTradingMarketPresetActions({
    tradingMarketPresetKey,
    tradingAssetClass,
    activeTradingMarketPresetValues,
    tradingMarketPresetCustomTemplates,
    resolveTradingMarketPresetValues,
    resolveTradingMarketPresetValuesForAssetClass,
    resolveFallbackTradingMarketPresetId,
    createTradingCustomTemplateFromCurrent,
    applyTradingMarketPresetValues,
    listVisibleBuiltInTradingMarketPresetIdsByAssetClass,
    setTradingMarketPresetValuesByKey,
    setTradingMarketPresetCustomTemplates,
    setTradingMarketPresetLabelOverridesById,
    setHiddenBuiltInTradingMarketPresetIds,
    setSystemPoolTradingBindingById,
    setTradingMarketPresetKey,
  });
  const replayTrainerSettingsPanelProps = useReplayTrainerSettingsModalProps(
    buildRuntimeReplaySettingsPanelArgs({
      tradeMarkerDensityTitle: ui.tradeMarkerDensityRatio,
      tradeMarkerDensityLevelSuffix: ui.tradeMarkerDensityLevelSuffix,
      tradeMarkerDensityHelpText: ui.tradeMarkerDensityRatioDesc,
      tradeMarkerDensityLevel,
      setTradeMarkerDensityRatio,
      replaySettingsDensityOptions,
      initialSecuritiesInput,
      setInitialSecuritiesInput,
      isInitialSecuritiesEditable,
      initialSecuritiesLockedReason,
      normalizeIntegerInput,
      tradingAssetClass,
      replaySettingsAssetClassOptions,
      handleTradingAssetClassChange,
      minTradeStepInput,
      setMinTradeStepInput,
      commissionRateInput,
      setCommissionRateInput,
      makerFeeRateInput,
      setMakerFeeRateInput,
      takerFeeRateInput,
      setTakerFeeRateInput,
      fundingRateInput,
      setFundingRateInput,
      contractMultiplierInput,
      setContractMultiplierInput,
      transferFeeRateInput,
      setTransferFeeRateInput,
      regulatoryFeeRateInput,
      setRegulatoryFeeRateInput,
      platformFeeRateInput,
      setPlatformFeeRateInput,
      transactionLevyRateInput,
      setTransactionLevyRateInput,
      slippageRateInput,
      setSlippageRateInput,
      stampDutyRateInput,
      setStampDutyRateInput,
      commissionMinimumFeeInput,
      setCommissionMinimumFeeInput,
      platformFeeMinimumFeeInput,
      setPlatformFeeMinimumFeeInput,
      transactionLevyMinimumFeeInput,
      setTransactionLevyMinimumFeeInput,
      longFinancingAnnualRateInput,
      setLongFinancingAnnualRateInput,
      longInitialMarginRatioInput,
      setLongInitialMarginRatioInput,
      longMaintenanceMarginRatioInput,
      setLongMaintenanceMarginRatioInput,
      shortBorrowAnnualRateInput,
      setShortBorrowAnnualRateInput,
      shortInitialMarginRatioInput,
      setShortInitialMarginRatioInput,
      shortMaintenanceMarginRatioInput,
      setShortMaintenanceMarginRatioInput,
      replaySettingsStampDutyOptions,
      stampDutyMode,
      setStampDutyMode,
      replaySettingsSettlementModeOptions,
      tradeSettlementMode,
      setTradeSettlementMode,
      replaySettingsFreeReplayEndSettlementModeOptions,
      freeReplayEndSettlementMode,
      setFreeReplayEndSettlementMode,
      marketPresetChips,
      handleTradingMarketPresetKeyChange,
      handleCreateTradingMarketPresetFromCurrent,
      handleRenameTradingMarketPresetById,
      handleDeleteTradingMarketPresetById,
      resetAllTradingAssetParameters,
      isTradingMarketPresetDirty,
      canSaveTradingMarketPresetToCurrent,
      handleSaveTradingMarketPresetToCurrent,
      handleSaveTradingMarketPresetAsNew,
      activeTradingMarketPresetLabel,
      replaySettingsPositionCostOptions,
      positionCostMode,
      setPositionCostMode,
      replaySettingsAllowLongOptions,
      allowLongMarginTrading,
      handleAllowLongMarginTradingChange,
      replaySettingsAllowShortOptions,
      allowShortSelling,
      handleAllowShortSellingChange,
      replaySettingsTradeAmountOptions,
      tradeAmountIncludesFees,
      setTradeAmountIncludesFees,
      percentSymbol: ui.percentSymbol,
      onSave: handleSaveTradingSettings,
      isSavingTradingSettings,
      isBusy,
      isSaveDisabled: isReplaySettingsSaveDisabled,
    }),
  );
  const activeTradingPresetAutoSaveSignature = JSON.stringify({
    presetId: tradingMarketPresetKey,
    values: activeTradingMarketPresetValues,
    initialSecuritiesInput,
    freeReplayEndSettlementMode,
    positionCostMode,
    tradeAmountIncludesFees,
  });
  const activeTrainerMarketPresetLabel = useMemo(() => {
    const normalizedSessionId = String(sessionId || "").trim();
    const sessionMarketPresetId = String(
      activeSessionTradingSettings?.marketPresetId || "",
    ).trim();
    if (
      activePage === "TRAINER" &&
      normalizedSessionId &&
      sessionMarketPresetId
    ) {
      return resolveTradingMarketPresetLabel(
        sessionMarketPresetId as TradingMarketPresetId,
        sessionMarketPresetId,
      );
    }
    return activeTradingMarketPresetLabel;
  }, [
    activePage,
    activeSessionTradingSettings?.marketPresetId,
    activeTradingMarketPresetLabel,
    resolveTradingMarketPresetLabel,
    sessionId,
  ]);
  const sessionTrainerSettingsPanelProps = useMemo(() => {
    const normalizedSessionId = String(sessionId || "").trim();
    const sessionSettings = snapshot?.sessionTradingSettings;
    if (
      activePage !== "TRAINER" ||
      !normalizedSessionId ||
      !sessionSettings ||
      snapshot?.termination?.isTerminated
    ) {
      return replayTrainerSettingsPanelProps;
    }

    return applySessionTradingSettingsToReplayPanelProps({
      panel: replayTrainerSettingsPanelProps,
      settings: sessionSettings,
      activeTradingMarketPresetLabel: activeTrainerMarketPresetLabel,
    });
  }, [
    activePage,
    activeTrainerMarketPresetLabel,
    replayTrainerSettingsPanelProps,
    sessionId,
    snapshot?.sessionTradingSettings,
    snapshot?.termination?.isTerminated,
  ]);
  const persistActiveTradingPresetEdits = useCallback(() => {
    if (canSaveTradingMarketPresetToCurrent) {
      handleSaveTradingMarketPresetToCurrent();
    }
    if (tradingSettingsDraftParseResult.ok && !isSavingTradingSettings) {
      void saveTradingSettings({ quietHint: true });
    }
  }, [
    canSaveTradingMarketPresetToCurrent,
    handleSaveTradingMarketPresetToCurrent,
    isSavingTradingSettings,
    saveTradingSettings,
    tradingSettingsDraftParseResult.ok,
  ]);
  const { canResumeTrainerSession, trainerWorkspaceBundle } =
    useRuntimeTrainerWorkspaceBundle({
      layout: trainerChartWorkspaceLayout,
      ui,
      isFreeReplayPrepMode,
      freeReplayModeOptions,
      freeReplayPrepConfig,
      freeReplayAssetOptions,
      freeReplayEnvironmentAssetOptions,
      freeReplayEnvironmentPresetOptions,
      freeReplaySelectedEnvironmentAssetClass:
        freeReplayPrepEnvironmentAssetClass,
      freeReplaySelectedEnvironmentPresetId: freeReplayPrepEnvironmentPresetId,
      freeReplaySelectedEnvironmentPresetLabel:
        freeReplaySelectedEnvironmentPresetLabel,
      freeReplayEnvironmentRuleCards,
      freeReplayPersistEnvironmentToPool,
      freeReplayTimeframeOptions,
      freeReplaySamplePoolOptions,
      freeReplaySelectedPoolId,
      freeReplaySymbolOptions,
      freeReplayAvailableSymbolCount,
      freeReplaySelectedInstrumentId,
      freeReplaySelectedSymbol,
      freeReplayPrepAnchorTs,
      freeReplayStartHasExplicitAnchor:
        freeReplayStartReadiness.hasExplicitAnchor,
      language,
      freeReplayBlindBoxOptions,
      freeReplayBlindBoxValue,
      startPointWindowPayload: prepAnchorNavigatorWindowPayload,
      onApplyStartPoint: applyPrepAnchorSelection,
      freeReplayStartDisabled,
      freeReplayStartDisableReason: freeReplayStartReadiness.reason,
      freeReplayHasAvailableSymbols,
      freeReplayStartButtonIconName,
      startPreparedFreeReplay,
      resetTrainerToPrepView,
      onResumeLatestTrainerSession: handleResumeLatestTrainerSessionStable,
      handleFreeReplayPrepModeChange,
      handleFreeReplayPrepEnvironmentAssetClassChange,
      handleFreeReplayPrepEnvironmentPresetChange,
      handleFreeReplayPrepPersistEnvironmentToPoolChange,
      handleFreeReplayPrepBaseTimeframeChange,
      handleFreeReplayPrepSamplePoolChange,
      handleFreeReplayPrepSymbolChange,
      handleFreeReplayPrepBlindBoxChange,
      trainerTradingAssetUi,
      tradeLogBaseTimeframe: effectiveTrainingBaseTimeframe,
      tradeLogTimeZone: snapshot?.session.timeZone ?? barsTimeZone,
      tradingPresetEditor: {
        activeMarketPresetLabel: activeTrainerMarketPresetLabel,
        trainerSettingsPanel: sessionTrainerSettingsPanelProps,
        tradingSettingsText,
        autoSaveSignature: activeTradingPresetAutoSaveSignature,
        isAutoSaving: isSavingTradingSettings,
        onAutoSave: persistActiveTradingPresetEdits,
      },
      tt,
      ttf,
      trainerHydrationState,
      isBusy,
      isPreparingAction,
      trainingDays,
      trainingKlineCount: klineProgressData.current,
      trainingKlineSourceProgressLine: trainerKlineSourceProgressLine,
      hasTrainingKlineProgressWarning: Boolean(
        snapshot && bars.length && !hasNextBar,
      ),
      calendarSpanText,
      replaySpanText,
      securitiesTotal,
      securitiesDelta,
      positionMarketValue,
      securitiesAccount,
      currentPosition,
      currentTradingFee,
      floatingRate,
      cumulativePnlRate,
      leverageExposureSummary,
      tradeCapacity,
      trainingDateRange,
      buyTradeInputMode,
      buyLotInput,
      buyAmountInput,
      buyRatioInput,
      buyRatioPresetOptions,
      buyEstimate,
      sellEstimate,
      buyPriceMode,
      buyBlockReason,
      sellBlockReason,
      buyOrderDisabled,
      sellOrderDisabled,
      nextOpenUnavailable,
      canUndo: canUndoTrainerAction,
      undoAvailableSteps: undoAvailableTrainerSteps,
      undoMaxSteps: undoMaxTrainerSteps,
      lastUndoableAction: lastUndoableTrainerAction,
      tradeLogRows,
      tradeLogSideStats,
      formatMoney,
      formatRatio,
      formatSignedMoney,
      formatTradingQuantityText: formatWorkspaceTradeQuantityText,
      formatTradeLogQuantityText,
      withCountUnit,
      withBuySellCount,
      pnlClass,
      normalizeInput,
      setBuyTradeInputMode,
      setBuyLotInput,
      setBuyAmountInput,
      setBuyRatioInput,
      setBuyPriceMode,
      onStepNext: handleStepNext,
      isStepNextDisabled: !sessionId || !snapshot,
      undo,
      placeOrder,
      openResetAllDialog,
      hasLiveResumableTrainerSession,
      latestResumableTrainerSession,
    });
  const historyWorkspaceBundleArgs = buildRuntimeHistoryWorkspaceBundleArgs({
    tt,
    compactScriptLanguage,
    historyListCompact,
    historyKeyword,
    historyProfitFilter,
    historySamplePoolFilterSelectValue,
    samplePoolAllId: SAMPLE_POOL_ALL_ID,
    historyPoolFilterOptions,
    trainingProjects,
    selectedHistoryCompactStats,
    historyVisibleProjects,
    selectedHistoryProjectId,
    selectedHistoryProjectReplayNoteCount,
    selectedHistoryProject,
    historyProjectsNextCursor,
    replayNotesNextCursor,
    isHistoryProjectsLoading,
    isHistoryProjectsLoadingMore,
    isReplayNotesLoading,
    isReplayNotesLoadingMore,
    editingProjectId,
    editingProjectName,
    effectiveThemeMode,
    showGlobalDecimals,
    priceColorMode,
    tradeColorTheme,
    chartRenderMode,
    language,
    trainerDisplayPeriod,
    trainerPeriodOptionsByBase,
    historyReplayChartBindings,
    showChartSettingsModal,
    setTrainerDisplayPeriod,
    setChartRenderMode,
    createSystemMarkers,
    createHistoryReviewReplayNote,
    setHistoryKeyword,
    setHistoryProfitFilter,
    setHistorySamplePoolFilter,
    clearAllTrainingProjects,
    setHistoryListCompact,
    setSelectedHistoryProjectId,
    startRenameTrainingProject,
    deleteTrainingProject,
    deleteTrainingProjects,
    saveRenameTrainingProject,
    cancelRenameTrainingProject,
    setEditingProjectName,
    loadMoreTrainingProjects,
    loadMoreReplayNotes,
    setShowChartSettingsModal,
    formatMoney,
    formatRatio,
    formatSignedMoney,
    withCountUnit,
    withBuySellCount,
    changeClass,
    reverseChangeClass,
    pnlClass,
    formatReplayNoteTime,
  });
  const notesWorkspaceBundleArgs = buildRuntimeNotesWorkspaceBundleArgs({
    isActive: activePage === "NOTES",
    language,
    defaultReplayNoteTitle,
    notesPageController,
    onSelectReplayNoteId: setSelectedReplayNoteId,
    formatReplayNoteTime,
    formatMoney,
    onUpdateReplayNoteTitle: updateReplayNoteTitle,
    onCommitReplayNoteTitle: commitReplayNoteTitle,
    renderTrainingNoteSnapshot,
    onUpdateReplayNoteContent: updateReplayNoteContent,
    onUpdateReplayNoteColorTokens: updateReplayNoteColorTokens,
  });
  const dataConfigWorkspaceBundleArgs =
    buildRuntimeDataConfigWorkspaceBundleArgs({
      ui,
      tt,
      enabledPoolGroupCount,
      combinedEnabledPoolSymbols,
      customSamplePoolsCount: customSamplePools.length,
      totalPoolGroupCount,
      headerSymbolCount,
      marketDataStorageBytes: Math.max(
        0,
        Number(systemStorageUsage?.categories.marketDataBytes ?? 0),
      ),
      compactScriptLanguage,
      isCsvImporting,
      isPreparingCsvImportPreview,
      isClearingLocalDataSources,
      isNativeImportDragActive,
      deletingSamplePoolId,
      preparingCsvImportPreviewPercent,
      preparingCsvImportPreviewProgress,
      clearingLocalDataSourcesProgressPercent,
      deletingSamplePoolProgressPercent,
      csvImportCardViews,
      csvImportCardControlAction,
      poolSettingsRows,
      dataSourceSyncMonitorStateById,
      dataSourceSyncPrefsById,
      editingSamplePoolId,
      editingSamplePoolName,
      pendingLocalDataSourceSyncPreview,
      preparingLocalDataSourceSyncPreview,
      removedSymbolsByPool: dataPoolRemovedSymbolsBySourceId,
      formatMoney,
      formatStorageBytes,
      withLabelValue,
      getBaseTimeframeLabels,
      effectiveThemeMode,
      priceColorMode,
      language,
      trainerDisplayPeriod,
      trainerPeriodOptionsByBase,
      historyReplayChartBindings,
      onClearLocalPools: handleClearLocalPools,
      openCsvFolderPickerAndPrepareImport,
      openCsvFolderPathAndPrepareImport,
      controlCsvImportCardJob,
      fetchDetailSymbolBarsRange,
      fetchDetailSymbolDiagnostics,
      startTrainingWithSymbol,
      dismissLocalDataSourceSyncPreview,
      selectLocalDataSourceSyncPreviewPlan,
      confirmLocalDataSourceSyncPreview,
      syncSamplePoolWithSourceFolder,
      removeSymbolsFromSamplePool,
      runDataSourceSyncQuickCheckSweep,
      refreshLocalDataSources: syncCustomSamplePoolsFromDataSources,
      setEditingSamplePoolName,
      saveRenameSamplePool: saveSamplePoolRename,
      cancelRenameSamplePool,
      startRenameSamplePool,
      moveCustomPoolWithinTimeframe,
      removeCustomPool: removeSamplePool,
      portableRebindTargetSourceIds,
      openDeviceTransferSettings,
      setRemovedSymbolsByPool: setDataPoolRemovedSymbolsBySourceId,
      setDataSourceSyncPrefsById,
    });
  const enableDeveloperMode = useCallback(() => {
    if (scope.developerModeEnabled === true) {
      return;
    }
    const setDeveloperModeEnabled = scope.setDeveloperModeEnabled;
    if (typeof setDeveloperModeEnabled === "function") {
      (setDeveloperModeEnabled as (value: boolean) => void)(true);
    }
  }, [scope.developerModeEnabled, scope.setDeveloperModeEnabled]);
  const requestGlobalResetConfirmation = useRuntimeGlobalResetConfirmation({
    isBusy,
    isPreparingAction,
    isGlobalResetProgressVisible,
    isGlobalResetStorageSummaryReady,
    globalResetStorageTotalText,
    globalResetAffectedPoolCount,
    globalResetAffectedSymbolCount,
    confirmTitle: tt("appText.confirmOneClickReset"),
    requestErrorMessage: tt("appText.request"),
    setError,
    resetAllStoredData,
  });
  const systemSettingsWorkspaceBundleArgs =
    buildRuntimeSystemSettingsWorkspaceBundleArgs({
      isActive: activePage === "SETTINGS",
      requestedTab: requestedSystemSettingsTab,
      requestedTabRequestId: requestedSystemSettingsTabRequestId,
      tt,
      ui,
      activeLanguageLabel,
      activeFontSizeLabel,
      activeThemeLabel,
      language,
      fontSizePreset,
      themeMode,
      desktopCloseButtonAction: scope.desktopCloseButtonAction,
      priceColorMode,
      tradeColorTheme,
      showGlobalDecimals,
      developerModeEnabled: scope.developerModeEnabled === true,
      isSystemStorageUsageLoading,
      isBusy,
      isPreparingAction,
      isGlobalResetProgressVisible,
      globalResetProgressLabel,
      globalResetProgressPercent,
      storageUsageTotalText,
      storageUsageRows,
      languageOptions,
      fontSizePresetOptions,
      setCurrentUiLanguage: setUserLanguagePreference,
      setLanguage,
      setFontSizePreset,
      setThemeMode,
      setDesktopCloseButtonAction: scope.setDesktopCloseButtonAction,
      setPriceColorMode,
      setTradeColorTheme,
      setShowGlobalDecimals,
      refreshSystemStorageUsage,
      onHistoryRetentionApplied: handleHistoryRetentionApplied,
      onRequestGlobalReset: requestGlobalResetConfirmation,
      onEnableDeveloperMode: enableDeveloperMode,
      globalResetStorageTotalText,
      globalResetStorageRows,
      isGlobalResetStorageSummaryReady,
      globalResetAffectedPoolCount,
      globalResetAffectedSymbolCount,
      openDataWorkspaceForPortableRebind,
      withLabelValue,
      formatStorageBytes,
      devSimulationInput: systemSettingsDevSimulationInput,
    });
  const workspacePageBundleArgs = useAppWorkspacePageBundleArgs(
    buildRuntimeWorkspacePageBundleArgs({
      trainer: trainerWorkspaceBundle,
      history: historyWorkspaceBundleArgs,
      notes: notesWorkspaceBundleArgs,
      dataConfig: dataConfigWorkspaceBundleArgs,
      systemSettings: systemSettingsWorkspaceBundleArgs,
    }),
  );
  return {
    activeTradingPresetAutoSaveSignature,
    canResumeTrainerSession,
    dataConfigWorkspaceBundleArgs,
    handleDeleteTradingMarketPresetById,
    handleRenameTradingMarketPresetById,
    handleSaveTradingMarketPresetAsNew,
    handleSaveTradingMarketPresetToCurrent,
    historyWorkspaceBundleArgs,
    notesWorkspaceBundleArgs,
    persistActiveTradingPresetEdits,
    replayTrainerSettingsPanelProps,
    systemSettingsWorkspaceBundleArgs,
    trainerWorkspaceBundle,
    workspacePageBundleArgs,
  };
};
