// SPDX-License-Identifier: GPL-3.0-only

import { normalizeImportHeader } from '@zinuto/shared/importRules';
import { INPUT_LIMITS, trimAndLimitInputText } from '@zinuto/shared/input-limits';
import { normalizeTimeZone } from '@zinuto/shared/timezone';
import {
  assertTradingCalendarConfig,
  type TradingCalendarConfig,
  type TradingSessionRange,
} from '@zinuto/shared/tradingCalendar';
import type { CsvFieldMapping } from '../../domain/dataSource/csvFieldMappingTypes.js';
import type { LocalDataSourceSummary } from './types.js';
import { preserveImportWireRelativePath } from '../../domain/dataSource/importPathSemantics.js';

type CsvFieldKey = keyof Omit<CsvFieldMapping, 'timestampMode'>;
type SupportedBaseTimeframe = '1m' | '5m' | '1h' | '1d';
type CsvImportEntryMode = 'GENERAL' | 'FULL_REIMPORT';
type CsvPoolNamingStrategy = 'FLAT' | 'WITH_PARENT';
type TimeZoneOrigin = 'PRESET_DEFAULT' | 'INFERRED_DEFAULT' | 'USER_SELECTED';

export type LocalDataImportDraftValidationReasonCode =
  | 'READY'
  | 'CSV_MAPPING_REQUIRED'
  | 'CSV_MAPPING_HEADER_MISSING'
  | 'CSV_MAPPING_DUPLICATED'
  | 'LOCAL_DATA_IMPORT_NO_CONFIRMABLE_PLAN'
  | 'LOCAL_DATA_IMPORT_PREVIEW_EXPIRED'
  | 'LOCAL_DATA_TRADING_CALENDAR_INVALID'
  | 'LOCAL_DATA_IMPORT_TARGET_SOURCE_INVALID'
  | 'LOCAL_DATA_IMPORT_REPAIR_WARNINGS'
  | 'LOCAL_DATA_IMPORT_TIME_ZONE_CONFIRMATION_REQUIRED';

export type LocalDataImportMappingValidationIssue = {
  field: CsvFieldKey;
  reasonCode: Extract<
    LocalDataImportDraftValidationReasonCode,
    'CSV_MAPPING_REQUIRED' | 'CSV_MAPPING_HEADER_MISSING' | 'CSV_MAPPING_DUPLICATED'
  >;
  header: string;
};

export type LocalDataImportTradingCalendarValidationIssue = {
  previewPlanId: string;
  baseTimeframe: SupportedBaseTimeframe | null;
  reasonCode: Extract<
    LocalDataImportDraftValidationReasonCode,
    | 'LOCAL_DATA_IMPORT_NO_CONFIRMABLE_PLAN'
    | 'LOCAL_DATA_IMPORT_PREVIEW_EXPIRED'
    | 'LOCAL_DATA_TRADING_CALENDAR_INVALID'
  >;
};

export type LocalDataImportTargetingValidationIssue = {
  previewPlanId: string;
  targetSourceId: string;
  reasonCode: 'LOCAL_DATA_IMPORT_TARGET_SOURCE_INVALID';
};

export type LocalDataImportBlockingIssueKind =
  | 'none'
  | 'field-mapping'
  | 'targeting'
  | 'trading-calendar'
  | 'repair-warnings'
  | 'time-zone';

export type LocalDataImportPlanningTargetSourceOption = {
  sourceId: string;
  sourceName: string;
  baseTimeframe: SupportedBaseTimeframe;
  importScopeStrategy: CsvPoolNamingStrategy | null;
  importScopeTopLevelSubfolder: string;
  timeZone: string;
  timeZoneOrigin: TimeZoneOrigin;
  tradingCalendar: TradingCalendarConfig;
};

export type LocalDataImportPlanReadModelRow = {
  id: string;
  previewPlanId: string;
  strategy: CsvPoolNamingStrategy;
  topLevelSubfolder: string;
  poolName: string;
  autoGeneratedPoolName: string;
  sourceId: string;
  targetSourceId: string;
  targetSourceOptions: Array<{
    sourceId: string;
    sourceName: string;
  }>;
  hasExistingTargetOptions: boolean;
  symbolCount: number;
  fileCount: number;
  baseTimeframe: SupportedBaseTimeframe;
  effectiveTimeZone: string;
  effectiveTimeZoneOrigin: TimeZoneOrigin;
  effectiveTimeZoneSource:
    | 'NEW_SOURCE_PENDING_IMPORT'
    | 'EXISTING_SOURCE'
    | 'FULL_REIMPORT';
  targetSourceTimeZone: string | null;
  targetSourceTimeZoneOrigin: TimeZoneOrigin | null;
  tradingCalendar: TradingCalendarConfig;
  targetSourceTradingCalendar: TradingCalendarConfig | null;
  willUpdateExistingSourceTimeZone: boolean;
  willUpdateExistingSourceTradingCalendar: boolean;
};

export type LocalDataImportPlanningReadModel = {
  targetSourceOptions: LocalDataImportPlanningTargetSourceOption[];
  recommendedTimeZone: string;
  recommendedTimeZoneReason:
    | 'PRESET_DEFAULT'
    | 'RULE_INFERRED'
    | 'TIMESTAMP_INFERRED'
    | 'EXISTING_SOURCE'
    | 'SYSTEM_FALLBACK';
  recommendedTradingCalendar: TradingCalendarConfig;
  scopeStrategy: CsvPoolNamingStrategy;
  availableScopeStrategies: CsvPoolNamingStrategy[];
  planRows: LocalDataImportPlanReadModelRow[];
};

export type LocalDataImportDraftValidation = {
  mapping: {
    valid: boolean;
    reasonCode: LocalDataImportDraftValidationReasonCode;
    issueCount: number;
    issues: LocalDataImportMappingValidationIssue[];
  };
  targeting: {
    valid: boolean;
    reasonCode: LocalDataImportDraftValidationReasonCode;
    issueCount: number;
    issues: LocalDataImportTargetingValidationIssue[];
  };
  tradingCalendar: {
    valid: boolean;
    reasonCode: LocalDataImportDraftValidationReasonCode;
    issueCount: number;
    issues: LocalDataImportTradingCalendarValidationIssue[];
  };
  repair: {
    valid: boolean;
    reasonCode: LocalDataImportDraftValidationReasonCode;
    warningCount: number;
  };
  timeZone: {
    valid: boolean;
    reasonCode: LocalDataImportDraftValidationReasonCode;
    confirmationRequired: boolean;
  };
  confirm: {
    enabled: boolean;
    reasonCode: LocalDataImportDraftValidationReasonCode;
  };
  blockingIssue: {
    kind: LocalDataImportBlockingIssueKind;
    reasonCode: LocalDataImportDraftValidationReasonCode;
  };
  planning: LocalDataImportPlanningReadModel;
  validatedAt: string;
};

export type LocalDataImportDraftPlanValidationInput = {
  previewPlanId: string;
  baseTimeframe: SupportedBaseTimeframe | null;
  tradingCalendar: unknown;
};

export type LocalDataImportDraftPlanOverrideInput = {
  previewPlanId: string;
  targetSourceId?: string;
  sourceTouched?: boolean;
  poolName?: string;
  nameTouched?: boolean;
};

export type LocalDataImportDraftPlanningInput = {
  importEntryMode?: CsvImportEntryMode;
  fullReimportTargetSourceId?: string;
  importTimeZone?: string;
  importTimeZoneMode?: 'AUTO' | 'MANUAL';
  timeZoneConfirmed?: boolean;
  timeZoneConfidence?: 'HIGH' | 'MEDIUM' | 'LOW';
  suggestedTimeZone?: string;
  suggestedTimeZoneReason?:
    | 'PRESET_DEFAULT'
    | 'RULE_INFERRED'
    | 'TIMESTAMP_INFERRED'
    | 'EXISTING_SOURCE'
    | 'SYSTEM_FALLBACK';
  scopeStrategy?: CsvPoolNamingStrategy;
  tradingCalendar?: unknown;
  tradingCalendarTouched?: boolean;
  planOverrides?: LocalDataImportDraftPlanOverrideInput[];
  repairWarningCount?: number;
  locale?: string;
};

type LocalDataImportDraftPlanLike = {
  id: string;
  strategy: CsvPoolNamingStrategy;
  baseTimeframe: SupportedBaseTimeframe;
  topLevelSubfolder: string;
  defaultPoolName?: string;
  symbolCount: number;
  fileCount: number;
};

const BASE_FIELD_RENDER_ORDER: CsvFieldKey[] = [
  'date',
  'open',
  'close',
  'high',
  'low',
  'volume',
];
const SPLIT_FIELD_RENDER_ORDER: CsvFieldKey[] = [
  'date',
  'time',
  'open',
  'close',
  'high',
  'low',
  'volume',
];
const OPTIONAL_FIELDS = new Set<CsvFieldKey>(['volume']);
const TIMEFRAME_STEP_MINUTES: Record<SupportedBaseTimeframe, number> = {
  '1m': 1,
  '5m': 5,
  '1h': 60,
  '1d': 1,
};
const DAY_MINUTES = 24 * 60;
const CSV_IMPORT_TARGET_SOURCE_AUTO_CREATE_ID = '__zinuto_auto_create__';
const ALL_DAY_TRADING_SESSION: TradingSessionRange = {
  startMinute: 0,
  endMinute: DAY_MINUTES,
  crossesMidnight: false,
};

const EMPTY_PLANNING_READ_MODEL: LocalDataImportPlanningReadModel = {
  targetSourceOptions: [],
  recommendedTimeZone: 'Asia/Shanghai',
  recommendedTimeZoneReason: 'SYSTEM_FALLBACK',
  recommendedTradingCalendar: {
    tradingDays: [1, 2, 3, 4, 5],
    sessions: [{ startMinute: 0, endMinute: DAY_MINUTES, crossesMidnight: false }],
  },
  scopeStrategy: 'FLAT',
  availableScopeStrategies: [],
  planRows: [],
};

const resolveFieldRenderOrder = (
  timestampMode: CsvFieldMapping['timestampMode'],
): CsvFieldKey[] =>
  timestampMode === 'SPLIT'
    ? [...SPLIT_FIELD_RENDER_ORDER]
    : [...BASE_FIELD_RENDER_ORDER];

const firstReasonCode = <T extends { reasonCode: LocalDataImportDraftValidationReasonCode }>(
  issues: T[],
  fallback: LocalDataImportDraftValidationReasonCode,
): LocalDataImportDraftValidationReasonCode =>
  issues[0]?.reasonCode ?? fallback;

const normalizeHeaderSet = (headersRaw: readonly string[]): Set<string> =>
  new Set(
    headersRaw
      .map((header) => normalizeImportHeader(header))
      .filter((header) => header.length > 0),
  );

const hasMappingIssueForFieldReason = (
  issues: LocalDataImportMappingValidationIssue[],
  field: CsvFieldKey,
  reasonCode: LocalDataImportMappingValidationIssue['reasonCode'],
): boolean =>
  issues.some((issue) => issue.field === field && issue.reasonCode === reasonCode);

export const validateLocalDataImportDraftMapping = (
  mapping: CsvFieldMapping,
  headersRaw: readonly string[],
): LocalDataImportDraftValidation['mapping'] => {
  const headers = normalizeHeaderSet(headersRaw);
  const selectedByHeader = new Map<string, CsvFieldKey>();
  const issues: LocalDataImportMappingValidationIssue[] = [];
  const activeFields = resolveFieldRenderOrder(mapping.timestampMode);

  activeFields.forEach((field) => {
    const header = String(mapping[field] ?? '').trim();
    if (!header) {
      if (!OPTIONAL_FIELDS.has(field)) {
        issues.push({
          field,
          reasonCode: 'CSV_MAPPING_REQUIRED',
          header: '',
        });
      }
      return;
    }

    const normalizedHeader = normalizeImportHeader(header);
    if (!normalizedHeader || !headers.has(normalizedHeader)) {
      issues.push({
        field,
        reasonCode: 'CSV_MAPPING_HEADER_MISSING',
        header,
      });
      return;
    }

    const existingField = selectedByHeader.get(normalizedHeader);
    if (existingField) {
      if (!hasMappingIssueForFieldReason(issues, existingField, 'CSV_MAPPING_DUPLICATED')) {
        issues.push({
          field: existingField,
          reasonCode: 'CSV_MAPPING_DUPLICATED',
          header,
        });
      }
      issues.push({
        field,
        reasonCode: 'CSV_MAPPING_DUPLICATED',
        header,
      });
      return;
    }
    selectedByHeader.set(normalizedHeader, field);
  });

  return {
    valid: issues.length === 0,
    reasonCode: firstReasonCode(issues, 'READY'),
    issueCount: issues.length,
    issues,
  };
};

const getTradingSessionDurationMinutes = (session: TradingSessionRange): number =>
  session.crossesMidnight
    ? DAY_MINUTES - session.startMinute + session.endMinute
    : session.endMinute - session.startMinute;

const isTradingSessionAlignedToTimeframe = (
  session: TradingSessionRange,
  baseTimeframe: SupportedBaseTimeframe,
): boolean => {
  if (baseTimeframe === '1d') {
    return true;
  }
  if (session.startMinute === 0 && session.endMinute === DAY_MINUTES) {
    return true;
  }
  return getTradingSessionDurationMinutes(session) % TIMEFRAME_STEP_MINUTES[baseTimeframe] === 0;
};

export const isTradingCalendarValidForLocalDataImport = (
  calendarRaw: unknown,
  baseTimeframe: SupportedBaseTimeframe,
): boolean => {
  let calendar: TradingCalendarConfig;
  try {
    calendar = assertTradingCalendarConfig(calendarRaw);
  } catch {
    return false;
  }
  return calendar.sessions.every((session) =>
    isTradingSessionAlignedToTimeframe(session, baseTimeframe),
  );
};

export const normalizeTradingCalendarForLocalDataImport = (
  calendarRaw: unknown,
  baseTimeframe: SupportedBaseTimeframe,
): TradingCalendarConfig => {
  const calendar = assertTradingCalendarConfig(calendarRaw);
  if (baseTimeframe !== '1d') {
    return calendar;
  }
  return {
    ...calendar,
    sessions: [{ ...ALL_DAY_TRADING_SESSION }],
  };
};

const normalizeSourceTimeZoneOrigin = (value: unknown): TimeZoneOrigin => {
  const raw = String(value || '').trim();
  return raw === 'USER_SELECTED' || raw === 'PRESET_DEFAULT'
    ? raw
    : 'INFERRED_DEFAULT';
};

const normalizeImportEntryMode = (value: unknown): CsvImportEntryMode =>
  value === 'FULL_REIMPORT' ? 'FULL_REIMPORT' : 'GENERAL';

const normalizeScopeStrategy = (value: unknown): CsvPoolNamingStrategy =>
  value === 'WITH_PARENT' ? 'WITH_PARENT' : 'FLAT';

const sanitizePoolName = (value: unknown, fallback: string): string =>
  trimAndLimitInputText(String(value ?? ''), INPUT_LIMITS.samplePoolNameChars) ||
  trimAndLimitInputText(fallback, INPUT_LIMITS.samplePoolNameChars) ||
  'Sample Pool';

const serializeCalendarKey = (calendar: TradingCalendarConfig | null): string =>
  calendar ? JSON.stringify(calendar) : '';

const preserveRelativePath = preserveImportWireRelativePath;

const normalizePlanningCalendar = (
  calendarRaw: unknown,
  fallback: TradingCalendarConfig,
  baseTimeframe: SupportedBaseTimeframe,
): TradingCalendarConfig => {
  try {
    return normalizeTradingCalendarForLocalDataImport(calendarRaw, baseTimeframe);
  } catch {
    return normalizeTradingCalendarForLocalDataImport(fallback, baseTimeframe);
  }
};

const buildTargetSourceOptions = (
  sources: readonly LocalDataSourceSummary[],
  locale: string,
): LocalDataImportPlanningTargetSourceOption[] =>
  sources
    .filter((source) => source.status !== 'IMPORTING')
    .map((source) => ({
      sourceId: String(source.id || '').trim(),
      sourceName: String(source.name || source.id || '').trim(),
      baseTimeframe: source.baseTimeframe,
      importScopeStrategy: source.importScopeStrategy,
      importScopeTopLevelSubfolder: preserveRelativePath(
        source.importScopeTopLevelSubfolder,
      ),
      timeZone: normalizeTimeZone(source.timeZone),
      timeZoneOrigin: normalizeSourceTimeZoneOrigin(source.timeZoneOrigin),
      tradingCalendar: normalizeTradingCalendarForLocalDataImport(
        source.tradingCalendar,
        source.baseTimeframe,
      ),
    }))
    .filter((source) => Boolean(source.sourceId))
    .sort((left, right) =>
      left.sourceName.localeCompare(right.sourceName, locale || 'zh-CN'),
    );

const resolveFullReimportPlan = (
  plans: readonly LocalDataImportDraftPlanLike[],
  targetSource: LocalDataImportPlanningTargetSourceOption | null,
): LocalDataImportDraftPlanLike | null => {
  if (!targetSource) {
    return null;
  }
  const configuredScopeStrategy =
    targetSource.importScopeStrategy === 'WITH_PARENT' ? 'WITH_PARENT' : 'FLAT';
  const configuredTopLevelSubfolder = preserveRelativePath(
    targetSource.importScopeTopLevelSubfolder,
  );
  return (
    plans.find(
      (plan) =>
        plan.baseTimeframe === targetSource.baseTimeframe &&
        plan.strategy === configuredScopeStrategy &&
        preserveRelativePath(plan.topLevelSubfolder) === configuredTopLevelSubfolder,
    ) ??
    plans.find((plan) => plan.baseTimeframe === targetSource.baseTimeframe) ??
    null
  );
};

const planRowsFallbackIndex = (
  planId: string,
  plans: readonly LocalDataImportDraftPlanLike[],
): number => Math.max(0, plans.findIndex((plan) => plan.id === planId));

export const buildLocalDataImportPlanningReadModel = ({
  plans: plansRaw,
  sources,
  input,
  fallbackTradingCalendar,
}: {
  plans: readonly LocalDataImportDraftPlanLike[];
  sources: readonly LocalDataSourceSummary[];
  input?: LocalDataImportDraftPlanningInput;
  fallbackTradingCalendar: TradingCalendarConfig;
}): LocalDataImportPlanningReadModel => {
  const locale = String(input?.locale || 'zh-CN').trim() || 'zh-CN';
  const targetSourceOptions = buildTargetSourceOptions(sources, locale);
  const sourceById = new Map(targetSourceOptions.map((source) => [source.sourceId, source] as const));
  const importEntryMode = normalizeImportEntryMode(input?.importEntryMode);
  const scopeStrategy = normalizeScopeStrategy(input?.scopeStrategy);
  const fullReimportTargetSource =
    importEntryMode === 'FULL_REIMPORT'
      ? sourceById.get(String(input?.fullReimportTargetSourceId || '').trim()) ?? null
      : null;
  const recommendedTimeZone = normalizeTimeZone(
    fullReimportTargetSource?.timeZone || input?.suggestedTimeZone || input?.importTimeZone || 'Asia/Shanghai',
  );
  const recommendedTimeZoneReason = fullReimportTargetSource
    ? 'EXISTING_SOURCE'
    : input?.suggestedTimeZoneReason ?? 'SYSTEM_FALLBACK';
  const recommendedTradingCalendar =
    fullReimportTargetSource?.tradingCalendar ?? fallbackTradingCalendar;
  const importTimeZone = normalizeTimeZone(input?.importTimeZone || recommendedTimeZone);
  const overridesByPlanId = new Map(
    (Array.isArray(input?.planOverrides) ? input.planOverrides : [])
      .map((override) => [String(override.previewPlanId || '').trim(), override] as const)
      .filter(([planId]) => Boolean(planId)),
  );
  const availableScopeStrategies = Array.from(
    new Set(
      plansRaw
        .filter((plan) => Math.max(0, Number(plan.fileCount) || 0) > 0 && Math.max(0, Number(plan.symbolCount) || 0) > 0)
        .map((plan) => plan.strategy),
    ),
  );
  const fullReimportPlan = resolveFullReimportPlan(plansRaw, fullReimportTargetSource);
  const scopedPlans = plansRaw
    .filter((plan) => Math.max(0, Number(plan.fileCount) || 0) > 0 && Math.max(0, Number(plan.symbolCount) || 0) > 0)
    .filter((plan) => {
      if (importEntryMode === 'FULL_REIMPORT') {
        return Boolean(fullReimportPlan) && plan.id === fullReimportPlan?.id;
      }
      return plan.strategy === scopeStrategy;
    });

  const planRows = scopedPlans.map<LocalDataImportPlanReadModelRow>((plan) => {
    const override = overridesByPlanId.get(plan.id) ?? null;
    const autoGeneratedPoolName = sanitizePoolName(
      plan.defaultPoolName,
      `Sample Pool ${planRowsFallbackIndex(plan.id, scopedPlans) + 1}`,
    );
    const isFullReimport =
      importEntryMode === 'FULL_REIMPORT' &&
      fullReimportTargetSource?.baseTimeframe === plan.baseTimeframe;
    const sourceOptionsForPlan = isFullReimport && fullReimportTargetSource
      ? [fullReimportTargetSource]
      : targetSourceOptions.filter((source) => source.baseTimeframe === plan.baseTimeframe);
    const rowTargetOptions = isFullReimport && fullReimportTargetSource
      ? [
          {
            sourceId: fullReimportTargetSource.sourceId,
            sourceName: fullReimportTargetSource.sourceName,
          },
        ]
      : [
          {
            sourceId: CSV_IMPORT_TARGET_SOURCE_AUTO_CREATE_ID,
            sourceName: autoGeneratedPoolName,
          },
          ...sourceOptionsForPlan.map((source) => ({
            sourceId: source.sourceId,
            sourceName: source.sourceName,
          })),
        ];
    const requestedTargetSourceId = String(override?.targetSourceId || '').trim();
    const defaultTargetSourceId = isFullReimport && fullReimportTargetSource
      ? fullReimportTargetSource.sourceId
      : CSV_IMPORT_TARGET_SOURCE_AUTO_CREATE_ID;
    const targetSourceId = requestedTargetSourceId || defaultTargetSourceId;
    const selectedSource =
      targetSourceId === CSV_IMPORT_TARGET_SOURCE_AUTO_CREATE_ID
        ? null
        : sourceOptionsForPlan.find((source) => source.sourceId === targetSourceId) ?? null;
    const shouldCreateNewSourceFromNameOverride =
      !isFullReimport &&
      Boolean(selectedSource) &&
      Boolean(override?.nameTouched) &&
      String(override?.poolName || '').trim() !== String(selectedSource?.sourceName || '').trim();
    const sourceId = shouldCreateNewSourceFromNameOverride
      ? ''
      : selectedSource?.sourceId ?? '';
    const effectiveTimeZoneSource = isFullReimport
      ? 'FULL_REIMPORT'
      : selectedSource
        ? 'EXISTING_SOURCE'
        : 'NEW_SOURCE_PENDING_IMPORT';
    const effectiveTimeZone =
      effectiveTimeZoneSource === 'EXISTING_SOURCE'
        ? selectedSource?.timeZone ?? importTimeZone
        : importTimeZone;
    const effectiveTimeZoneOrigin =
      effectiveTimeZoneSource === 'EXISTING_SOURCE'
        ? selectedSource?.timeZoneOrigin ?? 'INFERRED_DEFAULT'
        : input?.importTimeZoneMode === 'MANUAL'
          ? 'USER_SELECTED'
          : 'INFERRED_DEFAULT';
    const fallbackCalendar =
      selectedSource && effectiveTimeZoneSource === 'EXISTING_SOURCE'
        ? selectedSource.tradingCalendar
        : fallbackTradingCalendar;
    const effectiveTradingCalendar =
      selectedSource && effectiveTimeZoneSource === 'EXISTING_SOURCE'
        ? normalizePlanningCalendar(selectedSource.tradingCalendar, fallbackCalendar, plan.baseTimeframe)
        : normalizePlanningCalendar(
            input?.tradingCalendarTouched === true
              ? input?.tradingCalendar
              : recommendedTradingCalendar,
            recommendedTradingCalendar,
            plan.baseTimeframe,
          );
    const poolName = sanitizePoolName(
      isFullReimport
        ? selectedSource?.sourceName || autoGeneratedPoolName
        : override?.nameTouched
          ? override.poolName
          : selectedSource?.sourceName || autoGeneratedPoolName,
      autoGeneratedPoolName,
    );
    const targetSourceTradingCalendar = selectedSource?.tradingCalendar ?? null;
    return {
      id: plan.id,
      previewPlanId: plan.id,
      strategy: plan.strategy,
      topLevelSubfolder: preserveRelativePath(plan.topLevelSubfolder),
      poolName,
      autoGeneratedPoolName,
      sourceId,
      targetSourceId,
      targetSourceOptions: rowTargetOptions,
      hasExistingTargetOptions: !isFullReimport && rowTargetOptions.length > 1,
      symbolCount: Math.max(0, Number(plan.symbolCount) || 0),
      fileCount: Math.max(0, Number(plan.fileCount) || 0),
      baseTimeframe: plan.baseTimeframe,
      effectiveTimeZone,
      effectiveTimeZoneOrigin,
      effectiveTimeZoneSource,
      targetSourceTimeZone: selectedSource?.timeZone ?? null,
      targetSourceTimeZoneOrigin: selectedSource?.timeZoneOrigin ?? null,
      tradingCalendar: effectiveTradingCalendar,
      targetSourceTradingCalendar,
      willUpdateExistingSourceTimeZone:
        effectiveTimeZoneSource === 'FULL_REIMPORT' &&
        Boolean(selectedSource) &&
        effectiveTimeZone !== selectedSource?.timeZone,
      willUpdateExistingSourceTradingCalendar:
        effectiveTimeZoneSource === 'FULL_REIMPORT' &&
        Boolean(selectedSource) &&
        serializeCalendarKey(effectiveTradingCalendar) !==
          serializeCalendarKey(targetSourceTradingCalendar),
    };
  });

  return {
    targetSourceOptions,
    recommendedTimeZone,
    recommendedTimeZoneReason,
    recommendedTradingCalendar,
    scopeStrategy,
    availableScopeStrategies,
    planRows,
  };
};

export const validateLocalDataImportDraftTradingCalendars = (
  planDraftsRaw: readonly LocalDataImportDraftPlanValidationInput[],
): LocalDataImportDraftValidation['tradingCalendar'] => {
  const planDrafts = Array.isArray(planDraftsRaw) ? planDraftsRaw : [];
  const issues: LocalDataImportTradingCalendarValidationIssue[] = [];

  if (!planDrafts.length) {
    issues.push({
      previewPlanId: '',
      baseTimeframe: null,
      reasonCode: 'LOCAL_DATA_IMPORT_NO_CONFIRMABLE_PLAN',
    });
  }

  planDrafts.forEach((planDraft) => {
    const previewPlanId = String(planDraft.previewPlanId || '').trim();
    if (!previewPlanId || !planDraft.baseTimeframe) {
      issues.push({
        previewPlanId,
        baseTimeframe: null,
        reasonCode: 'LOCAL_DATA_IMPORT_PREVIEW_EXPIRED',
      });
      return;
    }
    if (
      !isTradingCalendarValidForLocalDataImport(
        planDraft.tradingCalendar,
        planDraft.baseTimeframe,
      )
    ) {
      issues.push({
        previewPlanId,
        baseTimeframe: planDraft.baseTimeframe,
        reasonCode: 'LOCAL_DATA_TRADING_CALENDAR_INVALID',
      });
    }
  });

  return {
    valid: issues.length === 0,
    reasonCode: firstReasonCode(issues, 'READY'),
    issueCount: issues.length,
    issues,
  };
};

const validateLocalDataImportDraftTargeting = (
  planning: LocalDataImportPlanningReadModel,
): LocalDataImportDraftValidation['targeting'] => {
  const issues = planning.planRows
    .map((row) => {
      const targetSourceId = String(row.targetSourceId || '').trim();
      if (
        !targetSourceId ||
        targetSourceId === CSV_IMPORT_TARGET_SOURCE_AUTO_CREATE_ID ||
        row.sourceId
      ) {
        return null;
      }
      return {
        previewPlanId: row.previewPlanId,
        targetSourceId,
        reasonCode: 'LOCAL_DATA_IMPORT_TARGET_SOURCE_INVALID' as const,
      };
    })
    .filter((issue): issue is LocalDataImportTargetingValidationIssue => Boolean(issue));
  return {
    valid: issues.length === 0,
    reasonCode: firstReasonCode(issues, 'READY'),
    issueCount: issues.length,
    issues,
  };
};

const validateLocalDataImportDraftRepair = (
  repairWarningCountRaw: unknown,
): LocalDataImportDraftValidation['repair'] => {
  const warningCount = Math.max(0, Math.floor(Number(repairWarningCountRaw) || 0));
  return {
    valid: warningCount === 0,
    reasonCode: warningCount > 0 ? 'LOCAL_DATA_IMPORT_REPAIR_WARNINGS' : 'READY',
    warningCount,
  };
};

const validateLocalDataImportDraftTimeZone = (
  planning: LocalDataImportPlanningReadModel,
  input?: LocalDataImportDraftPlanningInput,
): LocalDataImportDraftValidation['timeZone'] => {
  const shouldShowGlobalTimeZonePicker = planning.planRows.some(
    (row) => row.effectiveTimeZoneSource !== 'EXISTING_SOURCE',
  );
  const confirmationRequired =
    shouldShowGlobalTimeZonePicker &&
    input?.timeZoneConfidence === 'LOW' &&
    input?.importTimeZoneMode !== 'MANUAL' &&
    input?.timeZoneConfirmed !== true;
  return {
    valid: !confirmationRequired,
    reasonCode: confirmationRequired
      ? 'LOCAL_DATA_IMPORT_TIME_ZONE_CONFIRMATION_REQUIRED'
      : 'READY',
    confirmationRequired,
  };
};

const resolveBlockingIssue = (
  reasonCode: LocalDataImportDraftValidationReasonCode,
): LocalDataImportBlockingIssueKind => {
  if (
    reasonCode === 'CSV_MAPPING_REQUIRED' ||
    reasonCode === 'CSV_MAPPING_HEADER_MISSING' ||
    reasonCode === 'CSV_MAPPING_DUPLICATED'
  ) {
    return 'field-mapping';
  }
  if (reasonCode === 'LOCAL_DATA_IMPORT_TARGET_SOURCE_INVALID') {
    return 'targeting';
  }
  if (reasonCode === 'LOCAL_DATA_TRADING_CALENDAR_INVALID') {
    return 'trading-calendar';
  }
  if (reasonCode === 'LOCAL_DATA_IMPORT_REPAIR_WARNINGS') {
    return 'repair-warnings';
  }
  if (reasonCode === 'LOCAL_DATA_IMPORT_TIME_ZONE_CONFIRMATION_REQUIRED') {
    return 'time-zone';
  }
  return 'none';
};

export const validateLocalDataImportDraft = ({
  mapping,
  headers,
  planDrafts,
  validatedAt,
  planning = EMPTY_PLANNING_READ_MODEL,
  planningInput,
}: {
  mapping: CsvFieldMapping;
  headers: readonly string[];
  planDrafts: readonly LocalDataImportDraftPlanValidationInput[];
  validatedAt: string;
  planning?: LocalDataImportPlanningReadModel;
  planningInput?: LocalDataImportDraftPlanningInput;
}): LocalDataImportDraftValidation => {
  const mappingValidation = validateLocalDataImportDraftMapping(mapping, headers);
  const targetingValidation = validateLocalDataImportDraftTargeting(planning);
  const tradingCalendarValidation =
    validateLocalDataImportDraftTradingCalendars(planDrafts);
  const repairValidation = validateLocalDataImportDraftRepair(
    planningInput?.repairWarningCount,
  );
  const timeZoneValidation = validateLocalDataImportDraftTimeZone(planning, planningInput);
  const confirmReasonCode = !mappingValidation.valid
    ? mappingValidation.reasonCode
    : !targetingValidation.valid
      ? targetingValidation.reasonCode
      : !tradingCalendarValidation.valid
        ? tradingCalendarValidation.reasonCode
        : !repairValidation.valid
          ? repairValidation.reasonCode
          : !timeZoneValidation.valid
            ? timeZoneValidation.reasonCode
            : 'READY';
  return {
    mapping: mappingValidation,
    targeting: targetingValidation,
    tradingCalendar: tradingCalendarValidation,
    repair: repairValidation,
    timeZone: timeZoneValidation,
    confirm: {
      enabled: confirmReasonCode === 'READY',
      reasonCode: confirmReasonCode,
    },
    blockingIssue: {
      kind: resolveBlockingIssue(confirmReasonCode),
      reasonCode: confirmReasonCode,
    },
    planning,
    validatedAt,
  };
};

export const buildLocalDataImportDraftValidationFailure = (
  reasonCode: Exclude<LocalDataImportDraftValidationReasonCode, 'READY'>,
  validatedAt: string,
): LocalDataImportDraftValidation => ({
  mapping: {
    valid: false,
    reasonCode,
    issueCount: 1,
    issues: [],
  },
  targeting: {
    valid: reasonCode !== 'LOCAL_DATA_IMPORT_TARGET_SOURCE_INVALID',
    reasonCode:
      reasonCode === 'LOCAL_DATA_IMPORT_TARGET_SOURCE_INVALID'
        ? reasonCode
        : 'READY',
    issueCount: reasonCode === 'LOCAL_DATA_IMPORT_TARGET_SOURCE_INVALID' ? 1 : 0,
    issues: [],
  },
  tradingCalendar: {
    valid: false,
    reasonCode,
    issueCount: 1,
    issues: [
      {
        previewPlanId: '',
        baseTimeframe: null,
        reasonCode:
          reasonCode === 'LOCAL_DATA_IMPORT_NO_CONFIRMABLE_PLAN'
            ? 'LOCAL_DATA_IMPORT_NO_CONFIRMABLE_PLAN'
            : 'LOCAL_DATA_IMPORT_PREVIEW_EXPIRED',
      },
    ],
  },
  repair: {
    valid: true,
    reasonCode: 'READY',
    warningCount: 0,
  },
  timeZone: {
    valid: true,
    reasonCode: 'READY',
    confirmationRequired: false,
  },
  confirm: {
    enabled: false,
    reasonCode,
  },
  blockingIssue: {
    kind: resolveBlockingIssue(reasonCode),
    reasonCode,
  },
  planning: EMPTY_PLANNING_READ_MODEL,
  validatedAt,
});
