// SPDX-License-Identifier: GPL-3.0-only

import type {
  DesktopHelpArticleId,
  DesktopHelpCategoryId,
  DesktopHelpContextId,
  DesktopHelpSettingsTabId,
} from "@/domains/desktop-help/desktopHelpTypes";
import type { WorkspacePage } from "@/frontend-kernel/workspacePageModel";

type DesktopHelpArticleMetadata = {
  id: DesktopHelpArticleId;
  categoryId: DesktopHelpCategoryId;
  contextIds: readonly DesktopHelpContextId[];
  recommendationOrder: number;
  relatedArticleIds: readonly DesktopHelpArticleId[];
  targetWorkspace: WorkspacePage | null;
  targetSettingsTab?: DesktopHelpSettingsTabId;
};

export const DESKTOP_HELP_ARTICLE_METADATA = [
  {
    id: "getting-started",
    categoryId: "START",
    contextIds: ["COMMAND_CENTER", "SETTINGS_GENERAL"],
    recommendationOrder: 10,
    relatedArticleIds: ["data-prepare", "trainer-prepare", "command-center-overview"],
    targetWorkspace: "COMMAND_CENTER",
  },
  {
    id: "command-center-overview",
    categoryId: "START",
    contextIds: ["COMMAND_CENTER"],
    recommendationOrder: 20,
    relatedArticleIds: ["getting-started", "trainer-prepare", "challenge-mode-selection"],
    targetWorkspace: "COMMAND_CENTER",
  },
  {
    id: "trainer-prepare",
    categoryId: "TRAINING",
    contextIds: ["TRAINER", "TRAINER_PREP"],
    recommendationOrder: 30,
    relatedArticleIds: ["trainer-session", "data-prepare", "review-overview"],
    targetWorkspace: "TRAINER",
  },
  {
    id: "trainer-session",
    categoryId: "TRAINING",
    contextIds: ["TRAINER", "TRAINER_SESSION"],
    recommendationOrder: 40,
    relatedArticleIds: ["trainer-prepare", "review-overview", "notes-review-links"],
    targetWorkspace: "TRAINER",
  },
  {
    id: "review-overview",
    categoryId: "REVIEW",
    contextIds: ["HISTORY", "HISTORY_OVERVIEW"],
    recommendationOrder: 50,
    relatedArticleIds: ["review-behavior", "review-archive", "notes-review-links"],
    targetWorkspace: "HISTORY",
  },
  {
    id: "review-behavior",
    categoryId: "REVIEW",
    contextIds: ["HISTORY", "HISTORY_BEHAVIOR"],
    recommendationOrder: 60,
    relatedArticleIds: ["review-overview", "review-archive", "notes-create"],
    targetWorkspace: "HISTORY",
  },
  {
    id: "review-archive",
    categoryId: "REVIEW",
    contextIds: ["HISTORY", "HISTORY_ARCHIVE"],
    recommendationOrder: 70,
    relatedArticleIds: ["review-overview", "notes-review-links", "settings-advanced"],
    targetWorkspace: "HISTORY",
  },
  {
    id: "challenge-mode-selection",
    categoryId: "CHALLENGE",
    contextIds: ["SPECIAL_TRAINING", "SPECIAL_TRAINING_MODE_SELECTION"],
    recommendationOrder: 80,
    relatedArticleIds: ["challenge-fast-decision", "challenge-risk-survival", "data-prepare"],
    targetWorkspace: "SPECIAL_TRAINING",
  },
  {
    id: "challenge-fast-decision",
    categoryId: "CHALLENGE",
    contextIds: ["SPECIAL_TRAINING", "SPECIAL_TRAINING_FAST_DECISION"],
    recommendationOrder: 90,
    relatedArticleIds: ["challenge-mode-selection", "challenge-settlement", "challenge-stats"],
    targetWorkspace: "SPECIAL_TRAINING",
  },
  {
    id: "challenge-risk-survival",
    categoryId: "CHALLENGE",
    contextIds: ["SPECIAL_TRAINING", "SPECIAL_TRAINING_RISK_SURVIVAL"],
    recommendationOrder: 100,
    relatedArticleIds: ["challenge-mode-selection", "challenge-settlement", "challenge-stats"],
    targetWorkspace: "SPECIAL_TRAINING",
  },
  {
    id: "challenge-settlement",
    categoryId: "CHALLENGE",
    contextIds: ["SPECIAL_TRAINING", "SPECIAL_TRAINING_SETTLEMENT"],
    recommendationOrder: 110,
    relatedArticleIds: ["challenge-fast-decision", "challenge-risk-survival", "challenge-stats"],
    targetWorkspace: "SPECIAL_TRAINING",
  },
  {
    id: "challenge-stats",
    categoryId: "ANALYSIS",
    contextIds: ["CHALLENGE_STATS"],
    recommendationOrder: 120,
    relatedArticleIds: ["challenge-settlement", "review-overview", "notes-review-links"],
    targetWorkspace: "CHALLENGE_STATS",
  },
  {
    id: "indicator-create",
    categoryId: "ANALYSIS",
    contextIds: ["CUSTOM_INDICATOR"],
    recommendationOrder: 130,
    relatedArticleIds: ["indicator-reference", "backtest-configure", "data-prepare"],
    targetWorkspace: "CUSTOM_INDICATOR",
  },
  {
    id: "indicator-reference",
    categoryId: "ANALYSIS",
    contextIds: ["CUSTOM_INDICATOR"],
    recommendationOrder: 140,
    relatedArticleIds: ["indicator-create", "backtest-configure", "data-import"],
    targetWorkspace: "CUSTOM_INDICATOR",
  },
  {
    id: "backtest-configure",
    categoryId: "ANALYSIS",
    contextIds: ["STRATEGY_BACKTEST"],
    recommendationOrder: 150,
    relatedArticleIds: ["backtest-results", "indicator-create", "data-prepare"],
    targetWorkspace: "STRATEGY_BACKTEST",
  },
  {
    id: "backtest-results",
    categoryId: "ANALYSIS",
    contextIds: ["STRATEGY_BACKTEST"],
    recommendationOrder: 160,
    relatedArticleIds: ["backtest-configure", "review-overview", "notes-review-links"],
    targetWorkspace: "STRATEGY_BACKTEST",
  },
  {
    id: "notes-create",
    categoryId: "REVIEW",
    contextIds: ["NOTES"],
    recommendationOrder: 170,
    relatedArticleIds: ["notes-review-links", "review-overview", "challenge-stats"],
    targetWorkspace: "NOTES",
  },
  {
    id: "notes-review-links",
    categoryId: "REVIEW",
    contextIds: ["NOTES"],
    recommendationOrder: 180,
    relatedArticleIds: ["notes-create", "review-archive", "challenge-settlement"],
    targetWorkspace: "NOTES",
  },
  {
    id: "data-acquire",
    categoryId: "DATA",
    contextIds: ["COMMAND_CENTER", "TRAINER_PREP", "DATA"],
    recommendationOrder: 1,
    relatedArticleIds: ["data-source-by-market", "data-prepare", "data-import"],
    targetWorkspace: "DATA",
  },
  {
    id: "data-source-by-market",
    categoryId: "DATA",
    contextIds: ["DATA"],
    recommendationOrder: 2,
    relatedArticleIds: ["data-acquire", "data-prepare", "data-import"],
    targetWorkspace: "DATA",
  },
  {
    id: "data-prepare",
    categoryId: "DATA",
    contextIds: ["DATA"],
    recommendationOrder: 3,
    relatedArticleIds: ["data-acquire", "data-import", "data-source-by-market"],
    targetWorkspace: "DATA",
  },
  {
    id: "data-import",
    categoryId: "DATA",
    contextIds: ["DATA"],
    recommendationOrder: 4,
    relatedArticleIds: ["data-prepare", "data-manage", "data-acquire"],
    targetWorkspace: "DATA",
  },
  {
    id: "data-manage",
    categoryId: "DATA",
    contextIds: ["DATA", "SETTINGS_DATA_TRANSFER"],
    recommendationOrder: 5,
    relatedArticleIds: ["data-prepare", "data-import", "settings-transfer"],
    targetWorkspace: "DATA",
  },
  {
    id: "settings-general",
    categoryId: "SETTINGS",
    contextIds: ["SETTINGS", "SETTINGS_GENERAL"],
    recommendationOrder: 200,
    relatedArticleIds: ["settings-about", "getting-started"],
    targetWorkspace: "SETTINGS",
    targetSettingsTab: "GENERAL",
  },
  {
    id: "settings-transfer",
    categoryId: "SETTINGS",
    contextIds: ["SETTINGS", "SETTINGS_DATA_TRANSFER"],
    recommendationOrder: 210,
    relatedArticleIds: ["data-manage", "settings-advanced"],
    targetWorkspace: "SETTINGS",
    targetSettingsTab: "DATA_TRANSFER",
  },
  {
    id: "settings-about",
    categoryId: "SETTINGS",
    contextIds: ["SETTINGS", "SETTINGS_ABOUT"],
    recommendationOrder: 220,
    relatedArticleIds: ["getting-started", "settings-general", "settings-advanced"],
    targetWorkspace: "SETTINGS",
    targetSettingsTab: "ABOUT",
  },
  {
    id: "settings-advanced",
    categoryId: "SETTINGS",
    contextIds: ["SETTINGS", "SETTINGS_ADVANCED"],
    recommendationOrder: 230,
    relatedArticleIds: ["review-archive", "settings-transfer", "settings-about"],
    targetWorkspace: "SETTINGS",
    targetSettingsTab: "ADVANCED",
  },
] as const satisfies readonly DesktopHelpArticleMetadata[];

export const DESKTOP_HELP_CONTEXT_RECOMMENDATIONS = {
  COMMAND_CENTER: ["getting-started", "command-center-overview", "trainer-prepare", "data-acquire"],
  TRAINER: ["trainer-prepare", "trainer-session", "data-prepare", "review-overview"],
  TRAINER_PREP: ["trainer-prepare", "data-acquire", "data-prepare", "data-import"],
  TRAINER_SESSION: ["trainer-session", "review-overview", "notes-review-links", "trainer-prepare"],
  HISTORY: ["review-overview", "review-behavior", "review-archive", "notes-review-links"],
  HISTORY_OVERVIEW: ["review-overview", "review-behavior", "review-archive", "notes-review-links"],
  HISTORY_BEHAVIOR: ["review-behavior", "review-overview", "notes-create", "review-archive"],
  HISTORY_ARCHIVE: ["review-archive", "review-overview", "notes-review-links", "settings-advanced"],
  SPECIAL_TRAINING: ["challenge-mode-selection", "challenge-fast-decision", "challenge-risk-survival", "data-prepare"],
  SPECIAL_TRAINING_MODE_SELECTION: ["challenge-mode-selection", "challenge-fast-decision", "challenge-risk-survival", "data-prepare"],
  SPECIAL_TRAINING_FAST_DECISION: ["challenge-fast-decision", "challenge-settlement", "challenge-stats", "challenge-mode-selection"],
  SPECIAL_TRAINING_RISK_SURVIVAL: ["challenge-risk-survival", "challenge-settlement", "challenge-stats", "challenge-mode-selection"],
  SPECIAL_TRAINING_SETTLEMENT: ["challenge-settlement", "challenge-stats", "notes-review-links", "review-overview"],
  CHALLENGE_STATS: ["challenge-stats", "challenge-settlement", "review-overview", "notes-review-links"],
  CUSTOM_INDICATOR: ["indicator-create", "indicator-reference", "data-prepare", "backtest-configure"],
  STRATEGY_BACKTEST: ["backtest-configure", "backtest-results", "indicator-create", "data-prepare"],
  NOTES: ["notes-create", "notes-review-links", "review-archive", "challenge-stats"],
  DATA: ["data-acquire", "data-source-by-market", "data-prepare", "data-import"],
  SETTINGS: ["settings-general", "settings-transfer", "settings-about", "settings-advanced"],
  SETTINGS_GENERAL: ["settings-general", "getting-started", "settings-about", "settings-advanced"],
  SETTINGS_DATA_TRANSFER: ["settings-transfer", "data-manage", "data-prepare", "settings-advanced"],
  SETTINGS_ABOUT: ["settings-about", "getting-started", "settings-general", "settings-advanced"],
  SETTINGS_ADVANCED: ["settings-advanced", "review-archive", "settings-transfer", "settings-about"],
} as const satisfies Record<
  DesktopHelpContextId,
  readonly [DesktopHelpArticleId, DesktopHelpArticleId, DesktopHelpArticleId, DesktopHelpArticleId]
>;
